# Wolfsburg

In [2]:
from googleapiclient.discovery import build
import time
import pandas as pd

API_KEY = 'AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ'  # Replace with your actual API key
youtube = build('youtube', 'v3', developerKey=API_KEY)

def get_channel_id_from_url(url):
    if '@' in url:
        handle = url.split('@')[1]
        res = youtube.search().list(
            q=handle,
            type='channel',
            maxResults=1,
            part='snippet'
        ).execute()
        if res['items']:
            return res['items'][0]['snippet']['channelId']
    return None

def get_uploads_playlist_id(channel_id):
    res = youtube.channels().list(
        part='contentDetails',
        id=channel_id
    ).execute()
    if res['items']:
        return res['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    return None

def get_recent_video_ids(playlist_id, count):
    video_ids = []
    next_page_token = None

    while len(video_ids) < count:
        res = youtube.playlistItems().list(
            playlistId=playlist_id,
            part='contentDetails',
            maxResults=50,
            pageToken=next_page_token
        ).execute()

        for item in res['items']:
            video_ids.append(item['contentDetails']['videoId'])
            if len(video_ids) >= count:
                break

        next_page_token = res.get('nextPageToken')
        if not next_page_token:
            break

    return video_ids

def get_top_level_comments(video_id, max_comments=None):
    comments = []
    next_page_token = None

    while True:
        try:
            res = youtube.commentThreads().list(
                part='snippet',
                videoId=video_id,
                maxResults=100,
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in res['items']:
                snippet = item['snippet']['topLevelComment']['snippet']
                comments.append({
                    'Commenter Name': snippet['authorDisplayName'],
                    'Comment': snippet['textDisplay'],
                    'Comment Like Count': snippet['likeCount']
                })

                if max_comments and len(comments) >= max_comments:
                    return comments

            next_page_token = res.get('nextPageToken')
            if not next_page_token:
                break

        except Exception as e:
            print(f"Error fetching comments for video {video_id}: {e}")
            break

        time.sleep(0.5)

    return comments

def get_video_metadata(video_id):
    res = youtube.videos().list(
        part='snippet,statistics',
        id=video_id
    ).execute()

    if not res['items']:
        return None

    item = res['items'][0]
    return {
        'Video ID': video_id,
        'Video Title': item['snippet']['title'],
        'View Count': item['statistics'].get('viewCount'),
        'Like Count': item['statistics'].get('likeCount'),
        'Comment Count': item['statistics'].get('commentCount'),
        'YouTube Channel': item['snippet']['channelTitle']
    }

def collect_all_comments(channel_url, num_videos, output_filename):
    channel_id = get_channel_id_from_url(channel_url)
    if not channel_id:
        print(f"❌ Could not find channel ID from URL: {channel_url}")
        return

    playlist_id = get_uploads_playlist_id(channel_id)
    video_ids = get_recent_video_ids(playlist_id, num_videos)
    print(f"📺 Processing {len(video_ids)} videos from {channel_url}")

    all_comments = []

    for i, vid in enumerate(video_ids, 1):
        print(f"▶️ [{i}/{len(video_ids)}] Video ID: {vid}")
        video_meta = get_video_metadata(vid)
        if not video_meta:
            continue

        comments = get_top_level_comments(vid)
        for c in comments:
            all_comments.append({
                'Video Title': video_meta['Video Title'],
                'Like Count': video_meta['Like Count'],
                'View Count': video_meta['View Count'],
                'Comment Count': video_meta['Comment Count'],
                'Commenter Name': c['Commenter Name'],
                'Comment': c['Comment'],
                'Comment Like Count': c['Comment Like Count'],
                'YouTube Channel': video_meta['YouTube Channel']
            })

        time.sleep(1)

    df = pd.DataFrame(all_comments)
    df.to_csv(output_filename, index=False, encoding='utf-8-sig')
    print(f"💾 Saved {len(all_comments)} comments to: {output_filename}")

if __name__ == '__main__':
    barca_url = "https://www.youtube.com/@VfLWolfsburg"
    collect_all_comments(barca_url, num_videos=1000, output_filename="wolfsburg.csv")

📺 Processing 1000 videos from https://www.youtube.com/@VfLWolfsburg
▶️ [1/1000] Video ID: TGhZ4dfQg9g
▶️ [2/1000] Video ID: S6_P83eKqIA
▶️ [3/1000] Video ID: O_b_OFUHMiA
▶️ [4/1000] Video ID: I0xlqmJcUpc
▶️ [5/1000] Video ID: gcK9r9FZHQc
Error fetching comments for video gcK9r9FZHQc: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=gcK9r9FZHQc&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [6/1000] Video ID: yYcCCezx_l4
▶️ [7/1000] Video ID: VTwn3CXMibI
▶️ [8/1000] Video ID: Tn550ct5IrI
▶️ [9/1000] Video ID: S9OdUvneSN4
▶️ [10/1000] Video ID: uhqH6th8JA4
▶️ [11/1000] Video ID: dg3lykdpZkE
▶️ [12/1000] Video ID: i9tPw07iv2I
▶️ [13/1000] Video ID: sdCOhHrUrkw
▶️ [14/1000] Video ID: z8TUZA03fxo
▶️ [15/1000] Video ID: gdvBX0mnnx0
▶️ [16/1000] Video ID: zAW7SAGy33M
▶️ [17/1000] Video ID: iEx5GlN-k5A
▶️ [18/1000] Video ID: oDyMzAfFTAI
▶️ [19/1000] Video ID: bOvz63umfFA
▶️ [20/1000] Video ID: L19EyRh_KRQ
▶️ [21/1000] Video ID: tClKup24Xnc
▶️ [22/1000] Video ID: rANaz96gHIs
▶️ [23/1000] Video ID: 3wPACdLLdZo
▶️ [24/1000] Video ID: 6swwv4ngHPM
▶️ [25/1000] Video ID: xtISFNUnKmQ
▶️ [26/1000] Video ID: p_XkfR_Zv4w
▶️ [27/1000] Video ID: 3mGM_4NAsQc
▶️ [28/1000] Video ID: pbp0XckZQkQ
▶️ [29/1000] Video ID: B3Qq3Y37Yts
▶️ [30/1000] Video ID: RxY9IiJf4Uw
▶️ [31/1000] Video ID: uyzExkoQqls
▶️ [32/1000] Video ID: cDbbQs5hHpA
▶️ [33/1000] Video ID: CXG-9ucwgUI
▶️ [34/1000] Video ID: XtYVZkY0dSE
▶️ [35/1000] Video ID: eSx609dSdSM
▶️ [36/1000] Video ID: P-OfVjlptM4
▶️ [37/1000] Video ID: RyvkB9j0t4U
▶️ [38/1000] Video ID: kYLiAQvPjRo
▶️ [39/1000] Video ID: OMkr8dCDcw0
▶️ [40/1000] Video ID: MQyIroG95Dg
▶️ [41/1000] Video ID: cmEXoKIG3lw
▶️ [42/1000] Video ID: Ybvlm3E6WiE
▶️ [43/1000] Video ID: wK6YcgMzonE
▶️ [44/1000] Video ID: FuOPpRla9Qg
▶️ [45/1000] Video ID: PX0azvH5tXs
▶️ [46/1000] Video ID: QWZXG8ol5E0
▶️ [47/1000] Video ID: R990PM9drQs
▶️ [48/1000] Video ID: nkBk1DEC6Xw
▶️ [49/1000] Video ID: WB-Kfv4ubDA
▶️ [50/1000] Video ID: omilP9lRbEs
▶️ [51/1000] Video ID: 7-UJ5EqTg9k
▶️ [52/1000] Video ID: fYIpl1PCnzI
▶️ [53/1000] Video ID: ljJiM8y7oBE
▶️ [54/1000] Video ID: v6e1M0Q2Sos
▶️ [55/1000] Video ID: ShwhpXxVJnM
▶️ [56/1000] Video ID: k9UzTfncz38
▶️ [57/1000] Video ID: 33p0LJ-wf-Q
▶️ [58/1000] Video ID: qbojmzvLQUU
▶️ [59/1000] Video ID: M3HvbnGnfbE
▶️ [60/1000] Video ID: w92-lAtKs8U
▶️ [61/1000] Video ID: dHK67JukXEw
▶️ [62/1000] Video ID: UEanrfzPLVA
▶️ [63/1000] Video ID: nvHw0YCYW9s
▶️ [64/1000] Video ID: oGHGpq4NeYY
▶️ [65/1000] Video ID: xjvdpHnY_SQ
▶️ [66/1000] Video ID: kx_0I23ONyc
▶️ [67/1000] Video ID: Yg0OxAlCmAU
▶️ [68/1000] Video ID: moNLb2hFR50
▶️ [69/1000] Video ID: ttRnczNq2Ps
▶️ [70/1000] Video ID: 6XQWs04CVS0
▶️ [71/1000] Video ID: OxV9YPvfUxg
▶️ [72/1000] Video ID: jShuSC6DiRQ
▶️ [73/1000] Video ID: M6s2FzhfOS8
▶️ [74/1000] Video ID: i3QEjRLWyzs
▶️ [75/1000] Video ID: RD-otl8zCxQ
▶️ [76/1000] Video ID: NK15JKohht0
▶️ [77/1000] Video ID: Q37xL4kY8xM
▶️ [78/1000] Video ID: pjwIp8w2l5A
▶️ [79/1000] Video ID: XctYU5TLsyU
▶️ [80/1000] Video ID: fdLSW65vtQI
▶️ [81/1000] Video ID: oyavI5dtrDQ
▶️ [82/1000] Video ID: b7699xVgsgA
▶️ [83/1000] Video ID: Z02zfAeM9Oc
▶️ [84/1000] Video ID: GPwGfwF6SdM
▶️ [85/1000] Video ID: fi3QK62gTgw
▶️ [86/1000] Video ID: 93F7H9lWb_Y
▶️ [87/1000] Video ID: GK_kaiBz5HY
▶️ [88/1000] Video ID: QqxAjcdAwlE
▶️ [89/1000] Video ID: Vb811wOI_aw
▶️ [90/1000] Video ID: aX_tLZOlqBw
▶️ [91/1000] Video ID: fmkjJCvMRpE
▶️ [92/1000] Video ID: fbHmADuhuvk
▶️ [93/1000] Video ID: oUlDz_6YclI
▶️ [94/1000] Video ID: kEZjnj6d2XY
▶️ [95/1000] Video ID: BFoLVH5XUKg
▶️ [96/1000] Video ID: 5cPVveQERS4
▶️ [97/1000] Video ID: m5uZiYS2bgw
▶️ [98/1000] Video ID: PmM4yrsA3tU
▶️ [99/1000] Video ID: b50-_jgv1BY
▶️ [100/1000] Video ID: 9NFiFTtWz3w
▶️ [101/1000] Video ID: jMHgFU6z00c
▶️ [102/1000] Video ID: JQVPsHHIMLQ
▶️ [103/1000] Video ID: 2DUSgw7rIt0
▶️ [104/1000] Video ID: ZiEem5Si3l8
▶️ [105/1000] Video ID: YTKhbIE5das
▶️ [106/1000] Video ID: 1tNVs0JMk3c
▶️ [107/1000] Video ID: stvfI4ACHes
▶️ [108/1000] Video ID: Hxnwoc29VdM
▶️ [109/1000] Video ID: hZOkmvsjXnA
▶️ [110/1000] Video ID: u-dJRAchog8
▶️ [111/1000] Video ID: hfBswRepdLY
▶️ [112/1000] Video ID: HLcmDG4huAw
▶️ [113/1000] Video ID: T-SDCelGOoI
▶️ [114/1000] Video ID: xtrUQClNo0M
▶️ [115/1000] Video ID: zfynY65wd74
▶️ [116/1000] Video ID: BPPjPRGOOCI
▶️ [117/1000] Video ID: OgMdDhLUrEM
▶️ [118/1000] Video ID: V0aHoFXTnXM
▶️ [119/1000] Video ID: oKM-_IhQAT4
▶️ [120/1000] Video ID: kTW0zIdvYE4
▶️ [121/1000] Video ID: 08XlcYoesRw
▶️ [122/1000] Video ID: kau7cddlWgU
▶️ [123/1000] Video ID: cgBvsPnG32o
▶️ [124/1000] Video ID: nVe4WMT-noc
▶️ [125/1000] Video ID: jqJrzcA3g7o
▶️ [126/1000] Video ID: rnHijKtf9sI
▶️ [127/1000] Video ID: Pa0hnlndFrw
▶️ [128/1000] Video ID: -wteX5HXTjs
▶️ [129/1000] Video ID: 2EnFHXVCFXE
▶️ [130/1000] Video ID: 6ganvYj0Xh4
▶️ [131/1000] Video ID: vzXuLvSq-9A
▶️ [132/1000] Video ID: pg3BdY_oq_c
▶️ [133/1000] Video ID: a_roNugagJo
▶️ [134/1000] Video ID: 1nF_rwrt5jw
▶️ [135/1000] Video ID: hkF3bJvD_Zg
▶️ [136/1000] Video ID: KDjDNyAvNZQ
▶️ [137/1000] Video ID: XuocNhhK2Ho
▶️ [138/1000] Video ID: m6WJaaeJZaU
▶️ [139/1000] Video ID: DVtSFwupq9Q
▶️ [140/1000] Video ID: GTMaIvFUMu4
▶️ [141/1000] Video ID: 4m1Wt_eS8Lw
▶️ [142/1000] Video ID: 2Mt4UowQD8A
▶️ [143/1000] Video ID: v355yd6Jq3k
▶️ [144/1000] Video ID: R8JO6E20Yz4
▶️ [145/1000] Video ID: Jm752FL2Ov0
▶️ [146/1000] Video ID: u4A5Q0N2x88
▶️ [147/1000] Video ID: qfoGpspUQ4A
▶️ [148/1000] Video ID: OeFSEs-3maI
▶️ [149/1000] Video ID: k7B1A81LEAk
▶️ [150/1000] Video ID: 7Pj_W11-iro
▶️ [151/1000] Video ID: k8OYOh6Nqrg
▶️ [152/1000] Video ID: h_W6J6DTQKk
▶️ [153/1000] Video ID: O6bqCObEHfE
▶️ [154/1000] Video ID: 2mXLQ6RC6dY
▶️ [155/1000] Video ID: BLSe6-oWGow
▶️ [156/1000] Video ID: AtsvqZnx7CE
▶️ [157/1000] Video ID: ioAaefpMBZQ
▶️ [158/1000] Video ID: OyZLDK9dFmw
▶️ [159/1000] Video ID: Jer6m_fcCoQ
▶️ [160/1000] Video ID: EKJruMzSXXw
▶️ [161/1000] Video ID: XX900JM7Qh8
▶️ [162/1000] Video ID: VZqwCmzLWIs
▶️ [163/1000] Video ID: Vnf7PGLvHq4
▶️ [164/1000] Video ID: XiXEZaJatkQ
▶️ [165/1000] Video ID: 8p8oPRLR5GA
▶️ [166/1000] Video ID: zxg07JPZ4f8
▶️ [167/1000] Video ID: kVFmodjQmlo
▶️ [168/1000] Video ID: U1LZmESQwMo
▶️ [169/1000] Video ID: 5BlCXyXZC6Y
▶️ [170/1000] Video ID: tI8l-bB5qcc
▶️ [171/1000] Video ID: V495QCrf5wc
▶️ [172/1000] Video ID: uY_lYe5gtTc
▶️ [173/1000] Video ID: TDztCzXrsgw
▶️ [174/1000] Video ID: APOKOQwTNzI
▶️ [175/1000] Video ID: _OxgPLRYV8s
▶️ [176/1000] Video ID: x5OxmdP3xh0
▶️ [177/1000] Video ID: oRdA2vcNi6Y
▶️ [178/1000] Video ID: IXiSiW72TZE
▶️ [179/1000] Video ID: Ma9bsoIp5yU
▶️ [180/1000] Video ID: IevXDcNA-UI
▶️ [181/1000] Video ID: udDekoYnZuU
▶️ [182/1000] Video ID: Btmn4omf-DM
▶️ [183/1000] Video ID: 4VjkUZerxzw
▶️ [184/1000] Video ID: LtrLR4W1FAU
▶️ [185/1000] Video ID: Kx6Dj9x1gmU
▶️ [186/1000] Video ID: E3g-8DFD_j8
▶️ [187/1000] Video ID: I9W9rKpFjh4
▶️ [188/1000] Video ID: 2A3774lE4fE
▶️ [189/1000] Video ID: NkZBAQuQm3I
▶️ [190/1000] Video ID: BPcwqMC_UaM
▶️ [191/1000] Video ID: 3dkUrIn1dOU
▶️ [192/1000] Video ID: eOGwAgd3_Fo
▶️ [193/1000] Video ID: rkn5ztpMx4Q
▶️ [194/1000] Video ID: zNnKwwFQQUI
▶️ [195/1000] Video ID: bp8l6HJVIKY
▶️ [196/1000] Video ID: scEtFx_C69M
▶️ [197/1000] Video ID: tAe8z0gIGoE
▶️ [198/1000] Video ID: h3_FAtoXNr8
▶️ [199/1000] Video ID: sx0OR8FEo60
▶️ [200/1000] Video ID: ygWfOiVl8Ns
▶️ [201/1000] Video ID: hMg-4TFUHmA
▶️ [202/1000] Video ID: xbcD0oZiiZ8
▶️ [203/1000] Video ID: 2P6PsEEBTvA
▶️ [204/1000] Video ID: jOGlDcI10Yg
▶️ [205/1000] Video ID: BsQe4hH0dHg
▶️ [206/1000] Video ID: 2Ig6w6ltv9U
▶️ [207/1000] Video ID: H8NvEIc7dLw
▶️ [208/1000] Video ID: CczrmoHg38k
▶️ [209/1000] Video ID: XFH8G47DW3c
▶️ [210/1000] Video ID: 8MizWhxf0go
▶️ [211/1000] Video ID: apFHCK2RTxk
▶️ [212/1000] Video ID: j4Kay9qm-iw
▶️ [213/1000] Video ID: QEt8yqG1-ew
▶️ [214/1000] Video ID: 5QFC8vfK3aE
▶️ [215/1000] Video ID: Epa-_5hKNUM
▶️ [216/1000] Video ID: SMY28dKc3GQ
▶️ [217/1000] Video ID: zKa2rajGM58
▶️ [218/1000] Video ID: zEFx0jbHHT8
▶️ [219/1000] Video ID: ZltlgBBEDGk
▶️ [220/1000] Video ID: vfEmWKD-CVM
▶️ [221/1000] Video ID: PPYVzLa0M_4
▶️ [222/1000] Video ID: s1aRSJG9zgc
▶️ [223/1000] Video ID: upFqV6umL9M
▶️ [224/1000] Video ID: UPBiJpHQXy0
▶️ [225/1000] Video ID: QZ48p04mGpU
▶️ [226/1000] Video ID: yFpOL9CKA8A
▶️ [227/1000] Video ID: na8YBlpejc0
▶️ [228/1000] Video ID: _zKNlkoxbIg
▶️ [229/1000] Video ID: KU0Uv3FC6ME
▶️ [230/1000] Video ID: _tB0pxqKkiQ
▶️ [231/1000] Video ID: Ic-_giZVtjU
▶️ [232/1000] Video ID: 7rt1P4A8Sd0
▶️ [233/1000] Video ID: AFd2Fm_aKMo
▶️ [234/1000] Video ID: rG8GIVhNTLs
▶️ [235/1000] Video ID: iFlRP1t_ax4
▶️ [236/1000] Video ID: sILOKih5yrk
▶️ [237/1000] Video ID: q1u1ifWxM9g
▶️ [238/1000] Video ID: ElCXLRJv8Sg
▶️ [239/1000] Video ID: 0WYm88eid40
▶️ [240/1000] Video ID: vYyPG30kSCc
▶️ [241/1000] Video ID: 8oZ_dwvKbAM
▶️ [242/1000] Video ID: dcs3VuWTvrg
▶️ [243/1000] Video ID: Nk9ihDHBfw0
▶️ [244/1000] Video ID: 67pLYK9gZ2A
▶️ [245/1000] Video ID: 6cxwqZdtLtQ
▶️ [246/1000] Video ID: Ww2Fcb9QVq8
▶️ [247/1000] Video ID: FR4_MQauJZ8
▶️ [248/1000] Video ID: lvp7k51i18c
▶️ [249/1000] Video ID: I2nekwhDZxg
▶️ [250/1000] Video ID: cSQlFoMdXKU
▶️ [251/1000] Video ID: yvHO_aSj7Jc
▶️ [252/1000] Video ID: C9zKj8ODdHQ
▶️ [253/1000] Video ID: LwpENqsUCI4
▶️ [254/1000] Video ID: jIkTzjhoR0I
▶️ [255/1000] Video ID: ymVphEmQcCo
▶️ [256/1000] Video ID: QUF0sfyVXXc
▶️ [257/1000] Video ID: boxhmou9aRE
▶️ [258/1000] Video ID: tAULb1L0MEw
▶️ [259/1000] Video ID: fatVBM_1d4U
▶️ [260/1000] Video ID: CM-WMqe2xqY
▶️ [261/1000] Video ID: 3I90w0ssIv4
▶️ [262/1000] Video ID: 3naHW9flVtA
▶️ [263/1000] Video ID: CKH7qcA1gvw
▶️ [264/1000] Video ID: UKLP2axPboM
▶️ [265/1000] Video ID: G44PkJGvqG4
▶️ [266/1000] Video ID: F4hS2IR2h2s
▶️ [267/1000] Video ID: Yf0caMesXxI
▶️ [268/1000] Video ID: jrNg2fK1TA0
▶️ [269/1000] Video ID: V8kOmebDXuQ
▶️ [270/1000] Video ID: SZX3C72yKSI
▶️ [271/1000] Video ID: RHrb-zrv_ok
▶️ [272/1000] Video ID: 66YyB-AzTrs
▶️ [273/1000] Video ID: RIuBcqIvbcE
▶️ [274/1000] Video ID: _2Acz8smf5M
▶️ [275/1000] Video ID: XxarSqbbwS4
▶️ [276/1000] Video ID: 5Jmh8Vhj-HY
▶️ [277/1000] Video ID: gK1Axs2Q5f8
▶️ [278/1000] Video ID: 0dbmy2z3Za4
▶️ [279/1000] Video ID: 90pgaXDTRQA
▶️ [280/1000] Video ID: kVsEm0LkMjo
▶️ [281/1000] Video ID: l6bSQcOPQVs
▶️ [282/1000] Video ID: AnMbM01Au9Q
▶️ [283/1000] Video ID: xwTM6TStwxc
▶️ [284/1000] Video ID: nD7GZQV7sJI
▶️ [285/1000] Video ID: pXWYvqIZGuQ
▶️ [286/1000] Video ID: 0vnKU6Cpiv8
▶️ [287/1000] Video ID: feXDQlPI_q8
▶️ [288/1000] Video ID: 3_HX1DxhIb4
▶️ [289/1000] Video ID: EhG5YTUG7rU
▶️ [290/1000] Video ID: CJqqjLl3PMY
▶️ [291/1000] Video ID: Qubw_VvbZGg
▶️ [292/1000] Video ID: HDdoYWoC2C8
▶️ [293/1000] Video ID: ikxUs8gmOO8
▶️ [294/1000] Video ID: 6LzY3K21we4
▶️ [295/1000] Video ID: kMKToyvsMBE
▶️ [296/1000] Video ID: GX7zeW-sysY
▶️ [297/1000] Video ID: D_ZkycompTg
▶️ [298/1000] Video ID: KRMEmpmnQVQ
▶️ [299/1000] Video ID: -sp5bWGNhyU
▶️ [300/1000] Video ID: wPmnMDVy8tk
▶️ [301/1000] Video ID: AdmGRsZp0UM
▶️ [302/1000] Video ID: ZmYKvx-05mw
▶️ [303/1000] Video ID: zIa7MfcKpOM
▶️ [304/1000] Video ID: Fc93P_-GYvw
▶️ [305/1000] Video ID: SYxWJ1k1r4g
▶️ [306/1000] Video ID: zmwDORj1-ME
▶️ [307/1000] Video ID: gyyUY9Yn_RY
▶️ [308/1000] Video ID: nuBgzjGJst4
▶️ [309/1000] Video ID: DWMmcf1wbJI
▶️ [310/1000] Video ID: uH1WvZl5lYw
▶️ [311/1000] Video ID: BC3y_VkjV68
▶️ [312/1000] Video ID: JQaPakX3Uv4
▶️ [313/1000] Video ID: q9tf4CC2CkI
▶️ [314/1000] Video ID: tID2Mg6J9mE
▶️ [315/1000] Video ID: 2HPhRZ28i_I
▶️ [316/1000] Video ID: VY4_BFARFAc
▶️ [317/1000] Video ID: c9DIL7pykLc
▶️ [318/1000] Video ID: _6S0u_jNX7w
▶️ [319/1000] Video ID: QIBwDAElCZs
▶️ [320/1000] Video ID: iO4aHiM3auw
▶️ [321/1000] Video ID: tN0Ju55dzgM
▶️ [322/1000] Video ID: LIbJ2BYZA8M
▶️ [323/1000] Video ID: IcXrAaHeUok
▶️ [324/1000] Video ID: QoXZ59S0uAg
▶️ [325/1000] Video ID: TzNe3h75ZEk
▶️ [326/1000] Video ID: qNBcV2d6H8U
▶️ [327/1000] Video ID: -arRlRqkMTk
▶️ [328/1000] Video ID: kUDWi0ShkWQ
▶️ [329/1000] Video ID: C58gdLRjens
▶️ [330/1000] Video ID: 7UB8T0YX3YA
▶️ [331/1000] Video ID: wTYwP7_HLbw
▶️ [332/1000] Video ID: QGeYZ7BhTXw
▶️ [333/1000] Video ID: NG_-BHXAm2E
▶️ [334/1000] Video ID: ifqkYAGNT-Q
▶️ [335/1000] Video ID: j8T03xjVS9I
▶️ [336/1000] Video ID: mf0Y_C6WSTk
▶️ [337/1000] Video ID: jAeXPHIUyLw
▶️ [338/1000] Video ID: AfvRaeOBa3I
▶️ [339/1000] Video ID: BbwXSy8bt1o
▶️ [340/1000] Video ID: maKGtISSaLA
▶️ [341/1000] Video ID: 0jiMXrj8zOA
▶️ [342/1000] Video ID: aN0LqRWlpLM
▶️ [343/1000] Video ID: 4jGe7i0YZVI
▶️ [344/1000] Video ID: KdHeJDEg1Sw
▶️ [345/1000] Video ID: KjvclrE9v3Y
▶️ [346/1000] Video ID: PmJZMaNkHaw
▶️ [347/1000] Video ID: mb5tV71zGfc
▶️ [348/1000] Video ID: 1OH3D74moA0
▶️ [349/1000] Video ID: -P5nxMmnsdc
▶️ [350/1000] Video ID: Zknp9kq__iA
▶️ [351/1000] Video ID: MsWumRqvCAs
▶️ [352/1000] Video ID: -TszDi4MKEU
▶️ [353/1000] Video ID: XU9S9ZXlEuE
▶️ [354/1000] Video ID: cH1lU0HmpuE
▶️ [355/1000] Video ID: yf1vC5Voqcw
▶️ [356/1000] Video ID: r6n9fhmtcwk
▶️ [357/1000] Video ID: Jjqwp99T34g
▶️ [358/1000] Video ID: w-yPG1FNGTw
▶️ [359/1000] Video ID: h8HWp6V_r-g
▶️ [360/1000] Video ID: yw1uK_p4Tbc
▶️ [361/1000] Video ID: C-U-mPYERnY
▶️ [362/1000] Video ID: 3vfTn41b5pU
▶️ [363/1000] Video ID: L8nDJ3bdR1A
▶️ [364/1000] Video ID: UjmAiSZLDYk
▶️ [365/1000] Video ID: n0gYUB2npRo
▶️ [366/1000] Video ID: WJ7q0VW_x50
▶️ [367/1000] Video ID: Tag-H7RZ7Rc
▶️ [368/1000] Video ID: wT3Qch9JOGo
▶️ [369/1000] Video ID: 86wfpLZqwTM
▶️ [370/1000] Video ID: A90vq2zzdQo
▶️ [371/1000] Video ID: GTIrCkLpP-o
▶️ [372/1000] Video ID: qttV8q2z4bc
▶️ [373/1000] Video ID: DMdZyjwy4x4
▶️ [374/1000] Video ID: 71RHjAiAwWE
▶️ [375/1000] Video ID: 7MnaSc1kok8
▶️ [376/1000] Video ID: 2PvLtCxfT40
▶️ [377/1000] Video ID: GLqkIX-sEMM
▶️ [378/1000] Video ID: WYQAZguJa-o
▶️ [379/1000] Video ID: 8JHCQAiC3Q4
▶️ [380/1000] Video ID: 7RDszn9Z4sM
▶️ [381/1000] Video ID: 4uaFvgB0hOA
▶️ [382/1000] Video ID: j8U3O7vsxYA
▶️ [383/1000] Video ID: EOUcdNhKH3k
▶️ [384/1000] Video ID: 8mvQJ1bQuMI
▶️ [385/1000] Video ID: 9rFxWfNr7ME
▶️ [386/1000] Video ID: SiX-i0CMkg0
▶️ [387/1000] Video ID: BYZFvBkUxjI
▶️ [388/1000] Video ID: jpSpdFGqE8E
▶️ [389/1000] Video ID: jpB9FSmfILk
▶️ [390/1000] Video ID: hdCCmhxnOm0
▶️ [391/1000] Video ID: MuncKsLZUBQ
▶️ [392/1000] Video ID: UvQxwerzqiY
▶️ [393/1000] Video ID: VhTXeIs_nOc
▶️ [394/1000] Video ID: 2ou9t8N71Zw
▶️ [395/1000] Video ID: lvwqb3pcjqs
▶️ [396/1000] Video ID: 3JaomTXH5gs
▶️ [397/1000] Video ID: lE82Riox82w
▶️ [398/1000] Video ID: x3wMaWsRovE
▶️ [399/1000] Video ID: aWBtpOnrFHk
▶️ [400/1000] Video ID: -yB4Jda5jio
▶️ [401/1000] Video ID: ngm_0ij2DTE
▶️ [402/1000] Video ID: RISiM7jGdJo
▶️ [403/1000] Video ID: 8Lzz5poQ3A0
▶️ [404/1000] Video ID: 1NWN-I7Ynyo
▶️ [405/1000] Video ID: aa36nNysyEU
▶️ [406/1000] Video ID: WEB4rG46LKI
▶️ [407/1000] Video ID: cbSO7X94Y8g
▶️ [408/1000] Video ID: LNZZgB0ocEA
▶️ [409/1000] Video ID: ULKWPFgnDS4
▶️ [410/1000] Video ID: cUY6t0vbRa4
▶️ [411/1000] Video ID: 9w3mbOWUhLA
▶️ [412/1000] Video ID: rb-Su7Tq1RM
▶️ [413/1000] Video ID: nEOgCfx8coo
▶️ [414/1000] Video ID: gl3qaPmgtZc
▶️ [415/1000] Video ID: 1KeCvWbA6_c
▶️ [416/1000] Video ID: Q0iBdnXNRcM
▶️ [417/1000] Video ID: MLwf0P2CsQY
▶️ [418/1000] Video ID: DT9GCa6Z3ZE
▶️ [419/1000] Video ID: _5rqJKo1j9Y
▶️ [420/1000] Video ID: ZuIsPIAN9N4
▶️ [421/1000] Video ID: 3Kz9evkyNtg
▶️ [422/1000] Video ID: EN-cDHj6WyE
▶️ [423/1000] Video ID: vnFGagC6anI
▶️ [424/1000] Video ID: aHQqvSMX8go
▶️ [425/1000] Video ID: LIhwzrea_Co
▶️ [426/1000] Video ID: xmn6vP8DPz8
▶️ [427/1000] Video ID: xVPaZLdC9JU
▶️ [428/1000] Video ID: dxJB8XZZ-r0
▶️ [429/1000] Video ID: fYFa9LWq7zo
▶️ [430/1000] Video ID: KgACHkcTW1Q
▶️ [431/1000] Video ID: 502CWuxrUDw
▶️ [432/1000] Video ID: wyCpKgbaBzQ
▶️ [433/1000] Video ID: nVHc0akQhL4
▶️ [434/1000] Video ID: tVwXU5tkKXs
▶️ [435/1000] Video ID: PzqfYe9mFu4
▶️ [436/1000] Video ID: JvzLKFLQ4KU
▶️ [437/1000] Video ID: yataIu6I0qA
▶️ [438/1000] Video ID: HxhEecOehtA
▶️ [439/1000] Video ID: 2R7Ftn-uG9M
▶️ [440/1000] Video ID: KEJudh8fQzg
▶️ [441/1000] Video ID: TxR3WOGVrsM
▶️ [442/1000] Video ID: qXRL52Sa_EQ
▶️ [443/1000] Video ID: RCekkzdrdNQ
▶️ [444/1000] Video ID: TrTQbXZePR0
▶️ [445/1000] Video ID: Ehdk6KmPgek
▶️ [446/1000] Video ID: l_r_VtAie4A
▶️ [447/1000] Video ID: uyPmIhWhNis
▶️ [448/1000] Video ID: Zz4V8v8_Lbk
▶️ [449/1000] Video ID: LhQHKr00xnk
▶️ [450/1000] Video ID: _nxp7uFb7wM
▶️ [451/1000] Video ID: GGX1HB8BYVI
▶️ [452/1000] Video ID: r-QPKrC8d3M
▶️ [453/1000] Video ID: qatb6LMlUC4
▶️ [454/1000] Video ID: dsxm51wPZ6E
▶️ [455/1000] Video ID: Ax7CfO8CpPI
▶️ [456/1000] Video ID: kuhdxRdXVpQ
▶️ [457/1000] Video ID: y_gZykHHZTM
▶️ [458/1000] Video ID: JVc2C2U5MdU
▶️ [459/1000] Video ID: Evar9pkGj68
▶️ [460/1000] Video ID: qHT9ZhKZDfI
▶️ [461/1000] Video ID: cSCdHvONj5s
▶️ [462/1000] Video ID: sYi5Alwj2HY
▶️ [463/1000] Video ID: 1dGUITsiryk
▶️ [464/1000] Video ID: YyJZbX3j20w
▶️ [465/1000] Video ID: 6id9K5XkHbg
▶️ [466/1000] Video ID: aw0Um_gjHqw
▶️ [467/1000] Video ID: TbE1zrGM0-4
▶️ [468/1000] Video ID: 6zHHkwriknI
▶️ [469/1000] Video ID: M6nAshjNeU4
▶️ [470/1000] Video ID: 0z8G6yCMo1U
▶️ [471/1000] Video ID: wbSBPyLWixg
▶️ [472/1000] Video ID: BtC2Ei28lUY
▶️ [473/1000] Video ID: kNfXNr0A_A0
▶️ [474/1000] Video ID: cg0Cymt9LV4
▶️ [475/1000] Video ID: qnZHTmZmUVI
▶️ [476/1000] Video ID: HQAYukYnmj0
▶️ [477/1000] Video ID: ALWQjuXhLYM
▶️ [478/1000] Video ID: ZEowjp8lyr4
▶️ [479/1000] Video ID: mWhCsamzfaQ
▶️ [480/1000] Video ID: loZq9ftE4Ls
▶️ [481/1000] Video ID: 60VirvPme_c
▶️ [482/1000] Video ID: BodbuRAOPdI
▶️ [483/1000] Video ID: ZTeXXHCNPDY
▶️ [484/1000] Video ID: sl5LTbzMts0
▶️ [485/1000] Video ID: f3aHmDCtu9w
▶️ [486/1000] Video ID: tp8JOBtrNJ0
▶️ [487/1000] Video ID: Z-XigRFTAfY
▶️ [488/1000] Video ID: o8IEKEiOM8o
▶️ [489/1000] Video ID: KVcZigvrpa0
▶️ [490/1000] Video ID: UwjdDH6gWHo
▶️ [491/1000] Video ID: eKILbruFZCo
▶️ [492/1000] Video ID: loP2wOW7TTE
▶️ [493/1000] Video ID: TwVJyU87EOA
▶️ [494/1000] Video ID: YgFxZPU1hCc
▶️ [495/1000] Video ID: tjWj2FnSa0Y
▶️ [496/1000] Video ID: 7BoQ-3ggFyg
▶️ [497/1000] Video ID: iMPOhAxSVk0
▶️ [498/1000] Video ID: 6Rw7lczgtsA
▶️ [499/1000] Video ID: RUfQhO_d4Nw
▶️ [500/1000] Video ID: t99Z1SEV75A
▶️ [501/1000] Video ID: 39HchU-Oxes
▶️ [502/1000] Video ID: 7CmmIMPX7hw
▶️ [503/1000] Video ID: 0otcwd0RBGk
▶️ [504/1000] Video ID: bqSnDqC9Gzk
▶️ [505/1000] Video ID: vYOZAUTA8rs
▶️ [506/1000] Video ID: DnvybzcmjnA
▶️ [507/1000] Video ID: pgEP0_RAC7I
▶️ [508/1000] Video ID: shDnLnHS4YQ
▶️ [509/1000] Video ID: w4Q4G850A2A
▶️ [510/1000] Video ID: KYOSpOB8fkU
▶️ [511/1000] Video ID: -dQnE4_DK1Y
▶️ [512/1000] Video ID: 6J9DvxIdXns
▶️ [513/1000] Video ID: InePQ-eCRgs
▶️ [514/1000] Video ID: bOnTPW2imXs
▶️ [515/1000] Video ID: awhoZxFYmzk
▶️ [516/1000] Video ID: EvGXoiyGH64
▶️ [517/1000] Video ID: mISY8rVWO5M
▶️ [518/1000] Video ID: LziQiCwaa44
▶️ [519/1000] Video ID: xx3dGO_xEIY
▶️ [520/1000] Video ID: nfqfSSCxqNo
▶️ [521/1000] Video ID: KUidRS6Dqnc
▶️ [522/1000] Video ID: NhWbHHPWV6s
▶️ [523/1000] Video ID: ETUsLJRG8f4
▶️ [524/1000] Video ID: N8hldFAJikk
▶️ [525/1000] Video ID: 4pZgbMsSk_o
▶️ [526/1000] Video ID: quJo9f3rbgw
▶️ [527/1000] Video ID: ChCSbw3cHJg
▶️ [528/1000] Video ID: QSrfngKclmA
▶️ [529/1000] Video ID: -CfJgTZYqa8
▶️ [530/1000] Video ID: MaJzZ4m7lk4
▶️ [531/1000] Video ID: xYmyFSvsoUY
▶️ [532/1000] Video ID: RcR4GiRuDH8
▶️ [533/1000] Video ID: 87c5iNN7pWE
▶️ [534/1000] Video ID: Fi95LSWP-UA
▶️ [535/1000] Video ID: KJZWr211ZCM
▶️ [536/1000] Video ID: CYzxD7RZx6s
▶️ [537/1000] Video ID: Es-_8dOwCO0

In [3]:
import pandas as pd
from transformers import pipeline
from tqdm.auto import tqdm # For a nice progress bar

# --- 1. SETUP ---

# Load video titles from your CSV
try:
    df = pd.read_csv("wolfsburg.csv")
    titles = df['Video Title'].drop_duplicates().tolist()
except FileNotFoundError:
    print("wolfsburg.csv not found. Using dummy data for demonstration.")
    # Create dummy data if the file doesn't exist
    titles = [
        "HIGHLIGHTS | VfL Wolfsburg vs. SC Freiburg | Men's Bundesliga",
        "Press Conference with Tommy Stroot | UWCL Final",
        "Ewa Pajor: All Goals of the Season 2022/23",
        "Training Session Before The Big Game",
        "VfL Wolfsburg Women vs. Arsenal WFC | All Goals | UWCL",
        "Top 5 Goals: Men's Team October",
        "Die Wölfinnen im Pokalfinale! | Highlights", # "The She-Wolves in the Cup Final"
        "Jonas Wind talks about his hat-trick",
        "Lena Oberdorf - Defensive Masterclass vs. Lyon",
        "Our U19 team is ready for the derby!",
        "Alexandra Popp's powerful header | Behind the Goal",
        "She-Wolves win DFB-Pokal Frauen!",
        "Highlights: Wolfsburg vs. Barcelona Femení",
        "DFB-Pokal der Männer: Wolfsburg kämpft sich weiter", # "Men's DFB-Pokal: Wolfsburg fights on"
        "Behind the Scenes: A day with the women's team",
        "Men's Team Arrives in Munich",
        "Warm-up Drills with the Squad"
    ]


# Initialize a more modern and powerful zero-shot pipeline
# CORRECTED MODEL: This is a top-tier model for NLI / zero-shot tasks.
classifier = pipeline(
    "zero-shot-classification",
    model="cross-encoder/nli-deberta-v3-large",
    device=-1 # Use device=0 for GPU, or device=-1 for CPU
)

candidate_labels = ["male football", "female football"]

# Define regex preclassifier (your function is already great)
def regex_gender(title):
    """Applies simple rules to classify gender based on keywords."""
    title = title.lower()
    # Keywords for female teams
    if any(keyword in title for keyword in ['femení', 'femenil', 'femenina', 'women', 'womens', 'wfc', 'ladies', 'she-wolves', 'wölfinnen']):
        return "female football"
    # Keywords for male teams
    elif any(keyword in title for keyword in ['men', 'mens', 'masculino', 'masculine']):
        return "male football"
    else:
        return None  # Unknown, let the model decide

# --- 2. HYBRID CLASSIFICATION (BATCH-OPTIMIZED) ---

print(f"Starting classification for {len(titles)} unique titles...")

results = []
titles_to_classify_with_model = []

# First pass: Apply the fast regex classifier
for title in titles:
    regex_label = regex_gender(title)
    if regex_label:
        results.append({
            "Video Title": title,
            "Predicted Gender": regex_label,
            "Method": "regex"
        })
    else:
        # If regex doesn't find a match, add it to the list for the model
        titles_to_classify_with_model.append(title)

# Second pass: Use the powerful zero-shot model on the remaining titles in one batch
if titles_to_classify_with_model:
    print(f"Regex classified {len(results)} titles. Using zero-shot model for the remaining {len(titles_to_classify_with_model)}...")
    # The pipeline can process a list of inputs much faster than a loop
    model_outputs = classifier(
        titles_to_classify_with_model,
        candidate_labels=candidate_labels,
        multi_label=False # We want only the single best label
    )

    # Use a tqdm progress bar to wrap the model outputs for better user experience
    for output in tqdm(model_outputs, desc="Processing Model Results"):
        results.append({
            "Video Title": output["sequence"],
            "Predicted Gender": output["labels"][0],
            "Method": "zero-shot"
        })
else:
    print("All titles were classified using the regex method.")

# --- 3. RESULTS and VALIDATION SAMPLING ---

# Convert final results to a DataFrame
result_df = pd.DataFrame(results)

print("\n--- Classification Complete. Here's a preview of the results: ---")
print(result_df.head())
print(f"\nBreakdown of classification methods:\n{result_df['Method'].value_counts()}")


# --- Sampling for Validation ---
print("\n" + "="*50)
print("             VALIDATION SAMPLES")
print("="*50 + "\n")

# Filter by predicted gender
male_classified = result_df[result_df['Predicted Gender'] == 'male football']
female_classified = result_df[result_df['Predicted Gender'] == 'female football']

# Function to safely sample and print
def print_samples(df, gender_label, num_samples=10):
    print(f"--- Random Examples Classified as '{gender_label}' ---")
    if len(df) == 0:
        print(f"No titles were classified as {gender_label}.")
        return

    # Take at most num_samples, or fewer if not enough are available
    sample_size = min(num_samples, len(df))
    # Use random_state for reproducible samples
    random_sample = df.sample(n=sample_size, random_state=42)

    for index, row in random_sample.iterrows():
        print(f"  - Title: '{row['Video Title']}' (Method: {row['Method']})")
    print("\n")


# Print the samples
print_samples(male_classified, 'male football')
print_samples(female_classified, 'female football')

WARNING:tensorflow:From c:\Users\Daniel\AppData\Local\Programs\Python\Python311\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Starting classification for 995 unique titles...
Regex classified 206 titles. Using zero-shot model for the remaining 789...

Processing Model Results:   0%|          | 0/789 [00:00<?, ?it/s]

--- Classification Complete. Here's a preview of the results: ---
                                         Video Title Predicted Gender Method
0  "Anstrengend, aber gut!" | Stimmen | Trainings...  female football  regex
1  RE-LIVE vom Spielfeldrand! 🟢⚪ Trainingsauftakt...  female football  regex
2  Die Wölfinnen auf dem Prüfstand! 💪😮‍💨 Leistung...  female football  regex
3  Bonjour Wölfinnen! 🇫🇷 Kessya Bussy im Intervie...  female football  regex
4                   Herzlich Willkommen, Coach 🇳🇱🤝🇩🇪    male football  regex

Breakdown of classification methods:
Method
zero-shot    789
regex        206
Name: count, dtype: int64

==================================================
             VALIDATION SAMPLES
==================================================

--- Random Examples Classified as 'male football' ---
  - Title: 'Janssen eröffnet Torfestival | Highlights | VfL Wolfsburg - 1. FC Köln 5:1' (Method: zero-shot)
  - Title: 'Eure Pfiffe sind Motivation für uns! 🔥 #vflwolfsburgmen' (Method: regex)
  - Title: 'Frage der Woche: Wer zahlt am meisten in die Mannschaftskasse? 💰' (Method: zero-shot)
  - Title: 'RE-LIVE | Pressekonferenz mit Hasenhüttl und Schuster nach VfL Wolfsburg - SC Freiburg | Bundesliga' (Method: zero-shot)
  - Title: 'Weil es so schön war… 💚🤍🐺 #vflwolfsburg' (Method: zero-shot)
  - Title: 'First training of Amoura 👍' (Method: zero-shot)
  - Title: '„Bin geteilter Gefühle“ | Stimmen | Eintracht Frankfurt - VfL Wolfsburg' (Method: regex)
  - Title: 'RE-LIVE |  VfL Wolfsburg vs. Como 1907  | Testspiel' (Method: zero-shot)
  - Title: 'Say salut to Mohamed Amoura 👋' (Method: zero-shot)
  - Title: 'This-or-That Eis-Edition 🍨' (Method: zero-shot)


--- Random Examples Classified as 'female football' ---
  - Title: 'Bienvenido, Judit Pujols 🇪🇸' (Method: zero-shot)
  - Title: 'TSG Hoffenheim 🆚 VfL Wolfsburg | Weekly Wolves 🐺 Wölfinnen - 24/25: Präsentiert von Linglong Tyres' (Method: regex)
  - Title: 'In den Farben vereint! 🟢⚪️ Der Trikotlaunch 2025/26 für Wölfinnen und Wölfe | VfL Wolfsburg' (Method: regex)
  - Title: 'Vorhang auf 🎥 #vflwolfsburg' (Method: zero-shot)
  - Title: 'Say hello to Ella 👋' (Method: zero-shot)
  - Title: 'Hinter den Kulissen - Unsere Wölfe im Pokalfight! 🏆💪 | DFB-Pokal-Viertelfinale gegen RB Leipzig' (Method: zero-shot)
  - Title: 'Janina Minge & Marina Hegering starten die "Olympia-Tabu-Challenge" 😂🥇' (Method: zero-shot)
  - Title: 'This-or-That National Nail Polish Day 💅 powered by Neonail' (Method: zero-shot)
  - Title: 'Tor-Show der Wölfe & Nmechas Joker-Comeback! | Highlights: VfL Wolfsburg 🆚 Borussia M'gladbach ⚽🔥' (Method: zero-shot)
  - Title: 'Auf geht’s! - Der Trainingsauftakt der Wölfe 24/25 💚⚽️' (Method: zero-shot)

# Arsenal

In [4]:
from googleapiclient.discovery import build
import time
import pandas as pd

# ✅ Arsenal's Official Channel ID
CHANNEL_ID = 'UCpryVRk_VDudG8SHXgWcG0w'

# 🔑 Replace with your valid YouTube Data API v3 key
API_KEY = 'AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ'
youtube = build('youtube', 'v3', developerKey=API_KEY)

def get_uploads_playlist_id(channel_id):
    res = youtube.channels().list(
        part='contentDetails',
        id=channel_id
    ).execute()
    if res['items']:
        return res['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    return None

def get_recent_video_ids(playlist_id, count):
    video_ids = []
    next_page_token = None

    while len(video_ids) < count:
        res = youtube.playlistItems().list(
            playlistId=playlist_id,
            part='contentDetails',
            maxResults=50,
            pageToken=next_page_token
        ).execute()

        for item in res['items']:
            video_ids.append(item['contentDetails']['videoId'])
            if len(video_ids) >= count:
                break

        next_page_token = res.get('nextPageToken')
        if not next_page_token:
            break

    return video_ids

def get_top_level_comments(video_id, max_comments=None):
    comments = []
    next_page_token = None

    while True:
        try:
            res = youtube.commentThreads().list(
                part='snippet',
                videoId=video_id,
                maxResults=100,
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in res['items']:
                snippet = item['snippet']['topLevelComment']['snippet']
                comments.append({
                    'Commenter Name': snippet['authorDisplayName'],
                    'Comment': snippet['textDisplay'],
                    'Comment Like Count': snippet['likeCount']
                })

                if max_comments and len(comments) >= max_comments:
                    return comments

            next_page_token = res.get('nextPageToken')
            if not next_page_token:
                break

        except Exception as e:
            print(f"Error fetching comments for video {video_id}: {e}")
            break

        time.sleep(0.5)

    return comments

def get_video_metadata(video_id):
    res = youtube.videos().list(
        part='snippet,statistics',
        id=video_id
    ).execute()

    if not res['items']:
        return None

    item = res['items'][0]
    return {
        'Video ID': video_id,
        'Video Title': item['snippet']['title'],
        'View Count': item['statistics'].get('viewCount'),
        'Like Count': item['statistics'].get('likeCount'),
        'Comment Count': item['statistics'].get('commentCount'),
        'YouTube Channel': item['snippet']['channelTitle']
    }

def collect_all_comments_from_channel_id(channel_id, num_videos, output_filename):
    playlist_id = get_uploads_playlist_id(channel_id)
    if not playlist_id:
        print(f"❌ Could not get uploads playlist for channel: {channel_id}")
        return

    video_ids = get_recent_video_ids(playlist_id, num_videos)
    print(f"📺 Processing {len(video_ids)} videos from channel ID: {channel_id}")

    all_comments = []

    for i, vid in enumerate(video_ids, 1):
        print(f"▶️ [{i}/{len(video_ids)}] Video ID: {vid}")
        video_meta = get_video_metadata(vid)
        if not video_meta:
            continue

        comments = get_top_level_comments(vid)
        for c in comments:
            all_comments.append({
                'Video Title': video_meta['Video Title'],
                'Like Count': video_meta['Like Count'],
                'View Count': video_meta['View Count'],
                'Comment Count': video_meta['Comment Count'],
                'Commenter Name': c['Commenter Name'],
                'Comment': c['Comment'],
                'Comment Like Count': c['Comment Like Count'],
                'YouTube Channel': video_meta['YouTube Channel']
            })

        time.sleep(1)  # polite pause

    df = pd.DataFrame(all_comments)
    df.to_csv(output_filename, index=False, encoding='utf-8-sig')
    print(f"💾 Saved {len(all_comments)} comments to: {output_filename}")

# ✅ Run the script
if __name__ == '__main__':
    collect_all_comments_from_channel_id(
        channel_id=CHANNEL_ID,
        num_videos=1000,
        output_filename="arsenal.csv"
    )

📺 Processing 1000 videos from channel ID: UCpryVRk_VDudG8SHXgWcG0w
▶️ [1/1000] Video ID: 2juNkFErgnw
▶️ [2/1000] Video ID: snnBhI2OcgY
▶️ [3/1000] Video ID: q0bDaCxtev8
▶️ [4/1000] Video ID: PdUExg1d3tI
▶️ [5/1000] Video ID: 6A7EQ0PACmY
▶️ [6/1000] Video ID: m-iBHTuqQzA
▶️ [7/1000] Video ID: Ccr8BEmQ0O0
▶️ [8/1000] Video ID: oL4FUo4VbgI
▶️ [9/1000] Video ID: tbyaZM4gBew
▶️ [10/1000] Video ID: _ZqkdoG45Zo
▶️ [11/1000] Video ID: ZEYaN5suqi4
▶️ [12/1000] Video ID: Ol_3zVvb6q4
▶️ [13/1000] Video ID: Fi4_h658ElI
▶️ [14/1000] Video ID: lMPXajOxIsk
▶️ [15/1000] Video ID: 7MQBjH1xPoE
▶️ [16/1000] Video ID: cLmIGTK26_4
▶️ [17/1000] Video ID: cyFLfMnGhBU
▶️ [18/1000] Video ID: GqhIvUNexRI
▶️ [19/1000] Video ID: QRqVPXLvjvs
▶️ [20/1000] Video ID: xk1-NHWb-G8
▶️ [21/1000] Video ID: 5wOc3tEYEoM
▶️ [22/1000] Video ID: 6Z3aGfslAUY
▶️ [23/1000] Video ID: l4uV6K99vIM
▶️ [24/1000] Video ID: by129ggkHjs
▶️ [25/1000] Video ID: js1870ZMbbs
▶️ [26/1000] Video ID: 5gHE6aarGMY
▶️ [27/1000] Video ID: -e44R-PrJJs
▶️ [28/1000] Video ID: BsywPZmFycM
▶️ [29/1000] Video ID: 1W0-nvLTJWc
▶️ [30/1000] Video ID: -OvByZl9JUM
▶️ [31/1000] Video ID: 7zyXLiWMDWM
▶️ [32/1000] Video ID: LOFS2aOkaro
▶️ [33/1000] Video ID: Aw0U-6865cw
▶️ [34/1000] Video ID: OUFtaxPWzSA
▶️ [35/1000] Video ID: z3_6B2TTVls
▶️ [36/1000] Video ID: KqXuiKrrIac
▶️ [37/1000] Video ID: uf2F3OgdspM
▶️ [38/1000] Video ID: AXL8Q2pjBck
▶️ [39/1000] Video ID: XVaL-hcKUgA
▶️ [40/1000] Video ID: Mbd8KyHDtyU
▶️ [41/1000] Video ID: cbWhdCtZSYU
▶️ [42/1000] Video ID: UB86g2c8ftA
▶️ [43/1000] Video ID: zM2mSTQ8PYM
▶️ [44/1000] Video ID: JLlpgGMmS7k
▶️ [45/1000] Video ID: dVwsiUX9K8A
▶️ [46/1000] Video ID: E92LT6kEsXs
▶️ [47/1000] Video ID: 5wEqPaq0ka0
▶️ [48/1000] Video ID: EajpN4TGEn0
▶️ [49/1000] Video ID: 5cvzaE220Lg
▶️ [50/1000] Video ID: KKr-h70V4N8
▶️ [51/1000] Video ID: cLj-XwPboj8
▶️ [52/1000] Video ID: GrL-c6b75zE
▶️ [53/1000] Video ID: qxmjnIG77Pk
▶️ [54/1000] Video ID: fTbMIY-yqoo
▶️ [55/1000] Video ID: g9eU0WF3xKw
▶️ [56/1000] Video ID: 7liw-2airPs
▶️ [57/1000] Video ID: EXev8Dds5vQ
▶️ [58/1000] Video ID: WTGjNrx625I
▶️ [59/1000] Video ID: 0FL3OcbedPM
▶️ [60/1000] Video ID: SKPFTivt31E
▶️ [61/1000] Video ID: f3GSarHOOAA
▶️ [62/1000] Video ID: BHXcUIbz8XE
▶️ [63/1000] Video ID: hbYsd1n5WrI
▶️ [64/1000] Video ID: zsEikSm3tWo
▶️ [65/1000] Video ID: Qc_T9_4JOMo
▶️ [66/1000] Video ID: mcU35xAyOpI
▶️ [67/1000] Video ID: wj5_EHCsHcQ
▶️ [68/1000] Video ID: UbJtfuPuDi0
▶️ [69/1000] Video ID: gNKWJE_VgT4
▶️ [70/1000] Video ID: 6XuOxd0kesk
▶️ [71/1000] Video ID: 9YF-pYGzjnc
▶️ [72/1000] Video ID: _6X8LDDwb7A
▶️ [73/1000] Video ID: yeMc05pkp8c
▶️ [74/1000] Video ID: 8a2l6xr0KlI
▶️ [75/1000] Video ID: _urmdn2baxA
▶️ [76/1000] Video ID: rBtZVezYdqQ
▶️ [77/1000] Video ID: INyVIzuBF-0
▶️ [78/1000] Video ID: I2s04Jmwo78
▶️ [79/1000] Video ID: pYaSTE2WyEE
▶️ [80/1000] Video ID: kFcjvMWNjgI
▶️ [81/1000] Video ID: Z5hVkv27-8U
▶️ [82/1000] Video ID: LoIpclknEFU
▶️ [83/1000] Video ID: B6iHkbGQQTg
▶️ [84/1000] Video ID: AhbgH0Kh1lo
▶️ [85/1000] Video ID: AAW6QrdiKFs
▶️ [86/1000] Video ID: qPRbQtCJTmw
▶️ [87/1000] Video ID: ReuwJterH5I
▶️ [88/1000] Video ID: 7RDBckKANsE
▶️ [89/1000] Video ID: lZSYpVNQKg8
▶️ [90/1000] Video ID: UMnu9HITKaI
▶️ [91/1000] Video ID: Mp_L9iMl_0E
▶️ [92/1000] Video ID: jR9v98qPCNI
▶️ [93/1000] Video ID: QTZLEGDSmSE
▶️ [94/1000] Video ID: Ouz_5FL5gVk
▶️ [95/1000] Video ID: ZtZ7UD-HTKA
▶️ [96/1000] Video ID: CbCL3Aeo-J0
▶️ [97/1000] Video ID: _OBUio83dP4
▶️ [98/1000] Video ID: yQaEK18R9qs
▶️ [99/1000] Video ID: vPTRR8WPuug
▶️ [100/1000] Video ID: EBe3A9KTs0E
▶️ [101/1000] Video ID: a6Tz_YIgYJs
▶️ [102/1000] Video ID: oRHKXMjihpE
▶️ [103/1000] Video ID: zI0KA7JZfBY
▶️ [104/1000] Video ID: wIi7WTMWTDQ
▶️ [105/1000] Video ID: iLeNvcdwJRo
▶️ [106/1000] Video ID: FpAkOLyu5Us
▶️ [107/1000] Video ID: 0XUdFK722ws
▶️ [108/1000] Video ID: UfkwP0Skoiw
▶️ [109/1000] Video ID: MNOFWZCfDU8
▶️ [110/1000] Video ID: 9PewK_e-8QQ
▶️ [111/1000] Video ID: 9MeJZv-YA7k
▶️ [112/1000] Video ID: 2-nsVIbBLN8
▶️ [113/1000] Video ID: wSadpzdiqUE
▶️ [114/1000] Video ID: xtGOcFUZPy0
▶️ [115/1000] Video ID: Rxe0-TnESDs
▶️ [116/1000] Video ID: X429XSQLS_s
▶️ [117/1000] Video ID: fH1QuxrUbZk
▶️ [118/1000] Video ID: aX3jXBV7fEA
▶️ [119/1000] Video ID: rmdrXg1aBWk
▶️ [120/1000] Video ID: W2pMHZiwJrs
▶️ [121/1000] Video ID: biKtadmiWU0
▶️ [122/1000] Video ID: St-L7DH81Zg
▶️ [123/1000] Video ID: kDwGXIUD5CA
▶️ [124/1000] Video ID: 5Bo9Vuo_3wQ
▶️ [125/1000] Video ID: IfHP0ReKncY
▶️ [126/1000] Video ID: T37nSj0r2qU
▶️ [127/1000] Video ID: Nxhk2MooPq4
▶️ [128/1000] Video ID: Y-Mq1GzUptI
▶️ [129/1000] Video ID: yrK_pzdpNkA
▶️ [130/1000] Video ID: y6UXhNewgfg
▶️ [131/1000] Video ID: 5LE5kNnwVxQ
▶️ [132/1000] Video ID: iEt7IQBrrOQ
▶️ [133/1000] Video ID: V8PAv2dg_CI
▶️ [134/1000] Video ID: q9RH3MZSIEA
▶️ [135/1000] Video ID: M3QrSJyNGs8
▶️ [136/1000] Video ID: mVN6kjzbGJA
▶️ [137/1000] Video ID: CBAeJk1pKaU
▶️ [138/1000] Video ID: 4_B6q4Opk3Q
▶️ [139/1000] Video ID: 65bDOVe7DHI
▶️ [140/1000] Video ID: QxGns2R6JmM
▶️ [141/1000] Video ID: PnNHIf0lG5A
▶️ [142/1000] Video ID: 9eanGDoC25I
▶️ [143/1000] Video ID: pjgbGpIBDh8
▶️ [144/1000] Video ID: ztOa-NWqCZQ
▶️ [145/1000] Video ID: 7vCPQ2S7UvM
▶️ [146/1000] Video ID: NJSFrlIiFMA
▶️ [147/1000] Video ID: Bl22RATqjE4
▶️ [148/1000] Video ID: pTmeHDCqBlI
▶️ [149/1000] Video ID: XjQWyIE1s2M
▶️ [150/1000] Video ID: gSBvGL4rGEM
▶️ [151/1000] Video ID: xOFbKWMHJrY
▶️ [152/1000] Video ID: KAXE14sNabk
▶️ [153/1000] Video ID: rJkThzu0a0c
▶️ [154/1000] Video ID: yJTJyPOoYc4
▶️ [155/1000] Video ID: fpfBaVoyhBE
▶️ [156/1000] Video ID: Y_qUX8L7WWw
▶️ [157/1000] Video ID: ea--QYcVvEI
▶️ [158/1000] Video ID: KuO0rDyBc9k
▶️ [159/1000] Video ID: ceWoCVXltJg
▶️ [160/1000] Video ID: cJ-bvhVpciQ
▶️ [161/1000] Video ID: 9oNwce0KkzY
▶️ [162/1000] Video ID: j3UTGqnoMTM
▶️ [163/1000] Video ID: SooIgeMjJQI
▶️ [164/1000] Video ID: n7XP8XzDibE
▶️ [165/1000] Video ID: kU8_XjPd8XM
▶️ [166/1000] Video ID: UTukwySjKpY
▶️ [167/1000] Video ID: Jg8Q246hWYc
▶️ [168/1000] Video ID: ZzoMYbIq4nI
▶️ [169/1000] Video ID: zO_VIrQG68s
▶️ [170/1000] Video ID: LmTW79Pc5Ec
▶️ [171/1000] Video ID: FP5mc-LiKg0
▶️ [172/1000] Video ID: 9lTKjnqQL04
▶️ [173/1000] Video ID: WSA9fy80lcM
▶️ [174/1000] Video ID: Lukb_8gtnLA
▶️ [175/1000] Video ID: dgVxA8SyLiI
▶️ [176/1000] Video ID: jwBfi15JBTE
▶️ [177/1000] Video ID: 2W9l1HbEj9Y
▶️ [178/1000] Video ID: bpuO9OnYlek
▶️ [179/1000] Video ID: WYjUs_ULjaM
▶️ [180/1000] Video ID: 2uB5i9d5-N0
▶️ [181/1000] Video ID: Bi3G1lC51Po
▶️ [182/1000] Video ID: RGm6BqmlAkI
▶️ [183/1000] Video ID: wO536uwgyA0
▶️ [184/1000] Video ID: OWVI6TPeCc4
▶️ [185/1000] Video ID: i7qZ7jTJkxs
▶️ [186/1000] Video ID: DCRu81I0Hsw
▶️ [187/1000] Video ID: XHJuS1TXOio
▶️ [188/1000] Video ID: 3DVVm04ez9Q
▶️ [189/1000] Video ID: Cy3g1FSur4k
▶️ [190/1000] Video ID: rhntNze7LBs
▶️ [191/1000] Video ID: 2ta76tIaOKM
▶️ [192/1000] Video ID: ej_-oKDUPGc
▶️ [193/1000] Video ID: DgK-vPBVkyQ
▶️ [194/1000] Video ID: r5_sAiUMVeQ
▶️ [195/1000] Video ID: bghClZpEgKI
▶️ [196/1000] Video ID: 0hYFK3aKtkM
▶️ [197/1000] Video ID: 3fyuvqyssoQ
▶️ [198/1000] Video ID: XzJEIUX84as
▶️ [199/1000] Video ID: zRqifgwQ3QE
▶️ [200/1000] Video ID: zokGmOuVpBU
▶️ [201/1000] Video ID: 6K4fg6FaQeM
▶️ [202/1000] Video ID: C3lVhmmR1Pw
▶️ [203/1000] Video ID: aH2I3_8q6ok
▶️ [204/1000] Video ID: PP-JzyIL2JA
▶️ [205/1000] Video ID: ShIIcCa-Fxw
▶️ [206/1000] Video ID: eD-kcDXNbc4
▶️ [207/1000] Video ID: qH9qOPqBxQs
▶️ [208/1000] Video ID: HiH1TGpAoZ4
▶️ [209/1000] Video ID: cBJsI4siFs8
▶️ [210/1000] Video ID: zIOYrGqNdO0
▶️ [211/1000] Video ID: Rg3elhgWwsQ
▶️ [212/1000] Video ID: vi0gBrGkojI
▶️ [213/1000] Video ID: L0gyCveMFmk
▶️ [214/1000] Video ID: JlhesxBXmss
▶️ [215/1000] Video ID: GYm3OKh_Lv8
▶️ [216/1000] Video ID: b98guhuNIuI
▶️ [217/1000] Video ID: rZKOrIiw_rg
▶️ [218/1000] Video ID: oAWFyNKY6gA
▶️ [219/1000] Video ID: SwkF8gL_LIM
▶️ [220/1000] Video ID: RI4mqr5Kp9Y
▶️ [221/1000] Video ID: Cgu8fMbQhs4
▶️ [222/1000] Video ID: wfgVh_oG2GE
▶️ [223/1000] Video ID: 3BUGyUQROPU
▶️ [224/1000] Video ID: 7pkx8oCqZ7E
▶️ [225/1000] Video ID: r1LP9jZXvaU
▶️ [226/1000] Video ID: VVS3dQ0wUEU
▶️ [227/1000] Video ID: Wcrfjq74ejI
▶️ [228/1000] Video ID: 94dla3JFdtM
▶️ [229/1000] Video ID: fX-A_JyDO5c
▶️ [230/1000] Video ID: uAR1kCOv1w8
▶️ [231/1000] Video ID: OMQ8vDaT7y0
▶️ [232/1000] Video ID: rQRDfGWCkSo
▶️ [233/1000] Video ID: RBw1d7UHHzg
▶️ [234/1000] Video ID: NCV-_w_7g9I
▶️ [235/1000] Video ID: 7yUkVUlpeGc
▶️ [236/1000] Video ID: heaLzXwmqMU
▶️ [237/1000] Video ID: aV0y3rYZbK4
▶️ [238/1000] Video ID: nLoeuENz4WY
▶️ [239/1000] Video ID: FDcoOjwmPaw
▶️ [240/1000] Video ID: noWE_q23BI0
▶️ [241/1000] Video ID: pbrhU7-PCQI
▶️ [242/1000] Video ID: LI3eKGe89UM
▶️ [243/1000] Video ID: geKKujG_LZ0
▶️ [244/1000] Video ID: rXbh4lJKKdw
▶️ [245/1000] Video ID: nTv67R4SzpU
▶️ [246/1000] Video ID: alDO-sGItuo
▶️ [247/1000] Video ID: 3_zrJ-t0tWw
▶️ [248/1000] Video ID: cbPizBCGy7Y
▶️ [249/1000] Video ID: RiIc_Rgep4s
▶️ [250/1000] Video ID: 3JMQ11ApuEk
▶️ [251/1000] Video ID: aJ7nloP-bbw
▶️ [252/1000] Video ID: f3yK3hdEYlw
▶️ [253/1000] Video ID: b1w3v27rEh0
▶️ [254/1000] Video ID: fRks-x_0CD4
▶️ [255/1000] Video ID: YmcQyk5Gk3E
▶️ [256/1000] Video ID: kqYmIS18XHY
▶️ [257/1000] Video ID: eojcy1is1Qg
▶️ [258/1000] Video ID: RWmWkM7gjJc
▶️ [259/1000] Video ID: Wl-vzvGehZs
▶️ [260/1000] Video ID: UV18cu-y1Is
▶️ [261/1000] Video ID: GbIRv74ZYqo
▶️ [262/1000] Video ID: WOkm_MPi27k
▶️ [263/1000] Video ID: SumXgSH17Lo
▶️ [264/1000] Video ID: _-7-0MExy7k
▶️ [265/1000] Video ID: NUxCqavig38
▶️ [266/1000] Video ID: QAN8KLQBzvM
▶️ [267/1000] Video ID: aYIKWOoA3mM
▶️ [268/1000] Video ID: jhkHCQyXCOU
▶️ [269/1000] Video ID: JxVKzdn8FCo
▶️ [270/1000] Video ID: z46LdFXpREE
▶️ [271/1000] Video ID: e9T8ya7HY74
▶️ [272/1000] Video ID: ZNLfzZ7MPis
▶️ [273/1000] Video ID: TxbU3AEzu3I
▶️ [274/1000] Video ID: hPxgE93LwLc
▶️ [275/1000] Video ID: ILpTS1b6vqw
▶️ [276/1000] Video ID: pMOFk45GDFI
▶️ [277/1000] Video ID: oRilqHQt1j4
▶️ [278/1000] Video ID: CvcPIznHIJE
▶️ [279/1000] Video ID: eQweUjgxaWU
▶️ [280/1000] Video ID: UkGG_WqB_7c
▶️ [281/1000] Video ID: qxGOD78w6r8
▶️ [282/1000] Video ID: ECw4oc5diys
▶️ [283/1000] Video ID: xcgti2vkUho
▶️ [284/1000] Video ID: ROAiDiUGAEg
▶️ [285/1000] Video ID: _gJviGw_xb0
▶️ [286/1000] Video ID: OeT6EEvFCs4
▶️ [287/1000] Video ID: JmYVL5l7wgE
▶️ [288/1000] Video ID: IH692BWvQog
▶️ [289/1000] Video ID: wxo-yXP2rP0
▶️ [290/1000] Video ID: tojXI1GVNr8
▶️ [291/1000] Video ID: 6SNhPu2p73A
▶️ [292/1000] Video ID: crfWfHCLY-I
▶️ [293/1000] Video ID: K5zFoV4_mXY
▶️ [294/1000] Video ID: orx1K7uTOrE
▶️ [295/1000] Video ID: oyW0FspE0Uk
▶️ [296/1000] Video ID: UikQXOmdP90
▶️ [297/1000] Video ID: eOiKxq-27Uk
▶️ [298/1000] Video ID: UBLisI7I1I4
▶️ [299/1000] Video ID: 3XsfRwzqHow
▶️ [300/1000] Video ID: v06QulfQF5A
▶️ [301/1000] Video ID: 62lNIADscHo
▶️ [302/1000] Video ID: A7xApUpmgsY
▶️ [303/1000] Video ID: CRbajfRvt0A
▶️ [304/1000] Video ID: o5Kcc8R9n_4
▶️ [305/1000] Video ID: fVXyRHI-t0c
▶️ [306/1000] Video ID: K_VzD7NMj_o
▶️ [307/1000] Video ID: MEwhYn7x1_I
▶️ [308/1000] Video ID: FauQfSAVMMw
▶️ [309/1000] Video ID: qlHMzPQe7E8
▶️ [310/1000] Video ID: Zzj0BkzgsSQ
▶️ [311/1000] Video ID: JXJE0bQFQLI
▶️ [312/1000] Video ID: aXvI858XPf8
▶️ [313/1000] Video ID: TTcWT1rSMwA
▶️ [314/1000] Video ID: CQpMuy5t7m8
▶️ [315/1000] Video ID: zkEqVPAjOLY
▶️ [316/1000] Video ID: WljL1P7u0nY
▶️ [317/1000] Video ID: 133_rffdOHU
▶️ [318/1000] Video ID: uHxr2rvW5g8
▶️ [319/1000] Video ID: cysX5hiaogY
▶️ [320/1000] Video ID: cRwJm4r6BBE
▶️ [321/1000] Video ID: VvQ4kbdCeb4
▶️ [322/1000] Video ID: XZWztB-qS0c
▶️ [323/1000] Video ID: v4GyiynvByc
▶️ [324/1000] Video ID: lodWArMewIE
▶️ [325/1000] Video ID: 4pJWzz3viHg
▶️ [326/1000] Video ID: Trr_Z5ppVMA
▶️ [327/1000] Video ID: GjH4MVud_Jw
▶️ [328/1000] Video ID: 5zMM6Hf8Nt4
▶️ [329/1000] Video ID: R3RsCafnUVk
▶️ [330/1000] Video ID: pBA_zURMRl0
▶️ [331/1000] Video ID: I0Zx_6VZ-EE
▶️ [332/1000] Video ID: 1JUZMHKdz38
▶️ [333/1000] Video ID: r7-ETJ9qyEQ
▶️ [334/1000] Video ID: 6YA1GWAoK3o
▶️ [335/1000] Video ID: -GssdUULn6A
▶️ [336/1000] Video ID: kGkHoPFAi2k
▶️ [337/1000] Video ID: VCDd7KpEiag
▶️ [338/1000] Video ID: 4duQU5ZNSrY
▶️ [339/1000] Video ID: DKI3g1ic1Oo
▶️ [340/1000] Video ID: d7GYqZrAweQ
▶️ [341/1000] Video ID: NdAQBPgkvdY
▶️ [342/1000] Video ID: 0Kz5jEahnTI
▶️ [343/1000] Video ID: 5N1G8fJREsE
▶️ [344/1000] Video ID: 90yN7LA3bKY
▶️ [345/1000] Video ID: Nrp_SAwHsTE
▶️ [346/1000] Video ID: jp3-xSds3WI
▶️ [347/1000] Video ID: DxY-M9jNc08
▶️ [348/1000] Video ID: mgj5EaBykKQ
▶️ [349/1000] Video ID: _38iolVhDTQ
▶️ [350/1000] Video ID: 8f_SdL_jMuo
▶️ [351/1000] Video ID: 1u1jCmdGsJw
▶️ [352/1000] Video ID: cou23cawmR0
▶️ [353/1000] Video ID: p3PxK8K_RF8
▶️ [354/1000] Video ID: oZkc41gioZc
▶️ [355/1000] Video ID: F5CKgXY60Qo
▶️ [356/1000] Video ID: LsySjeF1rXM
▶️ [357/1000] Video ID: a3hzGtJZoeM
▶️ [358/1000] Video ID: lHBldixHuwk
▶️ [359/1000] Video ID: aOY3dCo5WQY
▶️ [360/1000] Video ID: LpUutTtEmNE
▶️ [361/1000] Video ID: _i1m4ayHW_4
▶️ [362/1000] Video ID: FZsQcn0Feso
▶️ [363/1000] Video ID: pdf-4-jagXk
▶️ [364/1000] Video ID: TD8GygVVTpA
▶️ [365/1000] Video ID: elh8v7h1zeo
▶️ [366/1000] Video ID: 1i_wP4dqG0s
▶️ [367/1000] Video ID: dQUSgiRYH38
▶️ [368/1000] Video ID: bHa3ZH4HdEI
▶️ [369/1000] Video ID: WpXgXFex1Rk
▶️ [370/1000] Video ID: 4xXbaIYwgzs
▶️ [371/1000] Video ID: Cpdkp9T1FWo
▶️ [372/1000] Video ID: pxgmajBBuP4
▶️ [373/1000] Video ID: 26JeuiZcO2Q
▶️ [374/1000] Video ID: EIKgz288Q-M
▶️ [375/1000] Video ID: pG14G6hZNsg
▶️ [376/1000] Video ID: zTaWU9BrLuQ
▶️ [377/1000] Video ID: f3POqcfPJZ8
▶️ [378/1000] Video ID: cVbpwAKYG-8
▶️ [379/1000] Video ID: 0Kr4LGSMVdg
▶️ [380/1000] Video ID: 4gSLH1PQgxM
▶️ [381/1000] Video ID: 0zKo54vRjGQ
▶️ [382/1000] Video ID: QI_LLpqE01E
▶️ [383/1000] Video ID: QsK68DG_Q-w
▶️ [384/1000] Video ID: tmSS8Tk7hmY
▶️ [385/1000] Video ID: WlncPHUm_vQ
▶️ [386/1000] Video ID: n1WtX0ZgRE4
▶️ [387/1000] Video ID: M3aEe6f_JbI
▶️ [388/1000] Video ID: Jytz5ItGd8E
▶️ [389/1000] Video ID: xjDL5wBQyXM
▶️ [390/1000] Video ID: i7hUdXdEGZ0
▶️ [391/1000] Video ID: vs8dkNmSJB8
▶️ [392/1000] Video ID: JCuLwct1940
▶️ [393/1000] Video ID: sPVd0q34WGA
▶️ [394/1000] Video ID: AUwxNH1F6Zw
▶️ [395/1000] Video ID: ilECz-7hMp4
▶️ [396/1000] Video ID: n-u-K17S7Gg
▶️ [397/1000] Video ID: m-5gFtAmQrc
▶️ [398/1000] Video ID: ZNm4rpjDRv4
▶️ [399/1000] Video ID: iBP3_NHXoBQ
▶️ [400/1000] Video ID: kNArQ9A4KVk
▶️ [401/1000] Video ID: sGh5gjkgHyI
▶️ [402/1000] Video ID: 5DWWSXwiMNs
▶️ [403/1000] Video ID: yVqxCdcbJQY
▶️ [404/1000] Video ID: RDHEcE8k2uE
▶️ [405/1000] Video ID: 3C0wBjYhqLE
▶️ [406/1000] Video ID: wnycjkTWAXQ
▶️ [407/1000] Video ID: Aa9Not8KlvQ
▶️ [408/1000] Video ID: tSl5NohOPkA
▶️ [409/1000] Video ID: niHrtZfcsbs
▶️ [410/1000] Video ID: ulOGDHfFZa4
▶️ [411/1000] Video ID: HUBQ9rFeDCc
▶️ [412/1000] Video ID: b5RekvcKSs0
▶️ [413/1000] Video ID: t2YPkuYcfdw
▶️ [414/1000] Video ID: 25nbf-dzopI
▶️ [415/1000] Video ID: T-SG3stkAKM
▶️ [416/1000] Video ID: iuD2QLuKgB8
▶️ [417/1000] Video ID: HZX9s5hideA
▶️ [418/1000] Video ID: LVcL_8sWlwg
▶️ [419/1000] Video ID: cM-zYWikgZA
▶️ [420/1000] Video ID: hx7k7PLV5_0
▶️ [421/1000] Video ID: COA3pyzdCyU
▶️ [422/1000] Video ID: jv1tunXAJi8
▶️ [423/1000] Video ID: sb6lQsToEj4
▶️ [424/1000] Video ID: 3BIOPTHKFSc
▶️ [425/1000] Video ID: eHleyiFFkNs
▶️ [426/1000] Video ID: sJvYmkBp5FE
▶️ [427/1000] Video ID: k0FEnbBaTeA
▶️ [428/1000] Video ID: i_qKVGnagiM
▶️ [429/1000] Video ID: IJM8LlfUpNA
▶️ [430/1000] Video ID: hUadqneDutw
▶️ [431/1000] Video ID: YId-4wYhWmk
▶️ [432/1000] Video ID: x-b7PqGf40M
▶️ [433/1000] Video ID: R1-9d5HwILo
▶️ [434/1000] Video ID: ALyCeRLYtNE
▶️ [435/1000] Video ID: R-tGHRVSy90
▶️ [436/1000] Video ID: whYUKd9mS5c
▶️ [437/1000] Video ID: xL6jmnWT1qg
▶️ [438/1000] Video ID: T93ymkbGbmM
▶️ [439/1000] Video ID: 8-8aMtkj224
▶️ [440/1000] Video ID: 0QqDOts0r3U
▶️ [441/1000] Video ID: iqirthUy8kI
▶️ [442/1000] Video ID: fr55N1G_fzY
▶️ [443/1000] Video ID: nsr7ZGQfpQQ
▶️ [444/1000] Video ID: 81FSgv2hfns
▶️ [445/1000] Video ID: jeDUJpDdTTs
▶️ [446/1000] Video ID: LIAsvxN7qAk
▶️ [447/1000] Video ID: z_z0rHpzXGU
▶️ [448/1000] Video ID: qxl6VkzOpng
▶️ [449/1000] Video ID: 1u__4uRBa98
▶️ [450/1000] Video ID: JCi5fj_7B6E
▶️ [451/1000] Video ID: VTwDKPUO1IU
▶️ [452/1000] Video ID: lvZrtov0lCI
▶️ [453/1000] Video ID: 2E1nBN8MwDU
▶️ [454/1000] Video ID: iZpY73shv9w
▶️ [455/1000] Video ID: hNka7uUc7Iw
▶️ [456/1000] Video ID: _DnYc4WaBa4
▶️ [457/1000] Video ID: BaP93VFfVXM
▶️ [458/1000] Video ID: 5r4JPB9Bp4Q
▶️ [459/1000] Video ID: nZelMXbuk7g
▶️ [460/1000] Video ID: yTTdH1ybU88
▶️ [461/1000] Video ID: snpifznz5cQ
▶️ [462/1000] Video ID: zwD24gJ2yBY
▶️ [463/1000] Video ID: L5J571_DOfQ
▶️ [464/1000] Video ID: 2SmrsLjR5ek
▶️ [465/1000] Video ID: Gnx_T7tFB58
▶️ [466/1000] Video ID: jzKYJp5gWdA
▶️ [467/1000] Video ID: nGC05AfKHtQ
▶️ [468/1000] Video ID: -2bmkMJgVXA
▶️ [469/1000] Video ID: _l3yFYR0O0g
▶️ [470/1000] Video ID: 1jFTKb6ijJE
▶️ [471/1000] Video ID: uU4GQ7OAUxs
▶️ [472/1000] Video ID: W98QbxYN0XI
▶️ [473/1000] Video ID: PC34F4th3hk
▶️ [474/1000] Video ID: HwAXiexoaEA
▶️ [475/1000] Video ID: KdWJeejiMaw
▶️ [476/1000] Video ID: K4OcuQbR5G4
▶️ [477/1000] Video ID: 4kvyfdg5LUg
▶️ [478/1000] Video ID: tiRY_DyrYd0
▶️ [479/1000] Video ID: gfliy6uyMn0
▶️ [480/1000] Video ID: XLvJZTGnpMQ
▶️ [481/1000] Video ID: _ki2HRFRPJk
▶️ [482/1000] Video ID: VJMff9NoGTQ
▶️ [483/1000] Video ID: J2_MObjw3VY
▶️ [484/1000] Video ID: zQMiYCrgsI8
▶️ [485/1000] Video ID: DJMF8klmh0o
▶️ [486/1000] Video ID: FFgbgXhoAoo
▶️ [487/1000] Video ID: SyWG6pZMkqk
▶️ [488/1000] Video ID: iiSJV-WEjnY
▶️ [489/1000] Video ID: hFt2oYDHyNw
▶️ [490/1000] Video ID: MJFUP_cxlAY
▶️ [491/1000] Video ID: brv-RXSNgno
▶️ [492/1000] Video ID: 3REtW3qi79U
▶️ [493/1000] Video ID: Uzcz57C58X0
▶️ [494/1000] Video ID: V1-opRROO5s
▶️ [495/1000] Video ID: fEmj0prHA4I
▶️ [496/1000] Video ID: yspvKRLJF24
▶️ [497/1000] Video ID: wtfpxjBLmck
▶️ [498/1000] Video ID: DN3EGanYbIc
▶️ [499/1000] Video ID: SF7V_KxWh2A
▶️ [500/1000] Video ID: m-XTb3aGi1U
▶️ [501/1000] Video ID: Cf23xHSH07Y
▶️ [502/1000] Video ID: b96E8PpKk2I
▶️ [503/1000] Video ID: xBOBPYEuRh8
▶️ [504/1000] Video ID: 4MPZzHq_NVE
▶️ [505/1000] Video ID: iTpqU3Zj5qs
▶️ [506/1000] Video ID: KPvRz7BIVV8
▶️ [507/1000] Video ID: I8QJ7ef-vYQ
▶️ [508/1000] Video ID: d3cTpcYP8mM
▶️ [509/1000] Video ID: DpFH1XZES7A
▶️ [510/1000] Video ID: z3Z4ut6pyvM
▶️ [511/1000] Video ID: Cl8akXndHtA
▶️ [512/1000] Video ID: pEOEBNKMZhI
▶️ [513/1000] Video ID: 67IFLpVuH8U
▶️ [514/1000] Video ID: Ci6w1Jpq9Rw
▶️ [515/1000] Video ID: PcIl711txE0
▶️ [516/1000] Video ID: VHxRCMt-msM
▶️ [517/1000] Video ID: 5m_XoVAJ-Wo
▶️ [518/1000] Video ID: hWvjw8b9ihM
▶️ [519/1000] Video ID: SGf3bMHwRcE
▶️ [520/1000] Video ID: cJj3i-O61No
▶️ [521/1000] Video ID: XB6ex2YqCwo
▶️ [522/1000] Video ID: gc3TLjlrmiA
▶️ [523/1000] Video ID: JlNLUcoUve0
▶️ [524/1000] Video ID: 3Zvm4SrNnjI
▶️ [525/1000] Video ID: 4n7Y4tLPin8
▶️ [526/1000] Video ID: ylN_qvhTjR4
▶️ [527/1000] Video ID: WsfANpiPfMg
▶️ [528/1000] Video ID: DtlzVNHsxk0
▶️ [529/1000] Video ID: xV4Mb7WG-gI
▶️ [530/1000] Video ID: l6XkJZ-jIGA
▶️ [531/1000] Video ID: 7WT9vXM0BAs
▶️ [532/1000] Video ID: jID6KO8OVl0
▶️ [533/1000] Video ID: GoJZgZyweS0
▶️ [534/1000] Video ID: SKL9x6b9m4s
▶️ [535/1000] Video ID: 31RvX6F_uUs
▶️ [536/1000] Video ID: v60RuEWTluY
▶️ [537/1000] Video ID: zODi_uDzfjk
▶️ [538/1000] Video ID: LVeg8ocuZiQ
▶️ [539/1000] Video ID: wJ_Q98mmIKw
▶️ [540/1000] Video ID: 82Dervt5E18
▶️ [541/1000] Video ID: 9WmclFKZ8iE
▶️ [542/1000] Video ID: VYN3bptsVYc
▶️ [543/1000] Video ID: ztBKQY6WDNU
▶️ [544/1000] Video ID: b2LG0bBMcz0
▶️ [545/1000] Video ID: PHtKec6PqPA
▶️ [546/1000] Video ID: IAHxjau4rjY
▶️ [547/1000] Video ID: USTnc6eiwec
▶️ [548/1000] Video ID: PJIr4DDjd6s
▶️ [549/1000] Video ID: d843cil5x0U
▶️ [550/1000] Video ID: VglzchhoelQ
▶️ [551/1000] Video ID: aopKGUNs3P0
▶️ [552/1000] Video ID: kvfGZanIk1Q
▶️ [553/1000] Video ID: ZDrspuymyZo
▶️ [554/1000] Video ID: BKR27Bb_sSM
▶️ [555/1000] Video ID: do0tuB-lsMA
▶️ [556/1000] Video ID: DJ7EwPNwDLE

# Chelsea

In [5]:
from googleapiclient.discovery import build
import time
import pandas as pd

API_KEY = 'AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ'  # Replace with your actual API key
youtube = build('youtube', 'v3', developerKey=API_KEY)

def get_channel_id_from_url(url):
    if '@' in url:
        handle = url.split('@')[1]
        res = youtube.search().list(
            q=handle,
            type='channel',
            maxResults=1,
            part='snippet'
        ).execute()
        if res['items']:
            return res['items'][0]['snippet']['channelId']
    return None

def get_uploads_playlist_id(channel_id):
    res = youtube.channels().list(
        part='contentDetails',
        id=channel_id
    ).execute()
    if res['items']:
        return res['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    return None

def get_recent_video_ids(playlist_id, count):
    video_ids = []
    next_page_token = None

    while len(video_ids) < count:
        res = youtube.playlistItems().list(
            playlistId=playlist_id,
            part='contentDetails',
            maxResults=50,
            pageToken=next_page_token
        ).execute()

        for item in res['items']:
            video_ids.append(item['contentDetails']['videoId'])
            if len(video_ids) >= count:
                break

        next_page_token = res.get('nextPageToken')
        if not next_page_token:
            break

    return video_ids

def get_top_level_comments(video_id, max_comments=None):
    comments = []
    next_page_token = None

    while True:
        try:
            res = youtube.commentThreads().list(
                part='snippet',
                videoId=video_id,
                maxResults=100,
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in res['items']:
                snippet = item['snippet']['topLevelComment']['snippet']
                comments.append({
                    'Commenter Name': snippet['authorDisplayName'],
                    'Comment': snippet['textDisplay'],
                    'Comment Like Count': snippet['likeCount']
                })

                if max_comments and len(comments) >= max_comments:
                    return comments

            next_page_token = res.get('nextPageToken')
            if not next_page_token:
                break

        except Exception as e:
            print(f"Error fetching comments for video {video_id}: {e}")
            break

        time.sleep(0.5)

    return comments

def get_video_metadata(video_id):
    res = youtube.videos().list(
        part='snippet,statistics',
        id=video_id
    ).execute()

    if not res['items']:
        return None

    item = res['items'][0]
    return {
        'Video ID': video_id,
        'Video Title': item['snippet']['title'],
        'View Count': item['statistics'].get('viewCount'),
        'Like Count': item['statistics'].get('likeCount'),
        'Comment Count': item['statistics'].get('commentCount'),
        'YouTube Channel': item['snippet']['channelTitle']
    }

def collect_all_comments(channel_url, num_videos, output_filename):
    channel_id = get_channel_id_from_url(channel_url)
    if not channel_id:
        print(f"❌ Could not find channel ID from URL: {channel_url}")
        return

    playlist_id = get_uploads_playlist_id(channel_id)
    video_ids = get_recent_video_ids(playlist_id, num_videos)
    print(f"📺 Processing {len(video_ids)} videos from {channel_url}")

    all_comments = []

    for i, vid in enumerate(video_ids, 1):
        print(f"▶️ [{i}/{len(video_ids)}] Video ID: {vid}")
        video_meta = get_video_metadata(vid)
        if not video_meta:
            continue

        comments = get_top_level_comments(vid)
        for c in comments:
            all_comments.append({
                'Video Title': video_meta['Video Title'],
                'Like Count': video_meta['Like Count'],
                'View Count': video_meta['View Count'],
                'Comment Count': video_meta['Comment Count'],
                'Commenter Name': c['Commenter Name'],
                'Comment': c['Comment'],
                'Comment Like Count': c['Comment Like Count'],
                'YouTube Channel': video_meta['YouTube Channel']
            })

        time.sleep(1)

    df = pd.DataFrame(all_comments)
    df.to_csv(output_filename, index=False, encoding='utf-8-sig')
    print(f"💾 Saved {len(all_comments)} comments to: {output_filename}")

if __name__ == '__main__':
    barca_url = "https://www.youtube.com/@chelseafc"
    collect_all_comments(barca_url, num_videos=1000, output_filename="chelsea.csv")

📺 Processing 1000 videos from https://www.youtube.com/@chelseafc
▶️ [1/1000] Video ID: bhQM5mAvOSg
Error fetching comments for video bhQM5mAvOSg: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=bhQM5mAvOSg&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [2/1000] Video ID: ccPEn1OzQDg
Error fetching comments for video ccPEn1OzQDg: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=ccPEn1OzQDg&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [3/1000] Video ID: M_gIe-ixuKA
▶️ [4/1000] Video ID: i5WVvKhYrJg
▶️ [5/1000] Video ID: J8XSx2xKw0I
▶️ [6/1000] Video ID: YY1B0zue_cI
Error fetching comments for video YY1B0zue_cI: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=YY1B0zue_cI&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [7/1000] Video ID: FjAcJUm5Ukg
▶️ [8/1000] Video ID: kqwkfwsVqG8
▶️ [9/1000] Video ID: VYEYEr3cDVs
▶️ [10/1000] Video ID: uT0Ypun_7D0
▶️ [11/1000] Video ID: tJgmgMtZSZw
▶️ [12/1000] Video ID: dOVxwFqmqyY
▶️ [13/1000] Video ID: jtUTPzieo3g
▶️ [14/1000] Video ID: TtWMr8WFJME
▶️ [15/1000] Video ID: UOkufnxwTyo
▶️ [16/1000] Video ID: y_99GhZWqnA
▶️ [17/1000] Video ID: FBLQoM-uY_8
▶️ [18/1000] Video ID: GJUf4pu4hNc
▶️ [19/1000] Video ID: E5dXujzIxTs
▶️ [20/1000] Video ID: khy-X2I6Nx4
▶️ [21/1000] Video ID: g0IoHplfPgk
▶️ [22/1000] Video ID: UmZCYcRlP3o
▶️ [23/1000] Video ID: __FmK75uGTc
▶️ [24/1000] Video ID: EYBHjm5_TKw
▶️ [25/1000] Video ID: 3IZuf5gcGLM
▶️ [26/1000] Video ID: wsXsZ9Rs8zI
▶️ [27/1000] Video ID: XbhoVJ81lCM
▶️ [28/1000] Video ID: 5AJx5wSUmGo
▶️ [29/1000] Video ID: OWTa3Gwjajo
▶️ [30/1000] Video ID: I4ri2WUYiDo
▶️ [31/1000] Video ID: RfjoIqsPhyQ
▶️ [32/1000] Video ID: ANvcE94DMAQ
▶️ [33/1000] Video ID: LTRjFPKKo0k
▶️ [34/1000] Video ID: mF6f6ke4t60
▶️ [35/1000] Video ID: mtlLYH_VEHo
▶️ [36/1000] Video ID: xuc8Dk5ynTE
▶️ [37/1000] Video ID: 2-RI6MGftUc
▶️ [38/1000] Video ID: LbjO3gQTML4
▶️ [39/1000] Video ID: -IDAY_-Qu-k
▶️ [40/1000] Video ID: _2cCgMgdP8I
▶️ [41/1000] Video ID: EikIZyFt-l8
▶️ [42/1000] Video ID: vxAa9GCOvOI
▶️ [43/1000] Video ID: ZwPyAR2xxKc
▶️ [44/1000] Video ID: Rok9cyeJ8W8
▶️ [45/1000] Video ID: 1ZNSZh8hv3k
▶️ [46/1000] Video ID: nXje9MuRJlk
▶️ [47/1000] Video ID: qHue6EHzW4k
▶️ [48/1000] Video ID: fwTJJvRbblA
▶️ [49/1000] Video ID: gk668nmPMt4
▶️ [50/1000] Video ID: rGKN3q71VHM
▶️ [51/1000] Video ID: gTS04Mkhwvs
▶️ [52/1000] Video ID: V9kT2dEPRrk
▶️ [53/1000] Video ID: _aqiS5FyFXE
▶️ [54/1000] Video ID: 1bVFcnpUqM0
▶️ [55/1000] Video ID: YpXG47NKNEo
▶️ [56/1000] Video ID: BAgZAO4kyj8
▶️ [57/1000] Video ID: -dSHktchras
▶️ [58/1000] Video ID: 4w_cui5H3VM
▶️ [59/1000] Video ID: eh6ToAerBew
▶️ [60/1000] Video ID: 2t6NUyyJwOI
▶️ [61/1000] Video ID: My68AaoFYZQ
▶️ [62/1000] Video ID: 4fCs2GgnZgg
▶️ [63/1000] Video ID: gdycs87DSbI
▶️ [64/1000] Video ID: 8ajbAENnT-E
▶️ [65/1000] Video ID: h6OwgKylzCs
▶️ [66/1000] Video ID: 3kBBK29JVMo
▶️ [67/1000] Video ID: Wr3VKamUjHM
▶️ [68/1000] Video ID: FG8QIPZTWd0
▶️ [69/1000] Video ID: eFHQIxN8TWI
▶️ [70/1000] Video ID: dXXhzTEoeAs
▶️ [71/1000] Video ID: nCGZW-xDo5Q
▶️ [72/1000] Video ID: HU8pKIa9sTE
▶️ [73/1000] Video ID: oJl4K2lpZlE
▶️ [74/1000] Video ID: KcqAmSGr0FY
▶️ [75/1000] Video ID: J8jkVX53Q2M
▶️ [76/1000] Video ID: u-6u61F9Ygs
▶️ [77/1000] Video ID: BmaKk4N71FI
▶️ [78/1000] Video ID: 9aA5PJ8d3xg
▶️ [79/1000] Video ID: 3V56sdxPDg4
▶️ [80/1000] Video ID: wN92GCM7vSk
▶️ [81/1000] Video ID: jQ320N6c0do
▶️ [82/1000] Video ID: iPA7N2aQhsw
▶️ [83/1000] Video ID: DZvkYA7CM_k
▶️ [84/1000] Video ID: YrWcCkGTFRI
▶️ [85/1000] Video ID: fpOnPqXE-yU
▶️ [86/1000] Video ID: iO6cpYmIMDI
▶️ [87/1000] Video ID: XI0b4tkJO2g
▶️ [88/1000] Video ID: P-t6RaGEgSo
▶️ [89/1000] Video ID: 6l_pvNLEhNo
▶️ [90/1000] Video ID: hzQ52WUVbsU
▶️ [91/1000] Video ID: SA5v41kqjDE
▶️ [92/1000] Video ID: r2obfFOtnbk
▶️ [93/1000] Video ID: mK5sjayVYSw
▶️ [94/1000] Video ID: zQHHujE5iME
▶️ [95/1000] Video ID: b_vvijpqW8Q
▶️ [96/1000] Video ID: g8iDB-XJ-Ws
▶️ [97/1000] Video ID: lr376BW84Q0
▶️ [98/1000] Video ID: yiseqzlmjHY
▶️ [99/1000] Video ID: _q6F20ytbUE
▶️ [100/1000] Video ID: skg-lydt89w
▶️ [101/1000] Video ID: q16UzXfZfas
▶️ [102/1000] Video ID: Mxv0-rEdgsM
▶️ [103/1000] Video ID: PXdRKoh0YqY
▶️ [104/1000] Video ID: _eKwiiYihxg
▶️ [105/1000] Video ID: EerxnS3799U
▶️ [106/1000] Video ID: aLrK_BjS14A
▶️ [107/1000] Video ID: EsIs_s2KFYs
▶️ [108/1000] Video ID: dseaGmu8rhA
▶️ [109/1000] Video ID: eC2iCciUEFI
▶️ [110/1000] Video ID: pHdkLta4tR0
▶️ [111/1000] Video ID: DwMCzmuVzn8
▶️ [112/1000] Video ID: pF_P9fYABv0
▶️ [113/1000] Video ID: i5t_spDMP14
▶️ [114/1000] Video ID: lEqvVWXt9hk
▶️ [115/1000] Video ID: VuTFbfnk-eE
▶️ [116/1000] Video ID: cju0PKRQCKI
▶️ [117/1000] Video ID: PSizpkrbk3M
▶️ [118/1000] Video ID: J31MJE8Ccvs
▶️ [119/1000] Video ID: a3_2zyEB2CI
▶️ [120/1000] Video ID: FZ5XGYQRv0I
▶️ [121/1000] Video ID: sR69M3O_uss
▶️ [122/1000] Video ID: q_jkgLhpNqY
▶️ [123/1000] Video ID: k48ePcr2xJE
▶️ [124/1000] Video ID: HH-4Ci5KvAA
▶️ [125/1000] Video ID: ZihYgzgsMbw
▶️ [126/1000] Video ID: PgTm6Ahlt1E
▶️ [127/1000] Video ID: T1Xgl2nL8O0
▶️ [128/1000] Video ID: Nz556v7gtRs
▶️ [129/1000] Video ID: PU6Vg9iGEyA
▶️ [130/1000] Video ID: lAoro-gCuH8
▶️ [131/1000] Video ID: B2LMthZXmKQ
▶️ [132/1000] Video ID: 3AyWskMvDj8
▶️ [133/1000] Video ID: 8Go9tcdkD-U
▶️ [134/1000] Video ID: -gutgMDk1Dg
▶️ [135/1000] Video ID: g8lRZhJB5LQ
▶️ [136/1000] Video ID: q9fvekhDy1I
▶️ [137/1000] Video ID: 6uZ2caIonzo
▶️ [138/1000] Video ID: UNjd2mWRjEQ
▶️ [139/1000] Video ID: CNy9WgO0wDk
▶️ [140/1000] Video ID: jB2mtorYXe4
▶️ [141/1000] Video ID: UM5j1UqcIIA
▶️ [142/1000] Video ID: kPxCT7QROOA
▶️ [143/1000] Video ID: I-_2zU14tsg
▶️ [144/1000] Video ID: E-ddpNNhg2Q
▶️ [145/1000] Video ID: smcoMTtmm2Q
▶️ [146/1000] Video ID: -ITKXzG7wjQ
▶️ [147/1000] Video ID: oo6GsfRPB6M
▶️ [148/1000] Video ID: 22VL9Gwf8KQ
▶️ [149/1000] Video ID: VtBwqMapEBo
▶️ [150/1000] Video ID: 9QrR1bZAk7U
▶️ [151/1000] Video ID: tN_chJ70q2c
▶️ [152/1000] Video ID: LN1Quydv4kw
▶️ [153/1000] Video ID: jELEVSRZhGc
▶️ [154/1000] Video ID: 4FwXMN74QIk
▶️ [155/1000] Video ID: b6w7sGA6wd4
▶️ [156/1000] Video ID: iiLVjQ_qp-Y
▶️ [157/1000] Video ID: jl2XgLtDopc
▶️ [158/1000] Video ID: 7AtsYlXxdDk
▶️ [159/1000] Video ID: JoH86TRpL78
▶️ [160/1000] Video ID: PYhB1Q0xoPg
▶️ [161/1000] Video ID: q_gXUf0TbwA
▶️ [162/1000] Video ID: sEA4ciz7Wco
▶️ [163/1000] Video ID: Kk3lhj6U8ZM
▶️ [164/1000] Video ID: R53cusTQ6Yg
▶️ [165/1000] Video ID: RZo-z2CcbBs
▶️ [166/1000] Video ID: lAauYyy3bcY
▶️ [167/1000] Video ID: 2eqEA_MUyzA
▶️ [168/1000] Video ID: Pp-iAJ77RqU
▶️ [169/1000] Video ID: YfxjuuARjOg
▶️ [170/1000] Video ID: hBA_qf58mqo
▶️ [171/1000] Video ID: HP434qyzktI
▶️ [172/1000] Video ID: mAW7GooxNRk
▶️ [173/1000] Video ID: leH0ZwLKxY4
▶️ [174/1000] Video ID: zQw4lLAbWvA
▶️ [175/1000] Video ID: 77Dx74FQBL0
▶️ [176/1000] Video ID: akGdPgBRMls
▶️ [177/1000] Video ID: Geego2Se9ro
▶️ [178/1000] Video ID: eU70GVf7CvQ
▶️ [179/1000] Video ID: Vt9y5I1Fbfw
▶️ [180/1000] Video ID: GgiiIuCMZI8
▶️ [181/1000] Video ID: 7yJc-pwY2Sg
▶️ [182/1000] Video ID: lmO1dxOWvzE
▶️ [183/1000] Video ID: PYYYOD4G6GU
Error fetching comments for video PYYYOD4G6GU: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=PYYYOD4G6GU&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [184/1000] Video ID: fTHfLodbS-o
▶️ [185/1000] Video ID: zCKl6DW9BAU
▶️ [186/1000] Video ID: 5uaVX1KF9cI
▶️ [187/1000] Video ID: nRKiQdl1yyU
▶️ [188/1000] Video ID: NqJgz1Au0jU
▶️ [189/1000] Video ID: VjVz1JkdB0A
▶️ [190/1000] Video ID: YTOABVRgxBQ
▶️ [191/1000] Video ID: 4teKBCDSVDw
▶️ [192/1000] Video ID: EVWdxHfjNFA
▶️ [193/1000] Video ID: _CGjwG6OxVQ
▶️ [194/1000] Video ID: T-yBbZnqS1w
▶️ [195/1000] Video ID: y7n8unSXZvg
▶️ [196/1000] Video ID: igUUOM9kl6A
▶️ [197/1000] Video ID: 8pxXZUiqMos
▶️ [198/1000] Video ID: -G5-RMkZ2mg
▶️ [199/1000] Video ID: u_WN0SX2upE
▶️ [200/1000] Video ID: vw3yZsAiqN4
▶️ [201/1000] Video ID: ilm0YZg5d0Y
▶️ [202/1000] Video ID: z_M1LpfTJe8
▶️ [203/1000] Video ID: CQi8ZSPDw8A
▶️ [204/1000] Video ID: MzOMGjuXma0
▶️ [205/1000] Video ID: lCe4EIVikH0
▶️ [206/1000] Video ID: kE81kCAL9s0
▶️ [207/1000] Video ID: mOJHKxDw62M
▶️ [208/1000] Video ID: zRSVOi9q3Uk
▶️ [209/1000] Video ID: s-RHSAA8_FU
▶️ [210/1000] Video ID: oP0v04MaIqY
▶️ [211/1000] Video ID: kBzYPRVJ6J0
▶️ [212/1000] Video ID: PXkNEE-pMEE
▶️ [213/1000] Video ID: IxDuqC2mSg4
▶️ [214/1000] Video ID: -H8tvnWaYs4
▶️ [215/1000] Video ID: wGXq7AKHOfU
▶️ [216/1000] Video ID: j72XUucnRE4
▶️ [217/1000] Video ID: cZiPFV2Tctg
▶️ [218/1000] Video ID: VPyqsQNSJeo
▶️ [219/1000] Video ID: KJFWF7zLlUE
▶️ [220/1000] Video ID: if2J0tnxTic
▶️ [221/1000] Video ID: 3zJsKoyG99E
▶️ [222/1000] Video ID: oQYV5OYLz9k
▶️ [223/1000] Video ID: CK33uk28-4g
▶️ [224/1000] Video ID: TIWRyARV7LI
▶️ [225/1000] Video ID: a70jvT0g7kE
▶️ [226/1000] Video ID: cz8YoP7Qobk
▶️ [227/1000] Video ID: ucgcRYCnOHo
▶️ [228/1000] Video ID: 94MPOQgD7Ss
▶️ [229/1000] Video ID: _Y738CeWm1o
▶️ [230/1000] Video ID: xhUdSIFTq_U
▶️ [231/1000] Video ID: UjYItKgSshQ
▶️ [232/1000] Video ID: JL9Ho7yx4xU
▶️ [233/1000] Video ID: trmdexxIcXU
▶️ [234/1000] Video ID: xtR6lgQsgPo
▶️ [235/1000] Video ID: tJuneQ6yVH4
▶️ [236/1000] Video ID: 5chSV8Df1VM
▶️ [237/1000] Video ID: kPnJr9p2wYg
▶️ [238/1000] Video ID: wDHPzlJc6TE
▶️ [239/1000] Video ID: ks-_Bc6sACY
▶️ [240/1000] Video ID: Us6WtmS7eK0
▶️ [241/1000] Video ID: URG03WSgXjQ
▶️ [242/1000] Video ID: H8vytmLyEE4
▶️ [243/1000] Video ID: Alc3cUIB__4
▶️ [244/1000] Video ID: n1Qnz_a_jSc
▶️ [245/1000] Video ID: YkuEbeDRpuE
▶️ [246/1000] Video ID: LXZ02hN1JSI
▶️ [247/1000] Video ID: HEijVuadI7U
▶️ [248/1000] Video ID: rR9WpWOYqyI
▶️ [249/1000] Video ID: M5aQQzf5BOg
▶️ [250/1000] Video ID: IKTC2gGEOVA
▶️ [251/1000] Video ID: diPRObfj04M
▶️ [252/1000] Video ID: P9YCv1qBZYk
▶️ [253/1000] Video ID: 9zIIkiQ60MI
▶️ [254/1000] Video ID: 7WgW2OWoews
▶️ [255/1000] Video ID: 4PZiRY-Q36Q
▶️ [256/1000] Video ID: oVnEPDhgSlI
▶️ [257/1000] Video ID: NlJZXhFLFMI
▶️ [258/1000] Video ID: yehk64wywJc
▶️ [259/1000] Video ID: GSNKbOMUxjM
▶️ [260/1000] Video ID: HHHphbFrvgw
▶️ [261/1000] Video ID: J0jhTf8ocbc
▶️ [262/1000] Video ID: ojXvuHfQg4A
▶️ [263/1000] Video ID: _cdHhZmUAzU
▶️ [264/1000] Video ID: Z_AeZhVXf_A
▶️ [265/1000] Video ID: TdJ-QGo7goU
▶️ [266/1000] Video ID: 6t1wCLe3zOY
▶️ [267/1000] Video ID: rx5Lt1bmfqs
▶️ [268/1000] Video ID: L7xuWI90NpA
▶️ [269/1000] Video ID: 86PSdv3SB-c
▶️ [270/1000] Video ID: D2KT13d-uGo
▶️ [271/1000] Video ID: B-VtfCsW8_0
▶️ [272/1000] Video ID: fCcuEHQGu6E
▶️ [273/1000] Video ID: NlZcTWk8Xe4
▶️ [274/1000] Video ID: HZVdDqQqW3I
▶️ [275/1000] Video ID: 50HYlaEYJso
▶️ [276/1000] Video ID: 0KsoZtpew_o
▶️ [277/1000] Video ID: b-4fL-6Pf0w
▶️ [278/1000] Video ID: jqUyv8F90-k
▶️ [279/1000] Video ID: TDQoRGAqR_c
▶️ [280/1000] Video ID: L9hSjIC9sdM
▶️ [281/1000] Video ID: P7fmULP-DAw
▶️ [282/1000] Video ID: J1YoH4Je9gM
▶️ [283/1000] Video ID: yLLXb4PveD4
▶️ [284/1000] Video ID: VSOiqdg2GHo
▶️ [285/1000] Video ID: t3k525zVL0o
▶️ [286/1000] Video ID: YbROCJdzd-A
▶️ [287/1000] Video ID: HD_yO-qTfjY
▶️ [288/1000] Video ID: 7TUKC6nN4lk
▶️ [289/1000] Video ID: E6d3vA7EVsI
▶️ [290/1000] Video ID: uVEzY8mte1o
▶️ [291/1000] Video ID: hRZgvwtdHeA
▶️ [292/1000] Video ID: pImTPp4iFNE
▶️ [293/1000] Video ID: qSNyQbj8GgY
▶️ [294/1000] Video ID: GOQSOnUPuKE
▶️ [295/1000] Video ID: u85LxDIFwnI
▶️ [296/1000] Video ID: ltYqbl2MyEg
▶️ [297/1000] Video ID: JkZ16-IlJsM
▶️ [298/1000] Video ID: ulNM7wfuapo
▶️ [299/1000] Video ID: mufdpTDpgCw
▶️ [300/1000] Video ID: uhDQqQt-Qn8
▶️ [301/1000] Video ID: KhKQS7aniYY
▶️ [302/1000] Video ID: f4oesdhet2U
▶️ [303/1000] Video ID: klNlldycyls
▶️ [304/1000] Video ID: 3djrZeUmblg
▶️ [305/1000] Video ID: 0keretPdVaE
▶️ [306/1000] Video ID: Z50an3x-40Q
▶️ [307/1000] Video ID: r-hIaYM0p4Y
▶️ [308/1000] Video ID: 9kUbYwlfNmo
▶️ [309/1000] Video ID: NYHaCWloEXk
▶️ [310/1000] Video ID: gIGkeYnqObM
▶️ [311/1000] Video ID: lKHuLiPeh2s
▶️ [312/1000] Video ID: G7TzZo1heNU
▶️ [313/1000] Video ID: mFGsElWE4jc
▶️ [314/1000] Video ID: 6sI73Mk8Woo
▶️ [315/1000] Video ID: qHoU6AIz1iY
▶️ [316/1000] Video ID: rD1xj8xjzlg
▶️ [317/1000] Video ID: TZhBxticYhQ
▶️ [318/1000] Video ID: CIIeHuXA7_w
▶️ [319/1000] Video ID: SZZajLbNgNE
▶️ [320/1000] Video ID: mBzkoKzfW8w
▶️ [321/1000] Video ID: ee76RovbxN4
▶️ [322/1000] Video ID: y-Z3zKYq7Vg
▶️ [323/1000] Video ID: 8pvz8IEL_cI
▶️ [324/1000] Video ID: yXw09LJ3A4U
▶️ [325/1000] Video ID: 1G-DUjjPN4Q
▶️ [326/1000] Video ID: NzJOiT8lwNA
▶️ [327/1000] Video ID: WO78WIz6J9I
▶️ [328/1000] Video ID: WPyPj9COgsE
▶️ [329/1000] Video ID: 4h4if4ABinc
▶️ [330/1000] Video ID: _dNPIUsODrM
▶️ [331/1000] Video ID: pAKlqfrNhRs
▶️ [332/1000] Video ID: ZDDNQ9OnPvo
▶️ [333/1000] Video ID: mg4vEJScjyc
▶️ [334/1000] Video ID: gb8KrU-svDw
▶️ [335/1000] Video ID: rMhZj7MNSsg
▶️ [336/1000] Video ID: -9FE73ISBMs
▶️ [337/1000] Video ID: KQoSqFHCngw
▶️ [338/1000] Video ID: JZ74i15pq68
▶️ [339/1000] Video ID: N86kUJo-SX0
▶️ [340/1000] Video ID: _D3B-_8Na40
▶️ [341/1000] Video ID: USBXiVaTOYY
▶️ [342/1000] Video ID: VbDzMLhrsro
▶️ [343/1000] Video ID: UDfIZhv8CkM
▶️ [344/1000] Video ID: n8KVHy5-eds
▶️ [345/1000] Video ID: asHQAp0iWFY
▶️ [346/1000] Video ID: 5X3LqdCXaQA
▶️ [347/1000] Video ID: 7hs7VfD52gU
▶️ [348/1000] Video ID: -YkyPd_X3qg
▶️ [349/1000] Video ID: dC_tSAajtrY
▶️ [350/1000] Video ID: fVBZTxua1XM
▶️ [351/1000] Video ID: zD1M55lVKso
▶️ [352/1000] Video ID: Cnlf6QuORp0
▶️ [353/1000] Video ID: Uz92keVW9Rk
▶️ [354/1000] Video ID: odlYyP5KIFI
▶️ [355/1000] Video ID: dn4OtXM_hxY
▶️ [356/1000] Video ID: BhQa2n3MWRM
▶️ [357/1000] Video ID: _ay7-I18Iqk
▶️ [358/1000] Video ID: yTEt89SZpww
▶️ [359/1000] Video ID: IZj7NDW8SaA
▶️ [360/1000] Video ID: eYbYFfubQGA
▶️ [361/1000] Video ID: qmE1gi8bLJk
▶️ [362/1000] Video ID: jf9mp8MWOtg
▶️ [363/1000] Video ID: dUg5SnoEPsw
▶️ [364/1000] Video ID: outLDEOE5Pw
▶️ [365/1000] Video ID: TEjyRjZnJAY
▶️ [366/1000] Video ID: dHQt21oD048
▶️ [367/1000] Video ID: RtJq3MRL4U8
▶️ [368/1000] Video ID: QedthnUpy5g
▶️ [369/1000] Video ID: isrK-Mazi-o
▶️ [370/1000] Video ID: MSywvIHe_fE
▶️ [371/1000] Video ID: QYldUseiUUo
▶️ [372/1000] Video ID: DZ9ue3Q9c_A
▶️ [373/1000] Video ID: vXStFymG0-c
▶️ [374/1000] Video ID: PC1fYaQzWiA
▶️ [375/1000] Video ID: XMHiF_s7vRo
▶️ [376/1000] Video ID: CTiRqBQA_xM
▶️ [377/1000] Video ID: RhluAKR_-o0
▶️ [378/1000] Video ID: 3IT58egPlgc
▶️ [379/1000] Video ID: drSkf_KKsdw
▶️ [380/1000] Video ID: Rvfs9iLs99I
▶️ [381/1000] Video ID: fmKKE3bXe0g
▶️ [382/1000] Video ID: TF2IvYODIhc
▶️ [383/1000] Video ID: HqmFxVjkJy0
▶️ [384/1000] Video ID: Ji6HECRHYHI
▶️ [385/1000] Video ID: fKdMTQynVDA
▶️ [386/1000] Video ID: XfgMge875m8
▶️ [387/1000] Video ID: RezX8S4TJSs
▶️ [388/1000] Video ID: W_69Aye23dE
▶️ [389/1000] Video ID: YysU73hPcZ4
▶️ [390/1000] Video ID: yLpy8HIYZC0
▶️ [391/1000] Video ID: -j6VlfjIzmM
▶️ [392/1000] Video ID: 9pfj6iw-7FE
▶️ [393/1000] Video ID: Ldw7fG1hwOg
▶️ [394/1000] Video ID: IIE20q7kz2o
▶️ [395/1000] Video ID: QJjtol0njMM
▶️ [396/1000] Video ID: 2Lt5L5hyzWA
▶️ [397/1000] Video ID: v4jcw6ZiPZ8
▶️ [398/1000] Video ID: eHoz3u98iOc
▶️ [399/1000] Video ID: fs_7nLjE_LE
▶️ [400/1000] Video ID: 9gtmmnmRTk0
▶️ [401/1000] Video ID: M66w_eEJob8
▶️ [402/1000] Video ID: X3U4hKT0P6A
▶️ [403/1000] Video ID: VlKyZ-MMAGs
▶️ [404/1000] Video ID: orCkIVtFA00
▶️ [405/1000] Video ID: CVqHQLH-od0
▶️ [406/1000] Video ID: saHLRxkcULs
▶️ [407/1000] Video ID: lNSJeYfQsvE
▶️ [408/1000] Video ID: I7fxSdocv-c
▶️ [409/1000] Video ID: vmiyKH_MqZ8
▶️ [410/1000] Video ID: 1ytbJbNNYFk
▶️ [411/1000] Video ID: huIw_P_8I2E
▶️ [412/1000] Video ID: WCT4ruekqF8
▶️ [413/1000] Video ID: 11Wfamgcx_8
▶️ [414/1000] Video ID: 7jOZ2-TS1y8
▶️ [415/1000] Video ID: 9oj96CgBPdI
▶️ [416/1000] Video ID: IDqiTomZ64U
▶️ [417/1000] Video ID: I8C-Tnma8E4
▶️ [418/1000] Video ID: GDwMqnmi-D0
▶️ [419/1000] Video ID: cuIeZ9e1lFo
▶️ [420/1000] Video ID: 6lzcxOmupKo
▶️ [421/1000] Video ID: 8VatU5T5Uts
▶️ [422/1000] Video ID: C_CPDP1scO8
▶️ [423/1000] Video ID: J-VLUyH_pbc
▶️ [424/1000] Video ID: MG9wP7H1ghg
▶️ [425/1000] Video ID: hJ2p1UNxCU4
▶️ [426/1000] Video ID: Sz1i7PQPdrg
▶️ [427/1000] Video ID: 2FII0Jx1nSE
▶️ [428/1000] Video ID: Av1l1agyEZ8
▶️ [429/1000] Video ID: zOaeIEP0bXc
▶️ [430/1000] Video ID: Gk0MCQWlMcg
▶️ [431/1000] Video ID: qmibl3vg-qU
▶️ [432/1000] Video ID: yuZk6tBQYRg
▶️ [433/1000] Video ID: zljfdvQ5aDQ
▶️ [434/1000] Video ID: 265OMvoByxw
▶️ [435/1000] Video ID: QhIH69x0RdY
▶️ [436/1000] Video ID: RXK_KixK8os
▶️ [437/1000] Video ID: rQz5-E33_og
▶️ [438/1000] Video ID: yoR8PhDXX-o
▶️ [439/1000] Video ID: mfbF_hMfpsY
▶️ [440/1000] Video ID: ZeulPCn4T7k
▶️ [441/1000] Video ID: YVelDLyB6vs
▶️ [442/1000] Video ID: ftYqQU3mveE
▶️ [443/1000] Video ID: ofbPAt28A_o
▶️ [444/1000] Video ID: kVaus6yaI70
▶️ [445/1000] Video ID: 9zeJr2eeneU
▶️ [446/1000] Video ID: ekiEW-mOXJE
▶️ [447/1000] Video ID: ZagpHgxcrn4
▶️ [448/1000] Video ID: em6yFzDPLnk
▶️ [449/1000] Video ID: Y1Y35xVxMnk
▶️ [450/1000] Video ID: 6F_NgOPIK0w
▶️ [451/1000] Video ID: 0Ns2_2SIFfA
▶️ [452/1000] Video ID: RMfWq9bxhEo
▶️ [453/1000] Video ID: 93JK-gqwLcs
▶️ [454/1000] Video ID: errVwJpSrrQ
▶️ [455/1000] Video ID: UUc5gal3mPM

KeyboardInterrupt:

# Juventus

In [ ]:
from googleapiclient.discovery import build
import time
import pandas as pd

API_KEY = 'AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ'  # Replace with your actual API key
youtube = build('youtube', 'v3', developerKey=API_KEY)

def get_channel_id_from_url(url):
    if '@' in url:
        handle = url.split('@')[1]
        res = youtube.search().list(
            q=handle,
            type='channel',
            maxResults=1,
            part='snippet'
        ).execute()
        if res['items']:
            return res['items'][0]['snippet']['channelId']
    return None

def get_uploads_playlist_id(channel_id):
    res = youtube.channels().list(
        part='contentDetails',
        id=channel_id
    ).execute()
    if res['items']:
        return res['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    return None

def get_recent_video_ids(playlist_id, count):
    video_ids = []
    next_page_token = None

    while len(video_ids) < count:
        res = youtube.playlistItems().list(
            playlistId=playlist_id,
            part='contentDetails',
            maxResults=50,
            pageToken=next_page_token
        ).execute()

        for item in res['items']:
            video_ids.append(item['contentDetails']['videoId'])
            if len(video_ids) >= count:
                break

        next_page_token = res.get('nextPageToken')
        if not next_page_token:
            break

    return video_ids

def get_top_level_comments(video_id, max_comments=None):
    comments = []
    next_page_token = None

    while True:
        try:
            res = youtube.commentThreads().list(
                part='snippet',
                videoId=video_id,
                maxResults=100,
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in res['items']:
                snippet = item['snippet']['topLevelComment']['snippet']
                comments.append({
                    'Commenter Name': snippet['authorDisplayName'],
                    'Comment': snippet['textDisplay'],
                    'Comment Like Count': snippet['likeCount']
                })

                if max_comments and len(comments) >= max_comments:
                    return comments

            next_page_token = res.get('nextPageToken')
            if not next_page_token:
                break

        except Exception as e:
            print(f"Error fetching comments for video {video_id}: {e}")
            break

        time.sleep(0.5)

    return comments

def get_video_metadata(video_id):
    res = youtube.videos().list(
        part='snippet,statistics',
        id=video_id
    ).execute()

    if not res['items']:
        return None

    item = res['items'][0]
    return {
        'Video ID': video_id,
        'Video Title': item['snippet']['title'],
        'View Count': item['statistics'].get('viewCount'),
        'Like Count': item['statistics'].get('likeCount'),
        'Comment Count': item['statistics'].get('commentCount'),
        'YouTube Channel': item['snippet']['channelTitle']
    }

def collect_all_comments(channel_url, num_videos, output_filename):
    channel_id = get_channel_id_from_url(channel_url)
    if not channel_id:
        print(f"❌ Could not find channel ID from URL: {channel_url}")
        return

    playlist_id = get_uploads_playlist_id(channel_id)
    video_ids = get_recent_video_ids(playlist_id, num_videos)
    print(f"📺 Processing {len(video_ids)} videos from {channel_url}")

    all_comments = []

    for i, vid in enumerate(video_ids, 1):
        print(f"▶️ [{i}/{len(video_ids)}] Video ID: {vid}")
        video_meta = get_video_metadata(vid)
        if not video_meta:
            continue

        comments = get_top_level_comments(vid)
        for c in comments:
            all_comments.append({
                'Video Title': video_meta['Video Title'],
                'Like Count': video_meta['Like Count'],
                'View Count': video_meta['View Count'],
                'Comment Count': video_meta['Comment Count'],
                'Commenter Name': c['Commenter Name'],
                'Comment': c['Comment'],
                'Comment Like Count': c['Comment Like Count'],
                'YouTube Channel': video_meta['YouTube Channel']
            })

        time.sleep(1)

    df = pd.DataFrame(all_comments)
    df.to_csv(output_filename, index=False, encoding='utf-8-sig')
    print(f"💾 Saved {len(all_comments)} comments to: {output_filename}")

if __name__ == '__main__':
    juve_url = "https://www.youtube.com/@Juventus"
    collect_all_comments(juve_url, num_videos=1000, output_filename="juventus.csv")

📺 Processing 1000 videos from https://www.youtube.com/@Juventus
▶️ [1/1000] Video ID: aHiLCaE72SU
▶️ [2/1000] Video ID: GiVA-h6qjEo
▶️ [3/1000] Video ID: rMOJsFFpezQ
▶️ [4/1000] Video ID: 3K049aRzwjQ
▶️ [5/1000] Video ID: ZyBpcahOktI
▶️ [6/1000] Video ID: AxWo8wNnCJo
▶️ [7/1000] Video ID: 2Erb6Kone-4
▶️ [8/1000] Video ID: RT0PlsLyaiw
▶️ [9/1000] Video ID: Y0TgAVrcxXs
▶️ [10/1000] Video ID: bDzzaxs40vo
▶️ [11/1000] Video ID: z85stSsE-FU
▶️ [12/1000] Video ID: QBGRr9kvfBA
▶️ [13/1000] Video ID: rCSuJ9cJbZY
▶️ [14/1000] Video ID: PwFOAue_Bcg
▶️ [15/1000] Video ID: tKj9mguZhzE
▶️ [16/1000] Video ID: -hub9kAnnVY
▶️ [17/1000] Video ID: xL5L_nSWMOA
▶️ [18/1000] Video ID: KzlN8QgS4eY
▶️ [19/1000] Video ID: 8T0uxPbknIQ
▶️ [20/1000] Video ID: Mvh0-rAa-AQ
▶️ [21/1000] Video ID: GM5gmtlL9qM
▶️ [22/1000] Video ID: wfV9ry46Vcw
▶️ [23/1000] Video ID: EuxaZGVFeqg
▶️ [24/1000] Video ID: C71bu00Pbkw
▶️ [25/1000] Video ID: PerD76UmE8g
▶️ [26/1000] Video ID: iSmSZQ6AJTA
▶️ [27/1000] Video ID: LGthW3FvIe0
▶️ [28/1000] Video ID: XApJcAjtBJo
▶️ [29/1000] Video ID: t1C5ZkZsx14
▶️ [30/1000] Video ID: a35u4lSgTk8
▶️ [31/1000] Video ID: yt6KFIStOuM
▶️ [32/1000] Video ID: pCL_3hGSp9k
▶️ [33/1000] Video ID: 4Wc-pDTayDk
▶️ [34/1000] Video ID: 152rDernr-w
▶️ [35/1000] Video ID: rR95v7BL8g0
▶️ [36/1000] Video ID: oaUWfpngxoM
▶️ [37/1000] Video ID: V3D01hMT0ew
▶️ [38/1000] Video ID: jYekqLJR9f4
▶️ [39/1000] Video ID: -3ba4KtbQbQ
▶️ [40/1000] Video ID: 4GNiuGvcUM4
▶️ [41/1000] Video ID: dOmimlZvCuY
▶️ [42/1000] Video ID: 81ytfObfWuk
▶️ [43/1000] Video ID: bQnJP3bqylk
▶️ [44/1000] Video ID: kHjS1JhqxKo
▶️ [45/1000] Video ID: FTldpDhukyE
▶️ [46/1000] Video ID: K4NNO26eLVw
▶️ [47/1000] Video ID: pCHBDGt2SR8
▶️ [48/1000] Video ID: -MFjJEE8Slc
▶️ [49/1000] Video ID: jjN-D_JTIpE
▶️ [50/1000] Video ID: QuCUazXXasM
▶️ [51/1000] Video ID: lnLzco2J5Ek
▶️ [52/1000] Video ID: oZdT4r-m_sA
▶️ [53/1000] Video ID: G3nHRMsnQak
▶️ [54/1000] Video ID: sf-Zm5zqCaA
▶️ [55/1000] Video ID: 9SHDDhcyxiA
▶️ [56/1000] Video ID: Dc7DcY0bOCc
▶️ [57/1000] Video ID: XExToP_QtBw
▶️ [58/1000] Video ID: zmRk3Czh5ng
▶️ [59/1000] Video ID: -F46kQ9I7K8
▶️ [60/1000] Video ID: ped7N_LdhOA
▶️ [61/1000] Video ID: AUKWdsJL--k
▶️ [62/1000] Video ID: Yvb_t3Wzg6w
▶️ [63/1000] Video ID: Tbp9_CK9skA
▶️ [64/1000] Video ID: _GOocYD2U_s
▶️ [65/1000] Video ID: E14cQCSi_5w
▶️ [66/1000] Video ID: 2OsOpPUayJw
▶️ [67/1000] Video ID: exn2WF1mNxQ
▶️ [68/1000] Video ID: ShDe6CrLqGs
▶️ [69/1000] Video ID: S14bwvb2PSQ
▶️ [70/1000] Video ID: jDBGlbCpwlw
▶️ [71/1000] Video ID: fuRQHwQKcy8
▶️ [72/1000] Video ID: aEXnmYTbU8o
▶️ [73/1000] Video ID: z9qLJkh-9SY
▶️ [74/1000] Video ID: nJ0laQVj5CA
▶️ [75/1000] Video ID: 2KtulRP38VU
▶️ [76/1000] Video ID: dYPbUe0KxaQ
▶️ [77/1000] Video ID: gZ8uwqSEe1M
▶️ [78/1000] Video ID: GkRuWHrDxmU
▶️ [79/1000] Video ID: w77Hufj1jf8
▶️ [80/1000] Video ID: UygMaWm3Gmw
▶️ [81/1000] Video ID: iJUlk9hUyY0
▶️ [82/1000] Video ID: bn0twx64mUw
▶️ [83/1000] Video ID: lokhTO9s4FA
▶️ [84/1000] Video ID: 5nVmLm8EPCU
▶️ [85/1000] Video ID: 0jt3xe5N3ak
▶️ [86/1000] Video ID: -zbHiTdLl0Y
▶️ [87/1000] Video ID: Z_8zhwLjn0U
▶️ [88/1000] Video ID: iHKBTaNhB5s
▶️ [89/1000] Video ID: sSc3LFLjusk
▶️ [90/1000] Video ID: Y6_-sgiMKEg
▶️ [91/1000] Video ID: 1FF5yBJ4Pc0
▶️ [92/1000] Video ID: P9t9B0Pdq-8
▶️ [93/1000] Video ID: hz3CT6f9cZA
▶️ [94/1000] Video ID: _AnO4MOf3_Y
▶️ [95/1000] Video ID: SuAop2CEdjI
▶️ [96/1000] Video ID: 1xetTdMQCVI
▶️ [97/1000] Video ID: Q1ZrCKfH3k0
▶️ [98/1000] Video ID: gg2n2x6i-gI
▶️ [99/1000] Video ID: UK0yqjAfYtY
▶️ [100/1000] Video ID: cVvvWXRL9-s
▶️ [101/1000] Video ID: IK8kId4zBx8
▶️ [102/1000] Video ID: Hv0tcdmoVHc
▶️ [103/1000] Video ID: CKqx9UPb0Xs
▶️ [104/1000] Video ID: QMA-DjahwKY
▶️ [105/1000] Video ID: AiK21TpFpJA
▶️ [106/1000] Video ID: N3KAtT7kSco
▶️ [107/1000] Video ID: vGZ1gE-w9ag
▶️ [108/1000] Video ID: x1OOSJmlaQ0
▶️ [109/1000] Video ID: Vph7aySz2aM
▶️ [110/1000] Video ID: f5gGOLz9eoU
▶️ [111/1000] Video ID: JvRFFmHpUd0
▶️ [112/1000] Video ID: a1fryHvndYc
▶️ [113/1000] Video ID: tjClq_WRqhk
▶️ [114/1000] Video ID: Yy2p7zVH20A
▶️ [115/1000] Video ID: udeHknNn4JU
▶️ [116/1000] Video ID: hY6fVagZ9eA
▶️ [117/1000] Video ID: L8yaFCffiRw
▶️ [118/1000] Video ID: EiPfsAgId6M
▶️ [119/1000] Video ID: RwpyTnSdbBc
▶️ [120/1000] Video ID: Bgf5p-jGA7E
▶️ [121/1000] Video ID: NJHBmjMvgyo
▶️ [122/1000] Video ID: GkPTkd7MdwY
▶️ [123/1000] Video ID: azaLuoLjCao
▶️ [124/1000] Video ID: jzpdgCz72BA
▶️ [125/1000] Video ID: ypM_wL38RYU
▶️ [126/1000] Video ID: dTb5_rLJz18
▶️ [127/1000] Video ID: 1C7Dr7VdgYA
▶️ [128/1000] Video ID: PVdTA0ANtAw
▶️ [129/1000] Video ID: PLvsiB7z64w
▶️ [130/1000] Video ID: XqvcTb5y0Zo
▶️ [131/1000] Video ID: PVaaqF3biV4
▶️ [132/1000] Video ID: thtK-Map-Hc
▶️ [133/1000] Video ID: Mlbj0gCUd4Q
▶️ [134/1000] Video ID: yCA1EqUvLq4
▶️ [135/1000] Video ID: vGgRa9SIip0
▶️ [136/1000] Video ID: QNxIttHR9Ww
▶️ [137/1000] Video ID: 09107DTRJkY
▶️ [138/1000] Video ID: jJcixGChxpQ
▶️ [139/1000] Video ID: CMMGoOaglmo
▶️ [140/1000] Video ID: D5LDJjfR4-8
▶️ [141/1000] Video ID: uocqTo375qY
▶️ [142/1000] Video ID: Poyw2-4j4sg
▶️ [143/1000] Video ID: 5O_9KAWwq9k
▶️ [144/1000] Video ID: PC8nSLkc8Ak
▶️ [145/1000] Video ID: gogmVkGNeTM
▶️ [146/1000] Video ID: 8doQCAOydrE
▶️ [147/1000] Video ID: BrYfbXrSiWY
▶️ [148/1000] Video ID: cPdQAXudGlY
▶️ [149/1000] Video ID: VnY3wa-OenM
▶️ [150/1000] Video ID: Ph2fbFIzeB4
▶️ [151/1000] Video ID: _HxwF-xqF5A
▶️ [152/1000] Video ID: IdqW-LcBLuA
▶️ [153/1000] Video ID: vFsByTi6a64
▶️ [154/1000] Video ID: -sGYJTqGTmk
▶️ [155/1000] Video ID: hVOXBkGUjJs
▶️ [156/1000] Video ID: ctNWhXK07yM
▶️ [157/1000] Video ID: NGLesnlc5sE
▶️ [158/1000] Video ID: cQdAy_fu0gk
▶️ [159/1000] Video ID: trtk8XztUi0
▶️ [160/1000] Video ID: mLbL0k3zd4g
▶️ [161/1000] Video ID: M9JR85R0urQ
▶️ [162/1000] Video ID: mU03w56p3Yw
▶️ [163/1000] Video ID: fm6cnq2ueFI
▶️ [164/1000] Video ID: JWFBHwoD7Eo
▶️ [165/1000] Video ID: D3YBnc49XoI
▶️ [166/1000] Video ID: n-XeQz1mGyo
▶️ [167/1000] Video ID: DGr8-ud_hho
▶️ [168/1000] Video ID: AeBTUBrhr3Q
▶️ [169/1000] Video ID: TbP5_iwYb54
▶️ [170/1000] Video ID: aBQb1v7ORfg
▶️ [171/1000] Video ID: -ALmE28z7co
▶️ [172/1000] Video ID: O-VDtY2hSp8
▶️ [173/1000] Video ID: -2JzpDlGX14
▶️ [174/1000] Video ID: 6W9aHw1g-Ek
▶️ [175/1000] Video ID: e1YY3fa6vvA
▶️ [176/1000] Video ID: y4wu-uIEb64
▶️ [177/1000] Video ID: A3dKMJvxPpk
▶️ [178/1000] Video ID: 2jzdLyzP2UE
▶️ [179/1000] Video ID: eC36olSlo5U
▶️ [180/1000] Video ID: qAyZkAe0OoU
▶️ [181/1000] Video ID: Pk7ZHAWY6iU
▶️ [182/1000] Video ID: zRPTyfNB8RQ
▶️ [183/1000] Video ID: JkFYgPk6RVo
▶️ [184/1000] Video ID: vntb1j5Fa7Y
▶️ [185/1000] Video ID: f22ZpVHcKQI
▶️ [186/1000] Video ID: KPTEKad4cmU
▶️ [187/1000] Video ID: RmFJu46Wx70
▶️ [188/1000] Video ID: fvbdg43ywog
▶️ [189/1000] Video ID: XBtr6478e_Y
▶️ [190/1000] Video ID: O_n_ExEa4Z0
▶️ [191/1000] Video ID: T05LEc1lgZo
▶️ [192/1000] Video ID: pBXK0iYz-3E
▶️ [193/1000] Video ID: XleKsPmzymg
▶️ [194/1000] Video ID: YMUsv6YWVdI
▶️ [195/1000] Video ID: GN67PW0_h6g
▶️ [196/1000] Video ID: YsFCNlESV9s
▶️ [197/1000] Video ID: -ScXCHQX9gE
▶️ [198/1000] Video ID: 6JJjd6Oisxw
▶️ [199/1000] Video ID: Jq4m9BKvlI4
▶️ [200/1000] Video ID: shlBlKahpOc
▶️ [201/1000] Video ID: dqy_CyY5UMw
▶️ [202/1000] Video ID: PkkoT3ksMOA
▶️ [203/1000] Video ID: g69bEuAZKzk
▶️ [204/1000] Video ID: p0B4CO16E70
▶️ [205/1000] Video ID: _lQ5uPO8MXs
▶️ [206/1000] Video ID: 5CnbCFb2XTU
▶️ [207/1000] Video ID: u83GbNpsbYg
▶️ [208/1000] Video ID: W3gAenLafNk
▶️ [209/1000] Video ID: a2-7sHSdJzs
▶️ [210/1000] Video ID: 1TONXsgrvZ4
▶️ [211/1000] Video ID: svpAEXp1rOo
▶️ [212/1000] Video ID: OR0M-qS7l7o
▶️ [213/1000] Video ID: EGKjDdraayE
▶️ [214/1000] Video ID: SgFxWi8Oz9U
▶️ [215/1000] Video ID: KR2KW_I0b_4
▶️ [216/1000] Video ID: dudElVT1oMQ
▶️ [217/1000] Video ID: CVnZ3-0Gy3o
▶️ [218/1000] Video ID: NLi4mvL91jw
▶️ [219/1000] Video ID: xuQaLpG1VAQ
▶️ [220/1000] Video ID: yl12zZCm3kk
▶️ [221/1000] Video ID: TtOvEwCvYOo
▶️ [222/1000] Video ID: hFjqWHpxH6Q
▶️ [223/1000] Video ID: j5FB7-B9bdA
▶️ [224/1000] Video ID: ryfHXNbTNOM
▶️ [225/1000] Video ID: ST9PszMJDAc
▶️ [226/1000] Video ID: yWGVkM-oBj8
▶️ [227/1000] Video ID: KKVP-dr0DCI
▶️ [228/1000] Video ID: TxKWxJBEql4
▶️ [229/1000] Video ID: tYtt-XPwoeQ
▶️ [230/1000] Video ID: gHzz3Dzd8Do
▶️ [231/1000] Video ID: wA9ucto8lbs
▶️ [232/1000] Video ID: B5vjKpIKiSY
▶️ [233/1000] Video ID: sN_u_MiIuKA
▶️ [234/1000] Video ID: VQc4cu7n_R4
▶️ [235/1000] Video ID: wmvGP8kOJJ4
▶️ [236/1000] Video ID: lSlzWG8w3ag
▶️ [237/1000] Video ID: QruL4SRckj8
▶️ [238/1000] Video ID: dIjxkxOmGIY
▶️ [239/1000] Video ID: VXwfHrxDqiw
▶️ [240/1000] Video ID: Qd1GzyOZQPM
▶️ [241/1000] Video ID: 41wUiIgH9KI
▶️ [242/1000] Video ID: IJMkcI7Xi_g
▶️ [243/1000] Video ID: Hjbgpc9RMXU
▶️ [244/1000] Video ID: QN_SfMRggdw
▶️ [245/1000] Video ID: _1gkSbxj1qo
▶️ [246/1000] Video ID: -PfPJDkSRrE
▶️ [247/1000] Video ID: y9kAiiGWIx8
▶️ [248/1000] Video ID: IsRqO7fKX_s
▶️ [249/1000] Video ID: T61H19WcDvY
▶️ [250/1000] Video ID: x9ACQKcQRTU
▶️ [251/1000] Video ID: pwqNwd72-Ho
▶️ [252/1000] Video ID: Bu6llW7flQ8
▶️ [253/1000] Video ID: 0TQ5_Dm2q9Q
▶️ [254/1000] Video ID: 9tY7lxGeTPI
▶️ [255/1000] Video ID: J-KCNbg_hGw
▶️ [256/1000] Video ID: CPkS6ACHqUM
▶️ [257/1000] Video ID: AjeswPDwRVU
▶️ [258/1000] Video ID: 89H_XihDuI8
▶️ [259/1000] Video ID: b0rc1TDENPI
▶️ [260/1000] Video ID: b6_LwgGbuSU
▶️ [261/1000] Video ID: KbxzWeNMWEs
▶️ [262/1000] Video ID: tID7R4vpWGs
▶️ [263/1000] Video ID: vqJ3ET65qyw
▶️ [264/1000] Video ID: S8Hy3Hpu-tI
▶️ [265/1000] Video ID: JtMFVZBJAQg
▶️ [266/1000] Video ID: x9_ahULmg_8
▶️ [267/1000] Video ID: 3tWX7gyICh4
▶️ [268/1000] Video ID: 7k2k7255zZg
▶️ [269/1000] Video ID: c1OcAnTVr30
▶️ [270/1000] Video ID: WA6Nny1W64c
▶️ [271/1000] Video ID: 79N2JwkWYao
▶️ [272/1000] Video ID: oXqF3wRA5Wo
▶️ [273/1000] Video ID: yY1IUEE4Tt0
▶️ [274/1000] Video ID: md8_jnhLcuM
▶️ [275/1000] Video ID: B417E7bH_TE
▶️ [276/1000] Video ID: zNVerApHJ28
▶️ [277/1000] Video ID: O-59J6juWkE
▶️ [278/1000] Video ID: 0A5lzD0HE-8
▶️ [279/1000] Video ID: KMWMDgZsOAI
▶️ [280/1000] Video ID: 15ALSUZknmA
▶️ [281/1000] Video ID: r3tlsthrypQ
▶️ [282/1000] Video ID: sFWDV8jnbwg
▶️ [283/1000] Video ID: x6ctXLYK7ew
▶️ [284/1000] Video ID: nNbWvyfcb_g
▶️ [285/1000] Video ID: TbbsZRInCKM
▶️ [286/1000] Video ID: uPlGBX7ddJg
▶️ [287/1000] Video ID: LrvtA9g8UE0
▶️ [288/1000] Video ID: yId1tksFFlA
▶️ [289/1000] Video ID: n6sio5w7hx8
▶️ [290/1000] Video ID: 51d0Zol_C88
▶️ [291/1000] Video ID: tnMkJ21Bc1I
▶️ [292/1000] Video ID: eZPal4f6jCI
▶️ [293/1000] Video ID: M5gWjta0gIQ
▶️ [294/1000] Video ID: o-2ixBkiNYI
▶️ [295/1000] Video ID: LJHOE-hWoVU
▶️ [296/1000] Video ID: _undZQ6_Irs
▶️ [297/1000] Video ID: TEX7qSljsrs
▶️ [298/1000] Video ID: HqG_YiS68Wk
▶️ [299/1000] Video ID: BAJChMOmKOA
▶️ [300/1000] Video ID: 1vru2M5rPL8
▶️ [301/1000] Video ID: LuAlDfHBEEg
▶️ [302/1000] Video ID: ikQeIZWHq4U
▶️ [303/1000] Video ID: 7q42a-ZEeBU
▶️ [304/1000] Video ID: _ua8vL5UC40
▶️ [305/1000] Video ID: AHXe3zUNsh8
▶️ [306/1000] Video ID: gF7XpVILP4Y
▶️ [307/1000] Video ID: WJldQ8WOu2w
▶️ [308/1000] Video ID: lsl_waXRfp8
▶️ [309/1000] Video ID: ChRBMexCC90
▶️ [310/1000] Video ID: Cml9KOkKSng
▶️ [311/1000] Video ID: Jt7LyQwY07s
▶️ [312/1000] Video ID: 7yxGZYbESuI
▶️ [313/1000] Video ID: xbb6mOOpKMU
▶️ [314/1000] Video ID: udwPrpMwNkQ
▶️ [315/1000] Video ID: DNGzfZoeVGk
▶️ [316/1000] Video ID: OGLIbdr_dy4
▶️ [317/1000] Video ID: NeGBASk89bA
▶️ [318/1000] Video ID: mboD4bceZd8
▶️ [319/1000] Video ID: L2zuznqu1Vg
▶️ [320/1000] Video ID: vY3wxmn8l9I
▶️ [321/1000] Video ID: vX07aXuoLjM
▶️ [322/1000] Video ID: gS9hUpCEriU
▶️ [323/1000] Video ID: vk3r4jrowvM
▶️ [324/1000] Video ID: 2l7aK__eTWE
▶️ [325/1000] Video ID: Z9eNOO3SzEQ
▶️ [326/1000] Video ID: edcS1342naY
▶️ [327/1000] Video ID: GdNaWYyikag
▶️ [328/1000] Video ID: 3AJaPVJ-bJ8
▶️ [329/1000] Video ID: B_0CftymBRU
▶️ [330/1000] Video ID: a03g4-_vAIA
▶️ [331/1000] Video ID: Nx7hKgIUjcM
▶️ [332/1000] Video ID: hyF0C_eFCis
▶️ [333/1000] Video ID: VUTVdhwU0OM
▶️ [334/1000] Video ID: yYQP2aRJ4BU
▶️ [335/1000] Video ID: QwwzHOgp7O8
▶️ [336/1000] Video ID: HcU98c4pa7A
▶️ [337/1000] Video ID: _26MHSzwaE8
▶️ [338/1000] Video ID: cWAShuFovBU
▶️ [339/1000] Video ID: DQayarrt4L0
▶️ [340/1000] Video ID: gQVOu44FOHQ
▶️ [341/1000] Video ID: Gt66h90KNuQ
▶️ [342/1000] Video ID: Coc65YbxWRU
▶️ [343/1000] Video ID: ktY9-iCCLzA
▶️ [344/1000] Video ID: i2R0GsZze6c
▶️ [345/1000] Video ID: 7TmWWMllgOU
▶️ [346/1000] Video ID: j1NoG5Ep1VA
▶️ [347/1000] Video ID: 2lQAAQB_ULY
▶️ [348/1000] Video ID: fjhVmO15NpI
▶️ [349/1000] Video ID: Gc3hxygzyUM
▶️ [350/1000] Video ID: 7Ju-qT6ebh8
▶️ [351/1000] Video ID: 3uzScvH5mF8
▶️ [352/1000] Video ID: QWZJdRXR4Ig
▶️ [353/1000] Video ID: BqNA1PeBGAM
▶️ [354/1000] Video ID: 7OvEGiDOmUU
▶️ [355/1000] Video ID: 6pPQc-T43_A
▶️ [356/1000] Video ID: n45kqyN3i-A
▶️ [357/1000] Video ID: GAQVNu0iwZI
▶️ [358/1000] Video ID: vzD06yNLXAg
▶️ [359/1000] Video ID: 1sexsIBnApg
▶️ [360/1000] Video ID: 2Uuj5Fi2j1w
▶️ [361/1000] Video ID: S86_EAsBokU
▶️ [362/1000] Video ID: CIBKCxDyJEk
▶️ [363/1000] Video ID: bnuTm6PoO48
▶️ [364/1000] Video ID: 0wcaJKW4y9Y
▶️ [365/1000] Video ID: RxMHSrM5Fww
▶️ [366/1000] Video ID: ZpuCV41iszc
▶️ [367/1000] Video ID: UwtZ5P5AqSA
▶️ [368/1000] Video ID: YNcN5pRPn0U
▶️ [369/1000] Video ID: CmNlI7Hyp3Y
▶️ [370/1000] Video ID: xJ6OwXtCock
▶️ [371/1000] Video ID: nnuX8z-JYVw
▶️ [372/1000] Video ID: CYQvP1MamHc
▶️ [373/1000] Video ID: G5GAD6WMkKo
▶️ [374/1000] Video ID: Tn02HZ5jBWI
▶️ [375/1000] Video ID: JZTZu3aVXeA
▶️ [376/1000] Video ID: aGOfpXcIBmg
▶️ [377/1000] Video ID: lJmGrzNKT-E
▶️ [378/1000] Video ID: IZU-a_jTn6s
▶️ [379/1000] Video ID: n9Q-7Hp-khE
▶️ [380/1000] Video ID: 33IyFNCnmfc
▶️ [381/1000] Video ID: r4x8dHs3LT8
▶️ [382/1000] Video ID: v7JA5lgnyjo
▶️ [383/1000] Video ID: iwzaqCmS5rc
▶️ [384/1000] Video ID: oD-9WGAAgF4
▶️ [385/1000] Video ID: IK6TacT4VKg
▶️ [386/1000] Video ID: OSs0EXUp9VU
▶️ [387/1000] Video ID: Q0kKLsdXFZI
▶️ [388/1000] Video ID: ESStvlwQOvY
▶️ [389/1000] Video ID: yd1rgDcJq88
▶️ [390/1000] Video ID: TFrf_DSRb8E
▶️ [391/1000] Video ID: BeGc_LwyMTA
▶️ [392/1000] Video ID: 45KmP3voPYk
▶️ [393/1000] Video ID: Q_9PBCRhVqU
▶️ [394/1000] Video ID: KPDniL4cTEI
▶️ [395/1000] Video ID: 1khZdPNtp4Y
▶️ [396/1000] Video ID: y5PIuQ6twto
▶️ [397/1000] Video ID: XOpQ8sJrr0U
▶️ [398/1000] Video ID: Kk2CiJYGsfc
▶️ [399/1000] Video ID: 6oNiBawzRsk
▶️ [400/1000] Video ID: dU9VCyuvDBg
▶️ [401/1000] Video ID: J3whfjWPlu8
▶️ [402/1000] Video ID: 2HbXd7H8ggQ
▶️ [403/1000] Video ID: 3fUL3sS3vms
▶️ [404/1000] Video ID: zF_kGz7jPiI
▶️ [405/1000] Video ID: i_t-IhgaEdI
▶️ [406/1000] Video ID: tzkQpTdQ7JU
▶️ [407/1000] Video ID: CiDY11Sny6A
▶️ [408/1000] Video ID: nWEoeXyw5no
▶️ [409/1000] Video ID: wvYSaCEvFz0
▶️ [410/1000] Video ID: bp-8sv4fXiA
▶️ [411/1000] Video ID: bH1jNuZqUxA
▶️ [412/1000] Video ID: DpNCszals0s
▶️ [413/1000] Video ID: FM-zjWGegGE
▶️ [414/1000] Video ID: vVNy58nn2Pk
▶️ [415/1000] Video ID: XoBd0bLSR0c
▶️ [416/1000] Video ID: sLXzgR6-_b0
▶️ [417/1000] Video ID: T99wS_L7j0I
▶️ [418/1000] Video ID: IdeYtvGnkbQ
▶️ [419/1000] Video ID: J_JKrsMdYfw
▶️ [420/1000] Video ID: Fp4SoPqRjYo
▶️ [421/1000] Video ID: LuSw_FgoRbc
▶️ [422/1000] Video ID: t8KLMns3wKo
▶️ [423/1000] Video ID: a5VgUqlnbZg
▶️ [424/1000] Video ID: ni_5GDqgg7E
▶️ [425/1000] Video ID: q3xa9L_HU24
▶️ [426/1000] Video ID: aj2ZCIauHTg
▶️ [427/1000] Video ID: 8aYWtlW8k0k
▶️ [428/1000] Video ID: 06EjkT87NFM
▶️ [429/1000] Video ID: r-gRiDk9ARE
▶️ [430/1000] Video ID: U0z_AccnzSQ
▶️ [431/1000] Video ID: 4N9S-qa3oh0
▶️ [432/1000] Video ID: Aat65Y7eHhM
▶️ [433/1000] Video ID: K4dG7-6-heg
▶️ [434/1000] Video ID: wZYloS2KbUQ
▶️ [435/1000] Video ID: oapUuhJkmdw
▶️ [436/1000] Video ID: 3D-n6qPjLmw
▶️ [437/1000] Video ID: nXpu0nOoKUg
▶️ [438/1000] Video ID: EDjGGwTMoDc
▶️ [439/1000] Video ID: IDjHCINBPKY
▶️ [440/1000] Video ID: swF7vpLzwZ4
▶️ [441/1000] Video ID: 5jq7HMtizFg
▶️ [442/1000] Video ID: Zvt4KqCXKTs
▶️ [443/1000] Video ID: 5tRLrqVg-24
▶️ [444/1000] Video ID: vRXUMfdsGOg
▶️ [445/1000] Video ID: Bb9Z35oeaew
▶️ [446/1000] Video ID: PaE_nLG6B3Q
▶️ [447/1000] Video ID: 65-RYp85o0A
▶️ [448/1000] Video ID: wdbt2mMvGew
▶️ [449/1000] Video ID: b7_RtRW7tyM
▶️ [450/1000] Video ID: 4V-myrFvP_0
▶️ [451/1000] Video ID: teN6E1tPe2c
▶️ [452/1000] Video ID: WERhJBAw3H8
▶️ [453/1000] Video ID: CEveHvgWvts
▶️ [454/1000] Video ID: d-4mEWErX9g
▶️ [455/1000] Video ID: 7gXbF6pemQA
▶️ [456/1000] Video ID: oSed-JpZM8M
▶️ [457/1000] Video ID: Dou1MtOsu0U
▶️ [458/1000] Video ID: xfdk-1pu_rU
▶️ [459/1000] Video ID: tlP-wp4X1pY
▶️ [460/1000] Video ID: nJoAg9yJZ7w
▶️ [461/1000] Video ID: EU49Z3wEj5Y
▶️ [462/1000] Video ID: tax80FLFxsE
▶️ [463/1000] Video ID: Kqr1kDhT39o
▶️ [464/1000] Video ID: l07LrpMPcjs
▶️ [465/1000] Video ID: okIChuvBt1Y
▶️ [466/1000] Video ID: Q63MEsDWg1s
▶️ [467/1000] Video ID: _uuTFXXLgNg
▶️ [468/1000] Video ID: z5dmnSCiRj0
▶️ [469/1000] Video ID: nXcrjUnbUrU
▶️ [470/1000] Video ID: KOnkIEOuLZA
▶️ [471/1000] Video ID: BHUTgYRSwCs
▶️ [472/1000] Video ID: AdIBQCjKji4
▶️ [473/1000] Video ID: 7KNBqUQExI0
▶️ [474/1000] Video ID: Bi0r2WFfRVA
▶️ [475/1000] Video ID: rSi5oLc_sFI
▶️ [476/1000] Video ID: JKMKMBcNpm8
▶️ [477/1000] Video ID: -8Ea37i_aWw
▶️ [478/1000] Video ID: Nch-4HUrFNk
▶️ [479/1000] Video ID: z0rOKIjWDRA
▶️ [480/1000] Video ID: _AAot5X_aDw
▶️ [481/1000] Video ID: er-rKRLjvhw
▶️ [482/1000] Video ID: HXnPXZqxZ2M
▶️ [483/1000] Video ID: NJh8zhOBbrU
▶️ [484/1000] Video ID: fNOyTU1WIdM
▶️ [485/1000] Video ID: oVCeFFvDvOE
▶️ [486/1000] Video ID: s9U0bWlrKmw
▶️ [487/1000] Video ID: U76FbvA3i1E
▶️ [488/1000] Video ID: rCDFD4Vh-us
▶️ [489/1000] Video ID: fBEyFvtbPdQ
▶️ [490/1000] Video ID: JFgbrGZmTK4
▶️ [491/1000] Video ID: ZZxzkeYJcLE
▶️ [492/1000] Video ID: NqKK5SLZDw8
▶️ [493/1000] Video ID: O7h0DwR2N00
▶️ [494/1000] Video ID: ct3XyBGr6Bs
▶️ [495/1000] Video ID: QdWJPjmBTtA
▶️ [496/1000] Video ID: 8nBXeqiXq78
▶️ [497/1000] Video ID: TGnlxv-JTR0
▶️ [498/1000] Video ID: uNDow38_rUQ
▶️ [499/1000] Video ID: wrIqXciKYI4
▶️ [500/1000] Video ID: cVkIeLSbIEY
▶️ [501/1000] Video ID: 8AbLWEbR_sk
▶️ [502/1000] Video ID: 1BbcdBRpybw
▶️ [503/1000] Video ID: -JWZK4hweYc
▶️ [504/1000] Video ID: Rm3budGTVpA
▶️ [505/1000] Video ID: BIuYK4x3G2E
▶️ [506/1000] Video ID: 8xVz5t7FmKI
▶️ [507/1000] Video ID: 4d_Bvv3_zvQ
▶️ [508/1000] Video ID: EE5yWtfgrKc
▶️ [509/1000] Video ID: lA6OIkFPK6s
▶️ [510/1000] Video ID: CK8Vucx865U
▶️ [511/1000] Video ID: koYNf5Z3EyI
▶️ [512/1000] Video ID: RxGFI5McXUI
▶️ [513/1000] Video ID: roQ6riH6z6o
▶️ [514/1000] Video ID: t0lM1q3iRAY
▶️ [515/1000] Video ID: RmUTjiaHP9k
▶️ [516/1000] Video ID: cLS7LKQIJZs
▶️ [517/1000] Video ID: Z4xAYilZZio
▶️ [518/1000] Video ID: 7DL8ydG3ZjA
▶️ [519/1000] Video ID: sHmArYAcvMM
▶️ [520/1000] Video ID: 4Uy5Sl17Y5k
▶️ [521/1000] Video ID: V2CRFdxCddE
▶️ [522/1000] Video ID: 1rMWRQvUg7I
▶️ [523/1000] Video ID: 2IDM7y65xjU
▶️ [524/1000] Video ID: 9BYpZTbyHTU
▶️ [525/1000] Video ID: 7RLUTz0wKOY
▶️ [526/1000] Video ID: grZU8CstMIU
▶️ [527/1000] Video ID: SrTq7-hmbxc
▶️ [528/1000] Video ID: 5Kzu_aZlfIc
▶️ [529/1000] Video ID: VJA1np0OVW0
▶️ [530/1000] Video ID: 9shz5knzXVI
▶️ [531/1000] Video ID: odPMvsKD0hI
▶️ [532/1000] Video ID: HQsebeO058I
▶️ [533/1000] Video ID: PwEVkpWxcnI
▶️ [534/1000] Video ID: PFIx-OofO1Q
▶️ [535/1000] Video ID: u22F5uvASnc
▶️ [536/1000] Video ID: UPAAvvhY6ls
▶️ [537/1000] Video ID: 2xZ31QsmdKs
▶️ [538/1000] Video ID: JQoPfmm6RmI
▶️ [539/1000] Video ID: xfnHGaN6i94
▶️ [540/1000] Video ID: rI8kOh0wX00
▶️ [541/1000] Video ID: iBOyvS23OB4
▶️ [542/1000] Video ID: 9_-JdCz0rgM
▶️ [543/1000] Video ID: vNtJrPZrWQ4
▶️ [544/1000] Video ID: 2U9SHbaOR2c
▶️ [545/1000] Video ID: gfxClxFgzDA
▶️ [546/1000] Video ID: rcDNvgh0Wwo
▶️ [547/1000] Video ID: X0JS6H8_R3g
▶️ [548/1000] Video ID: HZvaEFwCY_k
▶️ [549/1000] Video ID: qXSfcUH2B0o
▶️ [550/1000] Video ID: aRRUEHxXbBc
▶️ [551/1000] Video ID: zQZ5uuW6cfE
▶️ [552/1000] Video ID: lPMafSFW-Xg
▶️ [553/1000] Video ID: jLM3ZVtxH0o
▶️ [554/1000] Video ID: YoZRIVxDECo
▶️ [555/1000] Video ID: FK2uweAgpPw
▶️ [556/1000] Video ID: ktgGzjj-DIQ

# Paris FC

In [ ]:
from googleapiclient.discovery import build
import time
import pandas as pd

API_KEY = 'AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ'  # Replace with your actual API key
youtube = build('youtube', 'v3', developerKey=API_KEY)

def get_channel_id_from_url(url):
    if '@' in url:
        handle = url.split('@')[1]
        res = youtube.search().list(
            q=handle,
            type='channel',
            maxResults=1,
            part='snippet'
        ).execute()
        if res['items']:
            return res['items'][0]['snippet']['channelId']
    return None

def get_uploads_playlist_id(channel_id):
    res = youtube.channels().list(
        part='contentDetails',
        id=channel_id
    ).execute()
    if res['items']:
        return res['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    return None

def get_recent_video_ids(playlist_id, count):
    video_ids = []
    next_page_token = None

    while len(video_ids) < count:
        res = youtube.playlistItems().list(
            playlistId=playlist_id,
            part='contentDetails',
            maxResults=50,
            pageToken=next_page_token
        ).execute()

        for item in res['items']:
            video_ids.append(item['contentDetails']['videoId'])
            if len(video_ids) >= count:
                break

        next_page_token = res.get('nextPageToken')
        if not next_page_token:
            break

    return video_ids

def get_top_level_comments(video_id, max_comments=None):
    comments = []
    next_page_token = None

    while True:
        try:
            res = youtube.commentThreads().list(
                part='snippet',
                videoId=video_id,
                maxResults=100,
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in res['items']:
                snippet = item['snippet']['topLevelComment']['snippet']
                comments.append({
                    'Commenter Name': snippet['authorDisplayName'],
                    'Comment': snippet['textDisplay'],
                    'Comment Like Count': snippet['likeCount']
                })

                if max_comments and len(comments) >= max_comments:
                    return comments

            next_page_token = res.get('nextPageToken')
            if not next_page_token:
                break

        except Exception as e:
            print(f"Error fetching comments for video {video_id}: {e}")
            break

        time.sleep(0.5)

    return comments

def get_video_metadata(video_id):
    res = youtube.videos().list(
        part='snippet,statistics',
        id=video_id
    ).execute()

    if not res['items']:
        return None

    item = res['items'][0]
    return {
        'Video ID': video_id,
        'Video Title': item['snippet']['title'],
        'View Count': item['statistics'].get('viewCount'),
        'Like Count': item['statistics'].get('likeCount'),
        'Comment Count': item['statistics'].get('commentCount'),
        'YouTube Channel': item['snippet']['channelTitle']
    }

def collect_all_comments(channel_url, num_videos, output_filename):
    channel_id = get_channel_id_from_url(channel_url)
    if not channel_id:
        print(f"❌ Could not find channel ID from URL: {channel_url}")
        return

    playlist_id = get_uploads_playlist_id(channel_id)
    video_ids = get_recent_video_ids(playlist_id, num_videos)
    print(f"📺 Processing {len(video_ids)} videos from {channel_url}")

    all_comments = []

    for i, vid in enumerate(video_ids, 1):
        print(f"▶️ [{i}/{len(video_ids)}] Video ID: {vid}")
        video_meta = get_video_metadata(vid)
        if not video_meta:
            continue

        comments = get_top_level_comments(vid)
        for c in comments:
            all_comments.append({
                'Video Title': video_meta['Video Title'],
                'Like Count': video_meta['Like Count'],
                'View Count': video_meta['View Count'],
                'Comment Count': video_meta['Comment Count'],
                'Commenter Name': c['Commenter Name'],
                'Comment': c['Comment'],
                'Comment Like Count': c['Comment Like Count'],
                'YouTube Channel': video_meta['YouTube Channel']
            })

        time.sleep(1)

    df = pd.DataFrame(all_comments)
    df.to_csv(output_filename, index=False, encoding='utf-8-sig')
    print(f"💾 Saved {len(all_comments)} comments to: {output_filename}")

if __name__ == '__main__':
    paris_url = "https://www.youtube.com/@parisfc"
    collect_all_comments(paris_url, num_videos=500, output_filename="parisfc.csv")

📺 Processing 500 videos from https://www.youtube.com/@parisfc
▶️ [1/500] Video ID: uCltqhymDdc
▶️ [2/500] Video ID: F75Ml44F7H8
▶️ [3/500] Video ID: XORiQpwPw94
▶️ [4/500] Video ID: MyLOWTvQ2lY
▶️ [5/500] Video ID: D_n6XozxJdU
▶️ [6/500] Video ID: ObJd5MGdvBI
▶️ [7/500] Video ID: 96b0HhunqOE
▶️ [8/500] Video ID: tVNaUGx075A
▶️ [9/500] Video ID: b7nrE_bExlA
▶️ [10/500] Video ID: 1AzDN6PgaYQ
▶️ [11/500] Video ID: -JRSvBK6tH4
▶️ [12/500] Video ID: RIErIOGT9FU
▶️ [13/500] Video ID: doTBDFXB4Jg
▶️ [14/500] Video ID: -4rdV6Cxgag
▶️ [15/500] Video ID: aCx2VXtzrYQ
▶️ [16/500] Video ID: bYYdM4HPq3g
▶️ [17/500] Video ID: pGZHc1gcGOo
▶️ [18/500] Video ID: 5-ncHmyeajk
▶️ [19/500] Video ID: mrma9d8qpOQ
▶️ [20/500] Video ID: -_fBOPDxKEg
▶️ [21/500] Video ID: bphXZGisJL0
▶️ [22/500] Video ID: Z6vjDhDOn2Q
▶️ [23/500] Video ID: 00BCoQlTWSY
▶️ [24/500] Video ID: tRMIahHD2yw
▶️ [25/500] Video ID: SfM6zBO7caM
▶️ [26/500] Video ID: aPOYiZSShl4
▶️ [27/500] Video ID: eaje-86-jdg
▶️ [28/500] Video ID: EjDZ0juYfrI
▶️ [29/500] Video ID: vdSpaLJk1hM
▶️ [30/500] Video ID: CSgaqcrLSxE
▶️ [31/500] Video ID: 22ofTkSbE34
▶️ [32/500] Video ID: iX4GwTa9_n8
▶️ [33/500] Video ID: Cq3fj2oX4E8
▶️ [34/500] Video ID: _H9tbTt7anE
▶️ [35/500] Video ID: 1gHvWTagL5M
▶️ [36/500] Video ID: HaFhpNfhnSE
▶️ [37/500] Video ID: EqBld3VzSKg
▶️ [38/500] Video ID: f3BgMo5b6jA
▶️ [39/500] Video ID: Fso-S2YJhHk
▶️ [40/500] Video ID: HYZXrDqlHoU
▶️ [41/500] Video ID: GirEiXDvcEs
▶️ [42/500] Video ID: L1_AfYlBRi4
▶️ [43/500] Video ID: ZChyWMX7YOA
▶️ [44/500] Video ID: t_zF3KYgRP8
▶️ [45/500] Video ID: oOxSPK5aJDw
▶️ [46/500] Video ID: mhSyEFi8jOg
▶️ [47/500] Video ID: N3xf1cbc5mE
▶️ [48/500] Video ID: 8SDGCWud11s
▶️ [49/500] Video ID: llKeYpbNzss
▶️ [50/500] Video ID: rFMqjn9Zf9c
▶️ [51/500] Video ID: 5bMd2moRmik
▶️ [52/500] Video ID: EdfSMmLl9k4
▶️ [53/500] Video ID: oKgFM7O8xyg
▶️ [54/500] Video ID: mm818eWBYp4
▶️ [55/500] Video ID: _PRpuPnO-nE
▶️ [56/500] Video ID: y-jqWsSM7aY
▶️ [57/500] Video ID: T2LxE207rP4
▶️ [58/500] Video ID: xhZ5EDbiQ74
▶️ [59/500] Video ID: wR-qLQphNao
▶️ [60/500] Video ID: 5tt5u8yi_Mw
▶️ [61/500] Video ID: jIMY-GAfHPw
▶️ [62/500] Video ID: 1_kLeeT0UAQ
▶️ [63/500] Video ID: Wj_GEiaZ4S4
▶️ [64/500] Video ID: em9nzaBtfcM
▶️ [65/500] Video ID: q4Ie_K_HzJY
▶️ [66/500] Video ID: -PoVw6UccVc
▶️ [67/500] Video ID: 9xJgQOTND2Y
▶️ [68/500] Video ID: mi6SUUxuiCU
▶️ [69/500] Video ID: pLobbbjhDrA
▶️ [70/500] Video ID: fSPKxfIRtm8
▶️ [71/500] Video ID: pCTsuC2TWC4
▶️ [72/500] Video ID: cGye8ZujgIA
▶️ [73/500] Video ID: _CyLw32Isi4
▶️ [74/500] Video ID: 6nedQuL4Q3U
▶️ [75/500] Video ID: Uzk5Oid5Qzk
▶️ [76/500] Video ID: 4ca-ZS9GqqA
▶️ [77/500] Video ID: -jWL9Tn8aGI
▶️ [78/500] Video ID: D2e5O3-JYoA
▶️ [79/500] Video ID: qXMxrD0cOvU
▶️ [80/500] Video ID: QLZMyIGEC0o
▶️ [81/500] Video ID: SA2G0YdD2bw
▶️ [82/500] Video ID: JWHbjNb7lX4
▶️ [83/500] Video ID: PxEnZcALoWc
▶️ [84/500] Video ID: Y1N6UAfJwok
▶️ [85/500] Video ID: uejuCH3A7S0
▶️ [86/500] Video ID: sWnvJPmA61Y
▶️ [87/500] Video ID: u_FO3dDN_sk
▶️ [88/500] Video ID: RZwrrIrdc-c
▶️ [89/500] Video ID: GpDZ91DHr3g
▶️ [90/500] Video ID: kGBpIn8bxgA
▶️ [91/500] Video ID: pHVrKNzrudw
▶️ [92/500] Video ID: -59P04BFkp8
▶️ [93/500] Video ID: ej6Thhg9qdg
▶️ [94/500] Video ID: SCktRSJbxOE
▶️ [95/500] Video ID: YNjVdRRONxE
▶️ [96/500] Video ID: cZ21M3HXGVk
▶️ [97/500] Video ID: RK85gequHgw
▶️ [98/500] Video ID: xhGFaKxHxGo
▶️ [99/500] Video ID: 1xFDqcrq1S8
▶️ [100/500] Video ID: 2JIbt9O_BCE
▶️ [101/500] Video ID: GGl88CPNh3o
▶️ [102/500] Video ID: dxqrcnjq8Lg
▶️ [103/500] Video ID: 8QPm5qDMy5U
▶️ [104/500] Video ID: 6mIrkJttTW0
▶️ [105/500] Video ID: GxfQeVzms5I
▶️ [106/500] Video ID: BbM9zHkHCI8
▶️ [107/500] Video ID: 1F82QbonnSo
▶️ [108/500] Video ID: PaKXrVEemZ0
▶️ [109/500] Video ID: VCyhll3Jeg0
▶️ [110/500] Video ID: oPjfvFvgtY0
▶️ [111/500] Video ID: R9lhPdWla28
▶️ [112/500] Video ID: k6SihjftGLc
▶️ [113/500] Video ID: Tm3bmshkQdk
▶️ [114/500] Video ID: udnRsmMn-LQ
▶️ [115/500] Video ID: CPM4XXTbAMY
▶️ [116/500] Video ID: z07tGffZuXg
▶️ [117/500] Video ID: EV_Mx_PJ9fY
▶️ [118/500] Video ID: FTwifTtYeiM
▶️ [119/500] Video ID: IXO-RkbMylk
▶️ [120/500] Video ID: sVy_KXYbHOk
▶️ [121/500] Video ID: SP4g89KqtAk
▶️ [122/500] Video ID: p3NpSmxw3lE
▶️ [123/500] Video ID: pzBe55KFTNA
▶️ [124/500] Video ID: KTGL5Abki54
▶️ [125/500] Video ID: Cso2pb-YCug
▶️ [126/500] Video ID: TaBXGOymySg
▶️ [127/500] Video ID: l6mZ4dn8ZgY
▶️ [128/500] Video ID: Q5i6E3CITKI
▶️ [129/500] Video ID: NvCGaH7NH6A
▶️ [130/500] Video ID: buerBJ-8LWQ
▶️ [131/500] Video ID: 8D9wRwlwyuM
▶️ [132/500] Video ID: 0L0hHCOhbo4
▶️ [133/500] Video ID: tOxqPEddnJA
▶️ [134/500] Video ID: aU1gUHwhsfg
▶️ [135/500] Video ID: F7CtQJU1QrM
▶️ [136/500] Video ID: 35Df1kmkwqk
▶️ [137/500] Video ID: Zh-7IOd5vrA
▶️ [138/500] Video ID: 1kWtn86LbDc
Error fetching comments for video 1kWtn86LbDc: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=1kWtn86LbDc&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [139/500] Video ID: lpSVjhX4mFg
▶️ [140/500] Video ID: HBgBVXjkHW4
▶️ [141/500] Video ID: yHZ1QkmJaf8
▶️ [142/500] Video ID: Q8Qv0XkMOAQ
▶️ [143/500] Video ID: cvUrTZShbXU
Error fetching comments for video cvUrTZShbXU: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=cvUrTZShbXU&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [144/500] Video ID: wHrhYJGKUa0
▶️ [145/500] Video ID: VFN5Mo6nQRM
▶️ [146/500] Video ID: 4D4Ey7sZjho
▶️ [147/500] Video ID: O41ra-FGQtc
▶️ [148/500] Video ID: zNIGplG1OBI
▶️ [149/500] Video ID: -s1z052O5oY
▶️ [150/500] Video ID: iIPCCb9pySA
▶️ [151/500] Video ID: EAahjZTeDf4
▶️ [152/500] Video ID: -e4iXRbm2Lc
▶️ [153/500] Video ID: -Wl2yu9tzEE
▶️ [154/500] Video ID: T5aPfJbTp8s
▶️ [155/500] Video ID: bulDBiu1xOA
▶️ [156/500] Video ID: cj4-hHtUAVA
▶️ [157/500] Video ID: lHe4b1a0B2c
Error fetching comments for video lHe4b1a0B2c: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=lHe4b1a0B2c&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [158/500] Video ID: BhWWsG9YrcE
▶️ [159/500] Video ID: 9U0ZPbUGqKs
▶️ [160/500] Video ID: 6lkCsc5NneU
▶️ [161/500] Video ID: NQahmn3vA7w
▶️ [162/500] Video ID: nWDNCemIR18
Error fetching comments for video nWDNCemIR18: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=nWDNCemIR18&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [163/500] Video ID: EWmI6RwZxA4
▶️ [164/500] Video ID: CEecYkQr62s
Error fetching comments for video CEecYkQr62s: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=CEecYkQr62s&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [165/500] Video ID: nN7AN_yukzg
▶️ [166/500] Video ID: uZZz9TsgpCs
▶️ [167/500] Video ID: E24wiJuwqss
▶️ [168/500] Video ID: sA-twkbZ2Ws
▶️ [169/500] Video ID: wMaah88JbF8
▶️ [170/500] Video ID: GS56R-nzD8g
▶️ [171/500] Video ID: BtIZFbJedbU
▶️ [172/500] Video ID: XESEchjKlMc
▶️ [173/500] Video ID: TL2z94gmUoU
▶️ [174/500] Video ID: VN60-I0P6kU
▶️ [175/500] Video ID: tNa4389tBe8
▶️ [176/500] Video ID: HzR0sO2ojTA
▶️ [177/500] Video ID: BpIZ9W2eDso
▶️ [178/500] Video ID: LlJa8iwoFiY
▶️ [179/500] Video ID: XRDpPBvL5Ic
▶️ [180/500] Video ID: ulz9QSon2kY
▶️ [181/500] Video ID: gPM_QHt2nZU
▶️ [182/500] Video ID: mNYgGmNmvN4
▶️ [183/500] Video ID: j5ib2LNV9Zo
▶️ [184/500] Video ID: 0Yc7JyOyNDI
▶️ [185/500] Video ID: gXvCetD4asM
▶️ [186/500] Video ID: 4isVDYKA0VY
▶️ [187/500] Video ID: Pbt5W_N2_z8
▶️ [188/500] Video ID: D_cU_VKkAFw
▶️ [189/500] Video ID: mXvBEjCFHT4
▶️ [190/500] Video ID: DwfXfFFHSXA
▶️ [191/500] Video ID: tsp7-DeOaIQ
▶️ [192/500] Video ID: NfAmH7EGbnI
▶️ [193/500] Video ID: o_QPaArs30I
▶️ [194/500] Video ID: KtsmPn9CJkk
▶️ [195/500] Video ID: zvNOB60vDHU
▶️ [196/500] Video ID: I0WBsph28mM
▶️ [197/500] Video ID: 9gXR-gi9cnk
▶️ [198/500] Video ID: jjFV4oZXar4
▶️ [199/500] Video ID: EwIjBKeYBV8
▶️ [200/500] Video ID: 4vIl6Vv0Z24
▶️ [201/500] Video ID: Bwhxm5n3V28
▶️ [202/500] Video ID: 78GWveUo8jc
▶️ [203/500] Video ID: a186I1yHZVE
▶️ [204/500] Video ID: xIuFd3Dxd-k
▶️ [205/500] Video ID: INcEBqEwkwY
▶️ [206/500] Video ID: Gx398dh06GQ
▶️ [207/500] Video ID: 9TM_hL8k9aw
▶️ [208/500] Video ID: 1B5icti00uI
▶️ [209/500] Video ID: Kou9QVBSxy8
▶️ [210/500] Video ID: bhdfbFIZbk4
▶️ [211/500] Video ID: XFO9hGbPm-c
▶️ [212/500] Video ID: allVGEVTqS4
▶️ [213/500] Video ID: Hm-2pR5Qorc
▶️ [214/500] Video ID: UDlmRhnO_HY
▶️ [215/500] Video ID: _yIqgoDDUw0
▶️ [216/500] Video ID: MuXXH7JpY34
▶️ [217/500] Video ID: SdrvMzbi3fE
▶️ [218/500] Video ID: R8ehXBoF2gU
▶️ [219/500] Video ID: 1rHmJZlc2Ao
▶️ [220/500] Video ID: -vtt7qK80CQ
▶️ [221/500] Video ID: e8oTOfF8Cj0
▶️ [222/500] Video ID: eJvwP4mVbAs
▶️ [223/500] Video ID: E7UBy01Y8Ow
▶️ [224/500] Video ID: HW2SfCC7i6Y
▶️ [225/500] Video ID: MMOhb7lnLh4
▶️ [226/500] Video ID: CZpMPXcPuPw
▶️ [227/500] Video ID: g_IMsrt8EXU
▶️ [228/500] Video ID: t7zOdm3O3LM
▶️ [229/500] Video ID: VAYxsk0dvkU
▶️ [230/500] Video ID: W1DEza509zE
▶️ [231/500] Video ID: tzbmt0WkrN8
▶️ [232/500] Video ID: ll9f9WQURQg
▶️ [233/500] Video ID: 47Q6YIwDT9I
▶️ [234/500] Video ID: L2jg6U12E3U
▶️ [235/500] Video ID: Ay3uPe7QohI
▶️ [236/500] Video ID: Aa9Y60NTlEk
▶️ [237/500] Video ID: bm4_D4yDVfk
▶️ [238/500] Video ID: YwmotCzshII
▶️ [239/500] Video ID: Ap0-uKlJkXU
▶️ [240/500] Video ID: oI7dr_jS3A4
▶️ [241/500] Video ID: _xOPkxQkP1c
▶️ [242/500] Video ID: em7KIEfrQJs
▶️ [243/500] Video ID: IZctKtP8QhA
▶️ [244/500] Video ID: 3cysHfgKGRI
▶️ [245/500] Video ID: ezJ6FyiBQx4
▶️ [246/500] Video ID: YQ8nhSHYCdo
▶️ [247/500] Video ID: a_RgbOcP4HM
▶️ [248/500] Video ID: JlkvbgRlQrM
▶️ [249/500] Video ID: ohi9-HgOvtQ
▶️ [250/500] Video ID: mVIPydOEku4
▶️ [251/500] Video ID: _4foy3bAsfA
▶️ [252/500] Video ID: szMvuGFso5w
▶️ [253/500] Video ID: v-iYoEJI1JU
▶️ [254/500] Video ID: 9lS8oFV6SAk
▶️ [255/500] Video ID: ujwsznNMht4
▶️ [256/500] Video ID: qaZwPIjH7cg
▶️ [257/500] Video ID: agevox_ndbk
▶️ [258/500] Video ID: qSeC_rHsywQ
▶️ [259/500] Video ID: iSphEYDJLIU
▶️ [260/500] Video ID: XU42Sva5ypM
▶️ [261/500] Video ID: aGU-cCP5lhI
▶️ [262/500] Video ID: cRrh1Yqz4BU
▶️ [263/500] Video ID: iww65fcrwV8
▶️ [264/500] Video ID: kbQu2xqQSKg
▶️ [265/500] Video ID: qUrL-Bi9eyY
▶️ [266/500] Video ID: ZZ10ZYDoyxc
▶️ [267/500] Video ID: CCnd4EnNy1k
▶️ [268/500] Video ID: tfF5hszVFTM
▶️ [269/500] Video ID: _BrUa685kFs
▶️ [270/500] Video ID: CBr8zCLl218
▶️ [271/500] Video ID: u0nEoPl8idM
▶️ [272/500] Video ID: nd66TsnEzjc
▶️ [273/500] Video ID: _SnPLTvc0r4
▶️ [274/500] Video ID: c4nk8_CHVTI
▶️ [275/500] Video ID: r0M6485Woko
▶️ [276/500] Video ID: IB9WhxCyXHQ
▶️ [277/500] Video ID: BVrlQ_nQoWY
▶️ [278/500] Video ID: Ur_UqC0O16M
▶️ [279/500] Video ID: j2AHvAA7DGY
▶️ [280/500] Video ID: WhqdmDXAxNo
▶️ [281/500] Video ID: zd5o8pjviV0
▶️ [282/500] Video ID: 0d7DuuZrKwk
▶️ [283/500] Video ID: gK-t58m4GKE
▶️ [284/500] Video ID: gOKXgNEkkEE
▶️ [285/500] Video ID: w3JQDUPmQFc
▶️ [286/500] Video ID: qSmsX9mws4o
▶️ [287/500] Video ID: OHJF4VhOBhE
▶️ [288/500] Video ID: cHS-Kyw_lrs
▶️ [289/500] Video ID: gyHmHn6oaqw
▶️ [290/500] Video ID: NOrfeB3mCO4
▶️ [291/500] Video ID: LeG8ck82Yoo
▶️ [292/500] Video ID: -eO9thb16ns
▶️ [293/500] Video ID: CzZ5bCi2Drk
▶️ [294/500] Video ID: vH90YBlbCf4
▶️ [295/500] Video ID: TJFhorutR8s
▶️ [296/500] Video ID: BLm-gyv2MWg
▶️ [297/500] Video ID: cRpmg9_-_hM
▶️ [298/500] Video ID: PdzbDfGKG90
▶️ [299/500] Video ID: pUPu0BnX8pE
▶️ [300/500] Video ID: ge20n7VOgXM
▶️ [301/500] Video ID: tKoRvlvo4ec
▶️ [302/500] Video ID: zcsAlUv_uAI
▶️ [303/500] Video ID: j6N43vzgwTg
▶️ [304/500] Video ID: 53DH_uPs6NE
▶️ [305/500] Video ID: qerWSlsBQjk
▶️ [306/500] Video ID: MexcmrbRUyo
▶️ [307/500] Video ID: zNDIaDFqd1Y
▶️ [308/500] Video ID: _QxomJaxGt0
▶️ [309/500] Video ID: UZbkAsQ1zq4
▶️ [310/500] Video ID: 6Xhin65Egag
▶️ [311/500] Video ID: foYDseRxLw4
▶️ [312/500] Video ID: uzHr7CBRZuw
▶️ [313/500] Video ID: JXVGom4wARI
▶️ [314/500] Video ID: 8tE7xW0y8z8
Error fetching comments for video 8tE7xW0y8z8: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=8tE7xW0y8z8&maxResults=100&textFormat=plainText&key=AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
▶️ [315/500] Video ID: cdLOarxATLQ
▶️ [316/500] Video ID: wMl6YeCF3o0
▶️ [317/500] Video ID: pUrIK-4KAcs
▶️ [318/500] Video ID: hs-DpT56l0s
▶️ [319/500] Video ID: 0uCo1pV38g4
▶️ [320/500] Video ID: w8Umi-t_NtE
▶️ [321/500] Video ID: GQoE6KW6kSA
▶️ [322/500] Video ID: lT0umfletvE
▶️ [323/500] Video ID: Usaa8-ip-N4
▶️ [324/500] Video ID: QxG6hejeVPQ
▶️ [325/500] Video ID: _0Y_p5ND_gU
▶️ [326/500] Video ID: FEzhcPbfKP8
▶️ [327/500] Video ID: OmOo0vfKrXw
▶️ [328/500] Video ID: uW7fvMD_Z70
▶️ [329/500] Video ID: 8K9S4Wl2KcY
▶️ [330/500] Video ID: rQV1hX4qef0
▶️ [331/500] Video ID: ahOKKJZ_3CM
▶️ [332/500] Video ID: T6SG8b0dfuQ
▶️ [333/500] Video ID: Q26b2D-z8d0
▶️ [334/500] Video ID: 66hfErj2c8M
▶️ [335/500] Video ID: eNC-hiELJ5c
▶️ [336/500] Video ID: dI0YQruIj7c
▶️ [337/500] Video ID: sT3S0eTiOmM
▶️ [338/500] Video ID: V5IQJ4n2sgo
▶️ [339/500] Video ID: GmUxezKCm5o
▶️ [340/500] Video ID: DOHoBbRDuq8
▶️ [341/500] Video ID: a7BoMcumy2o
▶️ [342/500] Video ID: WHSTuWDro7g
▶️ [343/500] Video ID: prn7vS5kwbQ
▶️ [344/500] Video ID: 4Glnn7hHmsw
▶️ [345/500] Video ID: _Ag8_h8avqs
▶️ [346/500] Video ID: V4-LyOsqz-0
▶️ [347/500] Video ID: X5QTnfYVQnw
▶️ [348/500] Video ID: 8Vs1R6W1Ho8
▶️ [349/500] Video ID: 6qexST82dJ0
▶️ [350/500] Video ID: CSYrmCEE-KU
▶️ [351/500] Video ID: wIpyfUe-DNU
▶️ [352/500] Video ID: oNKIBPpHD1Y
▶️ [353/500] Video ID: rDvSk8Zhf8I
▶️ [354/500] Video ID: 5ezQWup6JsM
▶️ [355/500] Video ID: KlNfLmQeolA
▶️ [356/500] Video ID: mdFrc6Rlpac
▶️ [357/500] Video ID: ZMr2ozlINr0
▶️ [358/500] Video ID: _Feg_GpqE_4
▶️ [359/500] Video ID: bKRmnfyNfFA
▶️ [360/500] Video ID: MZ_OjKuNsMw
▶️ [361/500] Video ID: LLlRMObZ4BE
▶️ [362/500] Video ID: OLCD93OMHPs
▶️ [363/500] Video ID: VxeDoQ_abTM
▶️ [364/500] Video ID: XvLioeXWVUg
▶️ [365/500] Video ID: zVJ2uUzeLts
▶️ [366/500] Video ID: RXRZhWsLqhw
▶️ [367/500] Video ID: ZBfT1rjtiHU
▶️ [368/500] Video ID: v_6wgSqVBAw
▶️ [369/500] Video ID: _Z4SenVR81Q
▶️ [370/500] Video ID: SYyehsC58q8
▶️ [371/500] Video ID: 6Mgg_9gTAh4
▶️ [372/500] Video ID: X0oFpxLuJ2E
▶️ [373/500] Video ID: ua8agIHAY8E
▶️ [374/500] Video ID: SqRl11UsG6Y
▶️ [375/500] Video ID: HagPCXFQYqk
▶️ [376/500] Video ID: 6ulsM3IkNaA
▶️ [377/500] Video ID: -Ck9jRBL2KE
▶️ [378/500] Video ID: WGtH8cajy1k
▶️ [379/500] Video ID: 4kjfWPtKIqY
▶️ [380/500] Video ID: TiFxpqkakOA
▶️ [381/500] Video ID: flpvoeFNCbU
▶️ [382/500] Video ID: g96m7z8ZIkY
▶️ [383/500] Video ID: 9j1j1XbYmP8
▶️ [384/500] Video ID: ZMGUcKliWVg
▶️ [385/500] Video ID: wF6TLW448Xw
▶️ [386/500] Video ID: tuxPjrhLPJY
▶️ [387/500] Video ID: qzrm4t_uB8k
▶️ [388/500] Video ID: SY9nVrbyVI4
▶️ [389/500] Video ID: se67nMsIlJ8
▶️ [390/500] Video ID: EszcKDbnAAg
▶️ [391/500] Video ID: HAhPvYQGkHw
▶️ [392/500] Video ID: tx-oEOKU6mo
▶️ [393/500] Video ID: Gdr1bpluUhg
▶️ [394/500] Video ID: uolh45ce6Wk
▶️ [395/500] Video ID: 5tb5t2D48m8
▶️ [396/500] Video ID: 8F-dFKnso5o
▶️ [397/500] Video ID: DNlODHeYS98
▶️ [398/500] Video ID: pUsZtZA78qU
▶️ [399/500] Video ID: IVF7kLX7N7M
▶️ [400/500] Video ID: 2Wgn21J3sBs
▶️ [401/500] Video ID: GPfmz9rcF9w
▶️ [402/500] Video ID: Dh9tdrny5zw
▶️ [403/500] Video ID: IM_s8iaQ740
▶️ [404/500] Video ID: kc40xrQ8yZw
▶️ [405/500] Video ID: 9Y7BnWQtSQ4
▶️ [406/500] Video ID: PGdm--k1VFo
▶️ [407/500] Video ID: 3j3un_acehE
▶️ [408/500] Video ID: Aj_ARFK9ft8
▶️ [409/500] Video ID: vbiK1TJlmBE
▶️ [410/500] Video ID: opr0aEuvqyw
▶️ [411/500] Video ID: 75PCHoCNwHw
▶️ [412/500] Video ID: 38tH36VzmnM
▶️ [413/500] Video ID: cmZDjZLuon0
▶️ [414/500] Video ID: ewlQpgwKxuQ
▶️ [415/500] Video ID: koZ1Bz6vN-U
▶️ [416/500] Video ID: oxzLcaKRDtw
▶️ [417/500] Video ID: jxSgqLM1nWs
▶️ [418/500] Video ID: oQTBua_1e3U
▶️ [419/500] Video ID: GM8Me_7EVio
▶️ [420/500] Video ID: vaWrOtByHfE
▶️ [421/500] Video ID: sKwr8JdhEtA
▶️ [422/500] Video ID: NqdYtyImRKE
▶️ [423/500] Video ID: JUuR0cjNZ-4
▶️ [424/500] Video ID: EQqCKqlKLyk
▶️ [425/500] Video ID: 5CFG_nshqwQ
▶️ [426/500] Video ID: x5f2PNUtOfg
▶️ [427/500] Video ID: 0wbOYuXmk_E
▶️ [428/500] Video ID: hTop0OAykI8
▶️ [429/500] Video ID: e_7a2KJBWKg
▶️ [430/500] Video ID: V54k7OMReh0
▶️ [431/500] Video ID: yaBs55XRMK8
▶️ [432/500] Video ID: tyxDyeV2e_U
▶️ [433/500] Video ID: H-dFF3pbom4
▶️ [434/500] Video ID: umFLgt751Uw
▶️ [435/500] Video ID: issnPtFcoY8
▶️ [436/500] Video ID: AHTeMEK5Lf8
▶️ [437/500] Video ID: 1k8OXo3Z_7E
▶️ [438/500] Video ID: ov4BGx_wDeA
▶️ [439/500] Video ID: TSx_3vYjtnM
▶️ [440/500] Video ID: z6QA1PAz1SA
▶️ [441/500] Video ID: BxYdpXQItI0

# Corinthians

In [ ]:
from googleapiclient.discovery import build
import time
import pandas as pd

API_KEY = 'AIzaSyDyoZ13tvOSmoLKy_tPb3r06EQ89KdthQQ'  # Replace with your actual API key
youtube = build('youtube', 'v3', developerKey=API_KEY)

def get_channel_id_from_url(url):
    if '@' in url:
        handle = url.split('@')[1]
        res = youtube.search().list(
            q=handle,
            type='channel',
            maxResults=1,
            part='snippet'
        ).execute()
        if res['items']:
            return res['items'][0]['snippet']['channelId']
    return None

def get_uploads_playlist_id(channel_id):
    res = youtube.channels().list(
        part='contentDetails',
        id=channel_id
    ).execute()
    if res['items']:
        return res['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    return None

def get_recent_video_ids(playlist_id, count):
    video_ids = []
    next_page_token = None

    while len(video_ids) < count:
        res = youtube.playlistItems().list(
            playlistId=playlist_id,
            part='contentDetails',
            maxResults=50,
            pageToken=next_page_token
        ).execute()

        for item in res['items']:
            video_ids.append(item['contentDetails']['videoId'])
            if len(video_ids) >= count:
                break

        next_page_token = res.get('nextPageToken')
        if not next_page_token:
            break

    return video_ids

def get_top_level_comments(video_id, max_comments=None):
    comments = []
    next_page_token = None

    while True:
        try:
            res = youtube.commentThreads().list(
                part='snippet',
                videoId=video_id,
                maxResults=100,
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in res['items']:
                snippet = item['snippet']['topLevelComment']['snippet']
                comments.append({
                    'Commenter Name': snippet['authorDisplayName'],
                    'Comment': snippet['textDisplay'],
                    'Comment Like Count': snippet['likeCount']
                })

                if max_comments and len(comments) >= max_comments:
                    return comments

            next_page_token = res.get('nextPageToken')
            if not next_page_token:
                break

        except Exception as e:
            print(f"Error fetching comments for video {video_id}: {e}")
            break

        time.sleep(0.5)

    return comments

def get_video_metadata(video_id):
    res = youtube.videos().list(
        part='snippet,statistics',
        id=video_id
    ).execute()

    if not res['items']:
        return None

    item = res['items'][0]
    return {
        'Video ID': video_id,
        'Video Title': item['snippet']['title'],
        'View Count': item['statistics'].get('viewCount'),
        'Like Count': item['statistics'].get('likeCount'),
        'Comment Count': item['statistics'].get('commentCount'),
        'YouTube Channel': item['snippet']['channelTitle']
    }

def collect_all_comments(channel_url, num_videos, output_filename):
    channel_id = get_channel_id_from_url(channel_url)
    if not channel_id:
        print(f"❌ Could not find channel ID from URL: {channel_url}")
        return

    playlist_id = get_uploads_playlist_id(channel_id)
    video_ids = get_recent_video_ids(playlist_id, num_videos)
    print(f"📺 Processing {len(video_ids)} videos from {channel_url}")

    all_comments = []

    for i, vid in enumerate(video_ids, 1):
        print(f"▶️ [{i}/{len(video_ids)}] Video ID: {vid}")
        video_meta = get_video_metadata(vid)
        if not video_meta:
            continue

        comments = get_top_level_comments(vid)
        for c in comments:
            all_comments.append({
                'Video Title': video_meta['Video Title'],
                'Like Count': video_meta['Like Count'],
                'View Count': video_meta['View Count'],
                'Comment Count': video_meta['Comment Count'],
                'Commenter Name': c['Commenter Name'],
                'Comment': c['Comment'],
                'Comment Like Count': c['Comment Like Count'],
                'YouTube Channel': video_meta['YouTube Channel']
            })

        time.sleep(1)

    df = pd.DataFrame(all_comments)
    df.to_csv(output_filename, index=False, encoding='utf-8-sig')
    print(f"💾 Saved {len(all_comments)} comments to: {output_filename}")

if __name__ == '__main__':
    cor_url = "https://www.youtube.com/@corinthians"
    collect_all_comments(cor_url, num_videos=1000, output_filename="corinthians.csv")

📺 Processing 1000 videos from https://www.youtube.com/@corinthians
▶️ [1/1000] Video ID: rMUhuAUKHpg
▶️ [2/1000] Video ID: FK74s_-zDEA
▶️ [3/1000] Video ID: AspmwTwCGE4
▶️ [4/1000] Video ID: v1-FFw1_5io
▶️ [5/1000] Video ID: Fq-QDbgyn3o
▶️ [6/1000] Video ID: b34ZadPIUBI
▶️ [7/1000] Video ID: WOE2So8WbQ4
▶️ [8/1000] Video ID: XkgkfZRkzts
▶️ [9/1000] Video ID: ABJordhsLnk
▶️ [10/1000] Video ID: Pcje9T-IL_4
▶️ [11/1000] Video ID: 2BSsPlyxdLI
▶️ [12/1000] Video ID: 6ECJ_fjSr18
▶️ [13/1000] Video ID: bmVg0HATWIU
▶️ [14/1000] Video ID: ANgHyMPpmb4
▶️ [15/1000] Video ID: mnddk6iRHA0
▶️ [16/1000] Video ID: BQchSOZaNrE
▶️ [17/1000] Video ID: BF8uJ3YXG9o
▶️ [18/1000] Video ID: glkFTG1c_5M
▶️ [19/1000] Video ID: D0TCe2Dt70U
▶️ [20/1000] Video ID: R8Yc0x2BM7Q
▶️ [21/1000] Video ID: SAskM0a42Xk
▶️ [22/1000] Video ID: O7tNnWHYFLU
▶️ [23/1000] Video ID: FkY65_eUwQ8
▶️ [24/1000] Video ID: siWeSoRViSk
▶️ [25/1000] Video ID: 4ZQe0p2AWak
▶️ [26/1000] Video ID: rhHsYU2zrPc
▶️ [27/1000] Video ID: vmGRHYeZq7w
▶️ [28/1000] Video ID: 5e5XJoNXyOE
▶️ [29/1000] Video ID: exlzu6otLcs
▶️ [30/1000] Video ID: w-Y5KQUJ7TA
▶️ [31/1000] Video ID: WnNWMP5azlY
▶️ [32/1000] Video ID: ohF3JFv4BRk
▶️ [33/1000] Video ID: ycFdsWAVu8A
▶️ [34/1000] Video ID: vneNjcZasXA
▶️ [35/1000] Video ID: w3BW44TplxA
▶️ [36/1000] Video ID: 9ZK130t8gJ8
▶️ [37/1000] Video ID: qYZeqbYYKUI
▶️ [38/1000] Video ID: FarIPS5_hx8
▶️ [39/1000] Video ID: RiEfmCfQm0k
▶️ [40/1000] Video ID: zwuMnYzOi_w
▶️ [41/1000] Video ID: EFospMvELCY
▶️ [42/1000] Video ID: JnXXETZmaoo
▶️ [43/1000] Video ID: 7cuc7IQyq9Q
▶️ [44/1000] Video ID: sOwzOPsqvqU
▶️ [45/1000] Video ID: 9DGxs6wl3Zg
▶️ [46/1000] Video ID: 0o2PSk3jF8s
▶️ [47/1000] Video ID: lPMyCkjPLCM
▶️ [48/1000] Video ID: 2uSRTGMgWNs
▶️ [49/1000] Video ID: rIIsBfD86Ng
▶️ [50/1000] Video ID: EfIek3mtcPM
▶️ [51/1000] Video ID: OtTeqL6FIwQ
▶️ [52/1000] Video ID: hDracGpitUY
▶️ [53/1000] Video ID: OiTZa9_F6fE
▶️ [54/1000] Video ID: qlqftksGzLQ
▶️ [55/1000] Video ID: 01v-6Joenas
▶️ [56/1000] Video ID: 2y3OWopCrP8
▶️ [57/1000] Video ID: cwY1Sav0itY
▶️ [58/1000] Video ID: e89tCY34KQs
▶️ [59/1000] Video ID: 0KFuoIgO4ls
▶️ [60/1000] Video ID: SiyCNQOrhTE
▶️ [61/1000] Video ID: ELcI_iCpKfg
▶️ [62/1000] Video ID: 7hymgWeXIr8
▶️ [63/1000] Video ID: Cx8uyHxToLY
▶️ [64/1000] Video ID: HbeNRwpCHVY
▶️ [65/1000] Video ID: rYjfR-u9490
▶️ [66/1000] Video ID: yVhuachrvH8
▶️ [67/1000] Video ID: civQNQeS_Ro
▶️ [68/1000] Video ID: 128LY_-J3PI
▶️ [69/1000] Video ID: 6WSlQhvsNc0
▶️ [70/1000] Video ID: zCI2e2celnI
▶️ [71/1000] Video ID: eBcjkgYrx50
▶️ [72/1000] Video ID: maXKub3J44M
▶️ [73/1000] Video ID: 4phfkhJin9Q
▶️ [74/1000] Video ID: IH24CYfQCeI
▶️ [75/1000] Video ID: x29W8VvihLw
▶️ [76/1000] Video ID: VcvJKNtZyik
▶️ [77/1000] Video ID: PGsIu-PKRFQ
▶️ [78/1000] Video ID: DfCBmm0QBM4
▶️ [79/1000] Video ID: J8hoiiJ2vxs
▶️ [80/1000] Video ID: B0Xnv0KpZZA
▶️ [81/1000] Video ID: pL36OgAjslw
▶️ [82/1000] Video ID: ESjj-2jJL8k
▶️ [83/1000] Video ID: GrnniBDq5XY
▶️ [84/1000] Video ID: ZQOO_mLe2hE
▶️ [85/1000] Video ID: PPz2iRYnoCo
▶️ [86/1000] Video ID: 0VYcnDVP2c0
▶️ [87/1000] Video ID: xpzIFTvE6lo
▶️ [88/1000] Video ID: 25n8oYvLdzI
▶️ [89/1000] Video ID: 3OKMvdyLwoU
▶️ [90/1000] Video ID: 5WLiPGaAdYw
▶️ [91/1000] Video ID: pn0PQX60ppQ
▶️ [92/1000] Video ID: t7wtw47kxmI
▶️ [93/1000] Video ID: __EmfwNgTss
▶️ [94/1000] Video ID: NuWvedlFANw
▶️ [95/1000] Video ID: O24ePkFxdn8
▶️ [96/1000] Video ID: P0p7eNr2Ne4
▶️ [97/1000] Video ID: Sk1FVGd8RQA
▶️ [98/1000] Video ID: UcL-2Y1Fyn4
▶️ [99/1000] Video ID: XgJ1HdqrWXU
▶️ [100/1000] Video ID: hyVbuVfcrB8
▶️ [101/1000] Video ID: ov9nMFAi0ng
▶️ [102/1000] Video ID: r0dsf3BLNyo
▶️ [103/1000] Video ID: AMy1yJzvre8
▶️ [104/1000] Video ID: e3bzg1Oq1CM
▶️ [105/1000] Video ID: HPqhudlh8GM
▶️ [106/1000] Video ID: Ag9nFqTvzTU
▶️ [107/1000] Video ID: K7uH7CWcU3s
▶️ [108/1000] Video ID: 0dS5BsW7zxk
▶️ [109/1000] Video ID: bQpsqAhhr1Y
▶️ [110/1000] Video ID: yJ-iXMZL6pI
▶️ [111/1000] Video ID: YZ3YPPjbnVk
▶️ [112/1000] Video ID: 27JEt4j5fd0
▶️ [113/1000] Video ID: fzTQ9f0jkmc
▶️ [114/1000] Video ID: GPjmtaa4oqE
▶️ [115/1000] Video ID: 0XPV8Ih0ozs
▶️ [116/1000] Video ID: pVufrj2E2RE
▶️ [117/1000] Video ID: Jor6UVo7Djc
▶️ [118/1000] Video ID: FVLwDawys80
▶️ [119/1000] Video ID: MlZ7XeYn4Hs
▶️ [120/1000] Video ID: Juy24xSIFF8
▶️ [121/1000] Video ID: uuO3tGxYbkA
▶️ [122/1000] Video ID: rdQFS2meiBs
▶️ [123/1000] Video ID: 1Ca8CXhZVGU
▶️ [124/1000] Video ID: -JWtLr65mR8
▶️ [125/1000] Video ID: uus7NT-MDes
▶️ [126/1000] Video ID: w9FEIbCQ1aE
▶️ [127/1000] Video ID: sW1KfLb8bM4
▶️ [128/1000] Video ID: yiR4e2AZ6Xw
▶️ [129/1000] Video ID: 7w-A-FLfEQc
▶️ [130/1000] Video ID: jBDC4kluBT4
▶️ [131/1000] Video ID: lsdX5rSUnfo
▶️ [132/1000] Video ID: f82bVqOm0T4
▶️ [133/1000] Video ID: ryhh3eVEzoI
▶️ [134/1000] Video ID: Qe4znC2KdYc
▶️ [135/1000] Video ID: FFgHRTjokHE
▶️ [136/1000] Video ID: 1OBjH6nu7-U
▶️ [137/1000] Video ID: BQgqiaeoj4w
▶️ [138/1000] Video ID: CHM1WRQiCRc
▶️ [139/1000] Video ID: MLmJ7eNPVxo
▶️ [140/1000] Video ID: u6FjcAvVTsI
▶️ [141/1000] Video ID: rH60m51DxIg
▶️ [142/1000] Video ID: P7PSFOYC4gM
▶️ [143/1000] Video ID: nS1SPrbkr3w
▶️ [144/1000] Video ID: j74147q9WpU
▶️ [145/1000] Video ID: groU80YxVtQ
▶️ [146/1000] Video ID: 2sJAfx2TV1Y
▶️ [147/1000] Video ID: 754E89mdoMY
▶️ [148/1000] Video ID: QtRnxsTse9w
▶️ [149/1000] Video ID: 3FcTRNFc-t0
▶️ [150/1000] Video ID: EtznLGnW91Q
▶️ [151/1000] Video ID: _Xm4GDDr1O8
▶️ [152/1000] Video ID: vLuHBIgfsoE
▶️ [153/1000] Video ID: Yu3LbO3ZUmo
▶️ [154/1000] Video ID: llqp0D2W2rU
▶️ [155/1000] Video ID: loavOTOOq7c
▶️ [156/1000] Video ID: kU8ja-TdWnk
▶️ [157/1000] Video ID: j-2f3rUe5YQ
▶️ [158/1000] Video ID: ZPFIEp5sBgE
▶️ [159/1000] Video ID: 9vcOA5JxPqk
▶️ [160/1000] Video ID: JIv9UXMozJA
▶️ [161/1000] Video ID: a1gRXer2JpQ
▶️ [162/1000] Video ID: ouhXBp4TVq8
▶️ [163/1000] Video ID: eaStvEqiIV0
▶️ [164/1000] Video ID: R7cauUbt8sU
▶️ [165/1000] Video ID: xUz5xE9XoyQ
▶️ [166/1000] Video ID: zNLDxZ18FCY
▶️ [167/1000] Video ID: Ne2wtG5dCRA
▶️ [168/1000] Video ID: d5gd1K2Y0oQ
▶️ [169/1000] Video ID: 7iibJFbxnLA
▶️ [170/1000] Video ID: yjrNuGWv28Q
▶️ [171/1000] Video ID: _rW_IKTkj_g
▶️ [172/1000] Video ID: WgCT2PwQEGE
▶️ [173/1000] Video ID: c6IE8Op470M
▶️ [174/1000] Video ID: ihnH7V_5pyI
▶️ [175/1000] Video ID: 0RvjiC_UPtQ
▶️ [176/1000] Video ID: d-y6G5CAkRE
▶️ [177/1000] Video ID: xy3z4FsiSAo
▶️ [178/1000] Video ID: U3ne8G63JU0
▶️ [179/1000] Video ID: Jm88Qmcb-gg
▶️ [180/1000] Video ID: rFdDxaMHI1s
▶️ [181/1000] Video ID: IZWYoC1CUIs
▶️ [182/1000] Video ID: zUT7DuaNGiI
▶️ [183/1000] Video ID: IW0qnVM0C7I
▶️ [184/1000] Video ID: fQ1xFncJEXg
▶️ [185/1000] Video ID: VQJ83Q8pX_A
▶️ [186/1000] Video ID: BDxGyvuXyvg
▶️ [187/1000] Video ID: TJDFAQqrhf4
▶️ [188/1000] Video ID: zKl8c0d4imQ
▶️ [189/1000] Video ID: l4rvF68uu6Y
▶️ [190/1000] Video ID: M3u3hISLxW4
▶️ [191/1000] Video ID: cENBMlDS1Rw
▶️ [192/1000] Video ID: YTeZOBF5cT0
▶️ [193/1000] Video ID: Pge_Nioevpc
▶️ [194/1000] Video ID: SZquKGNzwL0
▶️ [195/1000] Video ID: sWX7YkkKyh4
▶️ [196/1000] Video ID: 1x2_2vAKyXk
▶️ [197/1000] Video ID: Ofl-4xVgoTE
▶️ [198/1000] Video ID: Pg-wTn68BiM
▶️ [199/1000] Video ID: IknKoCOJfVc
▶️ [200/1000] Video ID: 5FjPEZ6tauk
▶️ [201/1000] Video ID: 6oHNUzrGczE
▶️ [202/1000] Video ID: 317dq1jwyRU
▶️ [203/1000] Video ID: lo1TMKQ-XGc
▶️ [204/1000] Video ID: wusQhqlUYHY
▶️ [205/1000] Video ID: Tsd9LNH-qb8
▶️ [206/1000] Video ID: W3upjggDan0
▶️ [207/1000] Video ID: jmWASA9R22s
▶️ [208/1000] Video ID: Pn_XSM29zxU
▶️ [209/1000] Video ID: C47FTJ3Lt6Q
▶️ [210/1000] Video ID: jsEtoDihW5w
▶️ [211/1000] Video ID: d8dV4fvWbTY
▶️ [212/1000] Video ID: qpHdyCwMoi4
▶️ [213/1000] Video ID: ihMvx2AuHAA
▶️ [214/1000] Video ID: XIM0h_2DaS0
▶️ [215/1000] Video ID: gYEMOPzLxAc
▶️ [216/1000] Video ID: WkIN8ub7Vyw
▶️ [217/1000] Video ID: 19hBbq0Ja8Q
▶️ [218/1000] Video ID: acYIiuUGDcA
▶️ [219/1000] Video ID: X4nr5kFUFhg
▶️ [220/1000] Video ID: Kxd6TXIMs5Q
▶️ [221/1000] Video ID: iOw6Tyw8d7M
▶️ [222/1000] Video ID: sVSvFkpXpPU
▶️ [223/1000] Video ID: FDqTOkcqgH4
▶️ [224/1000] Video ID: TGg7aGnx6HA
▶️ [225/1000] Video ID: NkjIQ4IvtGQ
▶️ [226/1000] Video ID: g6hXerHWcIA
▶️ [227/1000] Video ID: S2po1BU4vbg
▶️ [228/1000] Video ID: xKtOl8pIx0I
▶️ [229/1000] Video ID: yKryQQszV2g
▶️ [230/1000] Video ID: V7Ac7YwV4XA
▶️ [231/1000] Video ID: Pvrur5SDWKs
▶️ [232/1000] Video ID: jDJkJIrUI3E
▶️ [233/1000] Video ID: I6bztxr8V9M
▶️ [234/1000] Video ID: 0YJBk3W_uh0
▶️ [235/1000] Video ID: -dE78ZQ1gTI
▶️ [236/1000] Video ID: AW6I-U5M_QM
▶️ [237/1000] Video ID: XSclMT152uE
▶️ [238/1000] Video ID: vbx6fQ133JI
▶️ [239/1000] Video ID: eMDtkqxW16M
▶️ [240/1000] Video ID: qdH516pSM1Y
▶️ [241/1000] Video ID: 6wJ-hmHD75g
▶️ [242/1000] Video ID: C-gPNcyhgPk
▶️ [243/1000] Video ID: bWOPbi2a01M
▶️ [244/1000] Video ID: QVw5Ux-toZs
▶️ [245/1000] Video ID: dhRSzHPJjB8
▶️ [246/1000] Video ID: Uq1I5XLoGGk
▶️ [247/1000] Video ID: N3KAewpJ8yk
▶️ [248/1000] Video ID: V-32JyqO7pM
▶️ [249/1000] Video ID: he2BkUhf37s
▶️ [250/1000] Video ID: otyUiScwwy4
▶️ [251/1000] Video ID: 2t_GKSEnlkA
▶️ [252/1000] Video ID: T5l-A2L6cUk
▶️ [253/1000] Video ID: AmIKnoYBF8s
▶️ [254/1000] Video ID: LysM34Lc4_8
▶️ [255/1000] Video ID: Nvg1tvrB1Xc
▶️ [256/1000] Video ID: E2Y0ptJuk8Q
▶️ [257/1000] Video ID: XjYPyIVHQo4
▶️ [258/1000] Video ID: kkPcbLERjWY
▶️ [259/1000] Video ID: mE4WWDtsClY
▶️ [260/1000] Video ID: bND3FF4qNyk
▶️ [261/1000] Video ID: yfGI9VUcWhc
▶️ [262/1000] Video ID: 1c35DVTgG30
▶️ [263/1000] Video ID: hzwgwJTnaZA
▶️ [264/1000] Video ID: acoTE1LlxiI
▶️ [265/1000] Video ID: 5tG26nF6LxY
▶️ [266/1000] Video ID: wcwVjeJIKdQ
▶️ [267/1000] Video ID: H5-Pu03E1Sw
▶️ [268/1000] Video ID: C42Pf8eziQw
▶️ [269/1000] Video ID: kuey9KKwc2E
▶️ [270/1000] Video ID: iEyROGDsrak
▶️ [271/1000] Video ID: TU-A32qioLI
▶️ [272/1000] Video ID: fjs8n-MUCUk
▶️ [273/1000] Video ID: EYN1QrvuNlw
▶️ [274/1000] Video ID: Tj_vPkggvk4
▶️ [275/1000] Video ID: UUqeqVXWdXE
▶️ [276/1000] Video ID: TxADxu5Zulc
▶️ [277/1000] Video ID: TiDOSUhXeq0
▶️ [278/1000] Video ID: hj0crTUDLno
▶️ [279/1000] Video ID: H0msxqHbTYk
▶️ [280/1000] Video ID: RNhgibKxIWY
▶️ [281/1000] Video ID: 6ly7bgqI8Oc
▶️ [282/1000] Video ID: rg-o2RRUNC4
▶️ [283/1000] Video ID: TExqnLhq8Fo
▶️ [284/1000] Video ID: mESdNistNL8
▶️ [285/1000] Video ID: f00MrKV3B_A
▶️ [286/1000] Video ID: bCgKMArhwAY
▶️ [287/1000] Video ID: as3x_zTXYh0
▶️ [288/1000] Video ID: EXjMQb5NNow
▶️ [289/1000] Video ID: KWylab-GWco
▶️ [290/1000] Video ID: yQyD2AH9IQ8
▶️ [291/1000] Video ID: tTaxSAcYUPc
▶️ [292/1000] Video ID: 7KM2s6QU4mE
▶️ [293/1000] Video ID: IyfJtnQ8KC8
▶️ [294/1000] Video ID: Rk474bHlIOE
▶️ [295/1000] Video ID: Exh6_u3Lkpk
▶️ [296/1000] Video ID: GDsVqMpjCPg
▶️ [297/1000] Video ID: NTiGjmU2ltw
▶️ [298/1000] Video ID: kTuu8oyE0uM
▶️ [299/1000] Video ID: scsVnXYLSB4
▶️ [300/1000] Video ID: JzlGZEiznSg
▶️ [301/1000] Video ID: wyDcJOIOA2Y
▶️ [302/1000] Video ID: cdXhhVFBVC4
▶️ [303/1000] Video ID: b7zVVT4dCeA
▶️ [304/1000] Video ID: JlUuY4ROkCg
▶️ [305/1000] Video ID: mYffUMHSjpg
▶️ [306/1000] Video ID: bb8b5uJzzuY
▶️ [307/1000] Video ID: ooevBNTttm8
▶️ [308/1000] Video ID: Fe3S3_obiJI
▶️ [309/1000] Video ID: _JLp_ZF-LYM
▶️ [310/1000] Video ID: UN_421K1iis
▶️ [311/1000] Video ID: DJsi9ZDtAnQ
▶️ [312/1000] Video ID: vfEN7XkRqdo
▶️ [313/1000] Video ID: J4CCk-KkMLo
▶️ [314/1000] Video ID: v_rDoXs-Qpc
▶️ [315/1000] Video ID: dTf9W1WtPPI
▶️ [316/1000] Video ID: 20hqXEqGJUc
▶️ [317/1000] Video ID: NtFP1lEWUmY
▶️ [318/1000] Video ID: TlSo0_pIWq8
▶️ [319/1000] Video ID: LY5Nw2wywSU
▶️ [320/1000] Video ID: IELhH-5KcVc
▶️ [321/1000] Video ID: FIij47MzVpY
▶️ [322/1000] Video ID: qpGCQB08HV8
▶️ [323/1000] Video ID: 3Dmog03XrLc
▶️ [324/1000] Video ID: 160KraIQjJE
▶️ [325/1000] Video ID: j5o82WF3PYY
▶️ [326/1000] Video ID: 3ca0iO2_iQw
▶️ [327/1000] Video ID: bDjrX6ol1H8
▶️ [328/1000] Video ID: HnW77PHJrzA
▶️ [329/1000] Video ID: yNfZv6FgcXU
▶️ [330/1000] Video ID: -eI6ROozVHg
▶️ [331/1000] Video ID: uK9HAv6ypUI
▶️ [332/1000] Video ID: JlXvL5Uhrm4
▶️ [333/1000] Video ID: JN35NybsXRs
▶️ [334/1000] Video ID: W74WUOwC7CU
▶️ [335/1000] Video ID: bqi2Y6bsQxk
▶️ [336/1000] Video ID: CS9-cC0tRGQ
▶️ [337/1000] Video ID: meNRkdi2dTg
▶️ [338/1000] Video ID: zw_3NtQZ6p4
▶️ [339/1000] Video ID: tbLfUnLY2_M
▶️ [340/1000] Video ID: CHPL4GfVDJk
▶️ [341/1000] Video ID: ONWq-xaq2co
▶️ [342/1000] Video ID: 6n0J6s4ShLI
▶️ [343/1000] Video ID: KBx8w_7wCHU
▶️ [344/1000] Video ID: MSQcDzupEd0
▶️ [345/1000] Video ID: Uv17i9X3fTU
▶️ [346/1000] Video ID: DSvD1n8bTR4
▶️ [347/1000] Video ID: ZjhNnCwHpnE
▶️ [348/1000] Video ID: WvT1wRNk9r8
▶️ [349/1000] Video ID: s7G7BNbPLXg
▶️ [350/1000] Video ID: ylOGhHKGiIQ
▶️ [351/1000] Video ID: rrtxpgT3VCM
▶️ [352/1000] Video ID: AzEByDDX4-g
▶️ [353/1000] Video ID: m8IBAGljNaE
▶️ [354/1000] Video ID: lNY5BCGqEI0
▶️ [355/1000] Video ID: xeu1ZQyTrgg
▶️ [356/1000] Video ID: QvmCgiMQ5YY
▶️ [357/1000] Video ID: 8amMjt-DExA
▶️ [358/1000] Video ID: rNr4BAA9S_0
▶️ [359/1000] Video ID: 22GWsIxiGS4
▶️ [360/1000] Video ID: MV9btObLvNI
▶️ [361/1000] Video ID: KgcCTjq5myQ
▶️ [362/1000] Video ID: 65sqjVvD0RQ
▶️ [363/1000] Video ID: IKspx4sDFxA
▶️ [364/1000] Video ID: AJdveW06mZ0
▶️ [365/1000] Video ID: zjPiYHwx5P8
▶️ [366/1000] Video ID: iByU-Q8VJY4
▶️ [367/1000] Video ID: DaOaJa7Dsdk
▶️ [368/1000] Video ID: oC_POnRayfk
▶️ [369/1000] Video ID: XKNUG0GKzX4
▶️ [370/1000] Video ID: lZ6T0bCy_28
▶️ [371/1000] Video ID: 7xsX4RSrcHo
▶️ [372/1000] Video ID: 5VVB6PSJ1r4
▶️ [373/1000] Video ID: pSzGbXtp04w
▶️ [374/1000] Video ID: xmioHKtl4ec
▶️ [375/1000] Video ID: _0KUMeGtmnQ
▶️ [376/1000] Video ID: NeHHQaHqHOo
▶️ [377/1000] Video ID: x8EM-uoO49Y
▶️ [378/1000] Video ID: 0A_SHkGBUyQ
▶️ [379/1000] Video ID: NCc-XboIFFA
▶️ [380/1000] Video ID: DuZiEjmxdRc
▶️ [381/1000] Video ID: P1REjRS8ckw
▶️ [382/1000] Video ID: gqAvqgBI1FE
▶️ [383/1000] Video ID: rRb5mFTkqJM
▶️ [384/1000] Video ID: jCu_ogEQT0o
▶️ [385/1000] Video ID: YKoMigNBScY
▶️ [386/1000] Video ID: P9HRyvqNZBo
▶️ [387/1000] Video ID: T7BnjrpCxZ4
▶️ [388/1000] Video ID: NDZRvjklcpQ
▶️ [389/1000] Video ID: g7_sg_ZUoK4
▶️ [390/1000] Video ID: ff2qWadRZw4
▶️ [391/1000] Video ID: nKWL3Vii7-Y
▶️ [392/1000] Video ID: 5tD_eUVZHGc
▶️ [393/1000] Video ID: 5VSYPTOvesk
▶️ [394/1000] Video ID: 9DmPKNjDfyQ
▶️ [395/1000] Video ID: AAJQNgkVpKE
▶️ [396/1000] Video ID: rG9Tzw_r0s8
▶️ [397/1000] Video ID: NCyOLuAwxVI
▶️ [398/1000] Video ID: qzam_4m5Tqk
▶️ [399/1000] Video ID: _3oDfjbXMiA
▶️ [400/1000] Video ID: Pojztw9ZIQM
▶️ [401/1000] Video ID: V4pWCbSCs6c
▶️ [402/1000] Video ID: 3-eIoclwfOs
▶️ [403/1000] Video ID: hpeBxresiT0
▶️ [404/1000] Video ID: ASXRs_4XQGY
▶️ [405/1000] Video ID: sAxUlfK9TBc
▶️ [406/1000] Video ID: YawRrbaKfpg
▶️ [407/1000] Video ID: QsCAzOpbUF8
▶️ [408/1000] Video ID: tvJwzE2-sAA
▶️ [409/1000] Video ID: Q2u1quyxitg
▶️ [410/1000] Video ID: bKYLLzLU16k
▶️ [411/1000] Video ID: TolI8va6pIY
▶️ [412/1000] Video ID: WGJ38Su_evc
▶️ [413/1000] Video ID: 2XOcl8Ytfbk
▶️ [414/1000] Video ID: qlhnERTnrms
▶️ [415/1000] Video ID: lNDK6oGp5qs
▶️ [416/1000] Video ID: WgReWJSyPe8
▶️ [417/1000] Video ID: aRz8i6gggtc
▶️ [418/1000] Video ID: uRH42BbVRW0
▶️ [419/1000] Video ID: T-_kjNcpoYI
▶️ [420/1000] Video ID: F1cLZabu75A
▶️ [421/1000] Video ID: hWvHumiun3k
▶️ [422/1000] Video ID: H9TLdfIOHYM
▶️ [423/1000] Video ID: 90W740N4HEQ
▶️ [424/1000] Video ID: vVveebwm7hE
▶️ [425/1000] Video ID: 5cyj8T54jWY
▶️ [426/1000] Video ID: 4u4WyGxHc1M
▶️ [427/1000] Video ID: k2-Ri4iNG24
▶️ [428/1000] Video ID: RVPoo6abK0U
▶️ [429/1000] Video ID: 3aF5t-hvO5I
▶️ [430/1000] Video ID: 1XkaO9NP9RE
▶️ [431/1000] Video ID: DxQuQ_a0oJA
▶️ [432/1000] Video ID: pon_PWaiSaI
▶️ [433/1000] Video ID: aBcpRhzTHVw
▶️ [434/1000] Video ID: iYXLNVxPN2w
▶️ [435/1000] Video ID: oMhoVeUMiKY
▶️ [436/1000] Video ID: BDNcIzNCMIE
▶️ [437/1000] Video ID: IPCJfyCp8bg
▶️ [438/1000] Video ID: 1f8ZN6Pu0m0
▶️ [439/1000] Video ID: oaN1895RRSc
▶️ [440/1000] Video ID: Rwp-oM3w2O4
▶️ [441/1000] Video ID: -UWDj01gRk0
▶️ [442/1000] Video ID: WOJlD_G12Us
▶️ [443/1000] Video ID: n66woNJKGBs
▶️ [444/1000] Video ID: EwC4EkS__r0
▶️ [445/1000] Video ID: DmHISUOvdNA
▶️ [446/1000] Video ID: dxw27idG-50
▶️ [447/1000] Video ID: 8JbAJsuYhmU
▶️ [448/1000] Video ID: vWtZ7MIpSKw
▶️ [449/1000] Video ID: v0tTFUnFups
▶️ [450/1000] Video ID: NbWxDdFqAyk
▶️ [451/1000] Video ID: W_luUWtt418
▶️ [452/1000] Video ID: HrO2gt0XdYQ
▶️ [453/1000] Video ID: 0NHfdhfJ3UI
▶️ [454/1000] Video ID: IuXzRpQ55oM
▶️ [455/1000] Video ID: 7PdZZIYn0JE
▶️ [456/1000] Video ID: OD7xDwpE5QE
▶️ [457/1000] Video ID: MYi2g5MO8mw
▶️ [458/1000] Video ID: khmxtAly0ng
▶️ [459/1000] Video ID: -tYTFU2jLd0
▶️ [460/1000] Video ID: nWrsTLwotoQ
▶️ [461/1000] Video ID: Q93L9x7xdQA
▶️ [462/1000] Video ID: 5lftSBEX7Tg
▶️ [463/1000] Video ID: SZoAUTudO5g
▶️ [464/1000] Video ID: CHA9Dtulydc
▶️ [465/1000] Video ID: G1E0rNNCC60
▶️ [466/1000] Video ID: JtIFlq3veuY
▶️ [467/1000] Video ID: ky8znAABLfo
▶️ [468/1000] Video ID: BU7O5WHL1Vg
▶️ [469/1000] Video ID: M_Q1MOtUTQ8
▶️ [470/1000] Video ID: OTwsuAgHXrE
▶️ [471/1000] Video ID: HPdOODnNIA4
▶️ [472/1000] Video ID: Bd2ciu-b4yY
▶️ [473/1000] Video ID: m1XgPvJfknU
▶️ [474/1000] Video ID: Me8n8PrC0DU
▶️ [475/1000] Video ID: G5Uu4nGehgw
▶️ [476/1000] Video ID: AZRShRdcVQY
▶️ [477/1000] Video ID: yEilTWMMNF8
▶️ [478/1000] Video ID: iPNWu-VWoto
▶️ [479/1000] Video ID: 70YWaCmaM3g
▶️ [480/1000] Video ID: f63wTnYaf68
▶️ [481/1000] Video ID: raD-f7x6F1g
▶️ [482/1000] Video ID: eZFpJjIz4oE
▶️ [483/1000] Video ID: 2VLf_HIOWYE
▶️ [484/1000] Video ID: F2C9qnmFcN0
▶️ [485/1000] Video ID: mzE9U1m7-w4
▶️ [486/1000] Video ID: ZOh1vec_B5E
▶️ [487/1000] Video ID: WXc_T9uOA4o
▶️ [488/1000] Video ID: hSa9FOiqan0
▶️ [489/1000] Video ID: nsEOU1HajhQ
▶️ [490/1000] Video ID: m12BZm1BAeo
▶️ [491/1000] Video ID: K4aocNeDJbs
▶️ [492/1000] Video ID: kx3kGjSEtEo
▶️ [493/1000] Video ID: VydEHkn1ZYw
▶️ [494/1000] Video ID: XtgQqhYR-gk
▶️ [495/1000] Video ID: StQ8uSBJq_g
▶️ [496/1000] Video ID: Gw7bikstU10
▶️ [497/1000] Video ID: 13WVWKvc224
▶️ [498/1000] Video ID: qXKScZpxM4w
▶️ [499/1000] Video ID: Dj0i6v_0Nac
▶️ [500/1000] Video ID: 7FjjXj47Roo
▶️ [501/1000] Video ID: CVtp0Ef4wWg
▶️ [502/1000] Video ID: turueHxuVVI
▶️ [503/1000] Video ID: LD2TzJp9X7c
▶️ [504/1000] Video ID: L0AIgFauDrc
▶️ [505/1000] Video ID: X50ah8sf0Js
▶️ [506/1000] Video ID: xGxEUx65snw
▶️ [507/1000] Video ID: 3TuggLXLLFA
▶️ [508/1000] Video ID: BWkSXpVH89Y
▶️ [509/1000] Video ID: _ou4sjaWOXc
▶️ [510/1000] Video ID: 2Pwm4tzGdDs
▶️ [511/1000] Video ID: me5-Gs0xpN4
▶️ [512/1000] Video ID: vSSLp5Mtmdo
▶️ [513/1000] Video ID: XgdF8Rh9RM0
▶️ [514/1000] Video ID: DQG7qsvE6bY
▶️ [515/1000] Video ID: CqdznQva--g
▶️ [516/1000] Video ID: yMuuRBM-KV0
▶️ [517/1000] Video ID: HDGh1sOQDt8
▶️ [518/1000] Video ID: 14T_J07_MGc
▶️ [519/1000] Video ID: jL6uAU-uFLo
▶️ [520/1000] Video ID: buPMlXlVFb4
▶️ [521/1000] Video ID: 1uKsWjRt6QI
▶️ [522/1000] Video ID: R42fBbyAJR0
▶️ [523/1000] Video ID: IBFiqqqLJ_A
▶️ [524/1000] Video ID: CQ_iFSKgmtA
▶️ [525/1000] Video ID: Fga5x7Abh_Q
▶️ [526/1000] Video ID: UhEkqnMTbRw
▶️ [527/1000] Video ID: iEQGwlPngw4
▶️ [528/1000] Video ID: VPBIysulx9E
▶️ [529/1000] Video ID: poLA2dQZOko
▶️ [530/1000] Video ID: Mcny15NfC7U
▶️ [531/1000] Video ID: tT7uraaEZq4
▶️ [532/1000] Video ID: jwKPOHzBL1Y
▶️ [533/1000] Video ID: WsXMsOiaZtg
▶️ [534/1000] Video ID: _4-HL99gICo
▶️ [535/1000] Video ID: 84t75QQ5ge8
▶️ [536/1000] Video ID: qmYKD9GUcGc
▶️ [537/1000] Video ID: PS7nWYuyfPs
▶️ [538/1000] Video ID: QSNjkx1tSHI
▶️ [539/1000] Video ID: 8L71QATmPMI
▶️ [540/1000] Video ID: VYKsCQo_yIs
▶️ [541/1000] Video ID: zmcnkJrwfkM
▶️ [542/1000] Video ID: o9rkQ5LKD60
▶️ [543/1000] Video ID: ZZVbU6VYHCQ
▶️ [544/1000] Video ID: Epc79HyTUZ4
▶️ [545/1000] Video ID: M5HL46K3Mao
▶️ [546/1000] Video ID: 3MSGHyxar24
▶️ [547/1000] Video ID: HnqFs4Q1IHU
▶️ [548/1000] Video ID: -iMzdDi0X0w
▶️ [549/1000] Video ID: 6iA8RIm_dNo
▶️ [550/1000] Video ID: 13JzibsrGVs
▶️ [551/1000] Video ID: -unE7qKLWn4
▶️ [552/1000] Video ID: qzp8UxPs2fo
▶️ [553/1000] Video ID: JJ2btoNp5gI
▶️ [554/1000] Video ID: hWB4cma0DHA
▶️ [555/1000] Video ID: nXxjoFPEAiw
▶️ [556/1000] Video ID: jEoiIsi9DV0

In [6]:
import pandas as pd
from transformers import pipeline
from tqdm.auto import tqdm
import os # To check if files exist

# --- 1. CENTRALIZED KNOWLEDGE BASE ---
# This is the "brain" of our system. Add player names and keywords here.
# All names and keywords should be lowercase for consistent matching.

KNOWLEDGE_BASE = {
    'wolfsburg': {
        'women_players': ['alexandra popp', 'ewa pajor', 'lena oberdorf', 'jill roord', 'svenja huth', 'merle frohms', 'jule brand', 'tommy stroot'],
        'men_players': ['koen casteels', 'maxence lacroix', 'ridle baku', 'maximilian arnold', 'jonas wind', 'lukas nmecha', 'niko kovač'],
        'women_keywords': ['she-wolves', 'wölfinnen', 'frauen'],
        'men_keywords': ['männer']
    },
    'arsenal': {
        'women_players': ['beth mead', 'vivianne miedema', 'leah williamson', 'lia wälti', 'caitlin foord', 'frida maanum', 'manuela zinsberger', 'jonas eidevall'],
        'men_players': ['bukayo saka', 'martin ødegaard', 'gabriel jesus', 'william saliba', 'aaron ramsdale', 'declan rice', 'mikel arteta'],
        'women_keywords': ['arsenal wfc', 'arsenal women'],
        'men_keywords': ['arsenal men']
    },
    'chelsea': {
        'women_players': ['sam kerr', 'fran kirby', 'pernille harder', 'magdalena eriksson', 'millie bright', 'guro reiten', 'ann-katrin berger', 'emma hayes'],
        'men_players': ['reece james', 'ben chilwell', 'thiago silva', 'enzo fernández', 'raheem sterling', 'nicolas jackson', 'mauricio pochettino'],
        'women_keywords': ['chelsea fc women'],
        'men_keywords': []
    },
    'paris_fc': {
        # Note: Paris FC is primarily known for its women's team in D1 Arkema. The men's team is in Ligue 2.
        # This might lead to ambiguity if not handled carefully.
        'women_players': ['gaëtane thiney', 'clara matéo', 'chiamaka nnadozie', 'julie dufour', 'sandrine soubeyrand'],
        'men_players': ['ilhan kebbal', 'cyril mandouki', 'pierre-yves hamel', 'stéphane gilli'],
        'women_keywords': ['paris fc féminin'],
        'men_keywords': []
    },
    'juventus': {
        'women_players': ['cristiana girelli', 'barbara bonansea', 'arianna caruso', 'lisa boattin', 'valentina cernoia', 'joe montemurro'],
        'men_players': ['dušan vlahović', 'federico chiesa', 'manuel locatelli', 'wojciech szczęsny', 'danilo', 'adrien rabiot', 'massimiliano allegri'],
        'women_keywords': ['juventus women', 'juve women'],
        'men_keywords': []
    },
    'corinthians': {
        # Brazilian team names can be complex.
        'women_players': ['tamires', 'gabi zanotti', 'adriana leal', 'vic albuquerque', 'arthur elias'],
        'men_players': ['cássio', 'fagner', 'renato augusto', 'yuri alberto', 'róger guedes', 'vanderlei luxemburgo'],
        'women_keywords': ['corinthians feminino'],
        'men_keywords': ['corinthians masculino', 'timão'] # 'Timão' is a general nickname, but often refers to the men's team.
    }
}

# --- 2. CONFIGURATION & SETUP ---

# List of clubs to process. The script will look for a CSV with this name.
# Format: ('filename.csv', 'knowledge_base_key')
CLUBS_TO_PROCESS = [
    ('wolfsburg.csv', 'wolfsburg'),
    ('arsenal.csv', 'arsenal'),
    ('chelsea.csv', 'chelsea'),
    ('parisfc.csv', 'paris_fc'),
    ('juventus.csv', 'juventus'),
    ('corinthians.csv', 'corinthians'),
]

# Initialize pipeline ONCE. We still need it as a fallback.
print("Initializing Zero-Shot-Classification pipeline...")
classifier = pipeline(
    "zero-shot-classification",
    model="cross-encoder/nli-deberta-v3-large",
    device=-1  # Set to -1 for CPU, 0 for GPU
)
candidate_labels = ["male football", "female football"]


# --- 3. GENERALIZED CLASSIFIER FUNCTION ---
def knowledge_based_gender_classifier(title, club_key, knowledge_base):
    """
    Classifies a title's gender based on general keywords and club-specific knowledge.
    """
    title_lower = title.lower()

    # Get the specific knowledge for the given club
    club_info = knowledge_base.get(club_key, {})
    women_players = club_info.get('women_players', [])
    men_players = club_info.get('men_players', [])
    women_keywords = club_info.get('women_keywords', [])
    men_keywords = club_info.get('men_keywords', [])

    # 1. Check for universal and club-specific female keywords
    universal_female_kws = ['femení', 'femenil', 'femenina', 'women', 'womens', 'wfc', 'ladies']
    if any(kw in title_lower for kw in universal_female_kws + women_keywords):
        return "female football"

    # 2. Check for universal and club-specific male keywords
    universal_male_kws = ['men', 'mens', 'masculino', 'masculine']
    if any(kw in title_lower for kw in universal_male_kws + men_keywords):
        return "male football"

    # 3. Check for player/coach names from our knowledge base for that specific club
    if any(player in title_lower for player in women_players):
        return "female football"
    if any(player in title_lower for player in men_players):
        return "male football"

    # 4. If no match, return None to let the zero-shot model decide
    return None

# --- 4. MAIN PROCESSING LOOP ---

all_results = []

print("\nStarting classification for all specified clubs...")

for filename, club_key in CLUBS_TO_PROCESS:
    if not os.path.exists(filename):
        print(f"\n--- Skipping {club_key.title()}: File '{filename}' not found. ---")
        continue

    print(f"\n--- Processing {club_key.title()} from '{filename}' ---")
    df = pd.read_csv(filename)
    titles = df['Video Title'].drop_duplicates().tolist()

    club_results = []
    titles_for_model = []

    # First pass: Apply our powerful knowledge-based classifier
    for title in titles:
        rule_based_label = knowledge_based_gender_classifier(title, club_key, KNOWLEDGE_BASE)
        if rule_based_label:
            club_results.append({
                "Club": club_key,
                "Video Title": title,
                "Predicted Gender": rule_based_label,
                "Method": "knowledge_rule"
            })
        else:
            titles_for_model.append(title)

    # Second pass: Use the zero-shot model ONLY as a last resort for the remaining titles
    if titles_for_model:
        print(f"Rule-based classifier handled {len(club_results)} titles. Using zero-shot for the remaining {len(titles_for_model)}...")
        model_outputs = classifier(titles_for_model, candidate_labels=candidate_labels, multi_label=False)

        for output in tqdm(model_outputs, desc=f"Model-Classifying {club_key.title()}"):
            club_results.append({
                "Club": club_key,
                "Video Title": output["sequence"],
                "Predicted Gender": output["labels"][0],
                "Method": "zero-shot"
            })
    else:
        print("All titles were successfully classified using knowledge-based rules.")

    all_results.extend(club_results)


# --- 5. FINAL RESULTS & ANALYSIS ---
if not all_results:
    print("\nNo data was processed. Please ensure your CSV files are in the correct directory.")
else:
    result_df = pd.DataFrame(all_results)

    print("\n\n" + "="*50)
    print("             OVERALL CLASSIFICATION COMPLETE")
    print("="*50 + "\n")

    print("--- Final DataFrame Head ---")
    print(result_df.head())

    print("\n--- Breakdown by Club and Method ---")
    # Using crosstab for a nice, clear table
    print(pd.crosstab(result_df['Club'], result_df['Method']))

    print("\n--- Breakdown by Club and Predicted Gender ---")
    print(pd.crosstab(result_df['Club'], result_df['Predicted Gender']))

    # Optional: Save the full combined results to a new CSV
    # result_df.to_csv("all_clubs_classified.csv", index=False)
    # print("\nFull results saved to 'all_clubs_classified.csv'")

Initializing Zero-Shot-Classification pipeline...

Starting classification for all specified clubs...

--- Processing Wolfsburg from 'wolfsburg.csv' ---
Rule-based classifier handled 244 titles. Using zero-shot for the remaining 751...

Model-Classifying Wolfsburg:   0%|          | 0/751 [00:00<?, ?it/s]

--- Processing Arsenal from 'arsenal.csv' ---
Rule-based classifier handled 169 titles. Using zero-shot for the remaining 828...

Model-Classifying Arsenal:   0%|          | 0/828 [00:00<?, ?it/s]

--- Processing Chelsea from 'chelsea.csv' ---
Rule-based classifier handled 157 titles. Using zero-shot for the remaining 842...

Model-Classifying Chelsea:   0%|          | 0/842 [00:00<?, ?it/s]

--- Processing Paris_Fc from 'parisfc.csv' ---
Rule-based classifier handled 28 titles. Using zero-shot for the remaining 349...

Model-Classifying Paris_Fc:   0%|          | 0/349 [00:00<?, ?it/s]

--- Processing Juventus from 'juventus.csv' ---
Rule-based classifier handled 123 titles. Using zero-shot for the remaining 876...

Model-Classifying Juventus:   0%|          | 0/876 [00:00<?, ?it/s]

--- Processing Corinthians from 'corinthians.csv' ---
Rule-based classifier handled 261 titles. Using zero-shot for the remaining 729...

Model-Classifying Corinthians:   0%|          | 0/729 [00:00<?, ?it/s]

==================================================
             OVERALL CLASSIFICATION COMPLETE
==================================================

--- Final DataFrame Head ---
        Club                                        Video Title  \
0  wolfsburg  "Anstrengend, aber gut!" | Stimmen | Trainings...
1  wolfsburg  RE-LIVE vom Spielfeldrand! 🟢⚪ Trainingsauftakt...
2  wolfsburg  Die Wölfinnen auf dem Prüfstand! 💪😮‍💨 Leistung...
3  wolfsburg  Bonjour Wölfinnen! 🇫🇷 Kessya Bussy im Intervie...
4  wolfsburg                   Herzlich Willkommen, Coach 🇳🇱🤝🇩🇪

  Predicted Gender          Method
0  female football  knowledge_rule
1  female football  knowledge_rule
2  female football  knowledge_rule
3  female football  knowledge_rule
4    male football  knowledge_rule

--- Breakdown by Club and Method ---
Method       knowledge_rule  zero-shot
Club
arsenal                 169        828
chelsea                 157        842
corinthians             261        729
juventus                123        876
paris_fc                 28        349
wolfsburg               244        751

--- Breakdown by Club and Predicted Gender ---
Predicted Gender  female football  male football
Club
arsenal                       146            851
chelsea                       239            760
corinthians                   180            810
juventus                      190            809
paris_fc                       53            324
wolfsburg                     269            726

In [7]:
# Group by Club and count Predicted Gender
gender_counts = result_df.groupby("Club")["Predicted Gender"].value_counts().unstack(fill_value=0)

print(gender_counts)

Predicted Gender  female football  male football
Club
arsenal                       146            851
chelsea                       239            760
corinthians                   180            810
juventus                      190            809
paris_fc                       53            324
wolfsburg                     269            726

In [8]:
result_df

,Club,Video Title,Predicted Gender,Method
0,wolfsburg,"""Anstrengend, aber gut!"" | Stimmen | Trainings...",female football,knowledge_rule
1,wolfsburg,RE-LIVE vom Spielfeldrand! 🟢⚪ Trainingsauftakt...,female football,knowledge_rule
2,wolfsburg,Die Wölfinnen auf dem Prüfstand! 💪😮‍💨 Leistung...,female football,knowledge_rule
3,wolfsburg,Bonjour Wölfinnen! 🇫🇷 Kessya Bussy im Intervie...,female football,knowledge_rule
4,wolfsburg,"Herzlich Willkommen, Coach 🇳🇱🤝🇩🇪",male football,knowledge_rule
...,...,...,...,...
5352,corinthians,Os trabalhos no CT para o primeiro clássico do...,male football,zero-shot
5353,corinthians,"Fala, Maycon. 🗣️",female football,zero-shot
5354,corinthians,"Fala, Ryan! 🗣️",male football,zero-shot
5355,corinthians,BASTIDORES | Corinthians 2 x 1 Água Santa | Pa...,male football,zero-shot
5356,corinthians,O gol do Talles pro Levi! 🥹 #VaiCorinthians #S...,female football,zero-shot

In [9]:
from collections import defaultdict

# Initialize nested dictionary
titles_by_club_and_gender = defaultdict(lambda: {"male football": [], "female football": []})

# Iterate through DataFrame and populate dictionary
for _, row in result_df.iterrows():
    club = row["Club"]
    gender = row["Predicted Gender"]
    title = row["Video Title"]

    titles_by_club_and_gender[club][gender].append(title)

# Optional: convert to regular dict (not defaultdict)
titles_by_club_and_gender = dict(titles_by_club_and_gender)

In [10]:
import pandas as pd

# Store counts in a list of dicts for easy conversion to DataFrame later
comment_counts = []

for club, gendered_titles in titles_by_club_and_gender.items():
    # Custom filename formatting
    if club.lower().replace(" ", "") == "paris_fc":
        filename = "parisfc.csv"
    else:
        filename = f"{club.lower().replace(' ', '_')}.csv"  # e.g., "fc_barcelona.csv"

    try:
        # Load comments for this club
        club_df = pd.read_csv(filename)

        # Get both sets of titles
        female_titles = set(gendered_titles.get("female football", []))
        male_titles = set(gendered_titles.get("male football", []))

        # Filter comments by gendered video titles
        female_comments = club_df[club_df["Video Title"].isin(female_titles)]
        male_comments = club_df[club_df["Video Title"].isin(male_titles)]

        # Store the counts
        comment_counts.append({
            "Club": club,
            "Female Football Comments": len(female_comments),
            "Male Football Comments": len(male_comments),
            "Total Comments": len(club_df)
        })

    except FileNotFoundError:
        print(f"⚠️ Could not find CSV for: {club}")
        continue

# Convert to DataFrame
counts_df = pd.DataFrame(comment_counts)

# Save to CSV if needed
counts_df.to_csv("comment_gender_counts.csv", index=False)

# Display
print(counts_df)

          Club  Female Football Comments  Male Football Comments  \
0    wolfsburg                      3274                    8137
1      arsenal                     10815                  135661
2      chelsea                     17864                  141332
3     paris_fc                       140                    1053
4     juventus                     10813                   84522
5  corinthians                      8167                   33558

   Total Comments
0           11411
1          146476
2          159196
3            1193
4           95335
5           41725

In [11]:
import pandas as pd
import random

def balance_by_gender_from_predictions(club_name, result_df, folder_path=".", random_seed=42):
    # Normalize file name
    file_name = f"{club_name.lower().replace(' ', '_')}.csv" if club_name.lower().replace(' ', '') != "paris_fc" else "parisfc.csv"
    full_path = f"{folder_path}/{file_name}"
   
    # Load full comment dataset
    df_all = pd.read_csv(full_path)
   
    # Extract predicted gender for the club's videos
    club_preds = result_df[result_df["Club"] == club_name]
   
    # Get lists of video titles by gender
    female_titles = set(club_preds[club_preds["Predicted Gender"] == "female football"]["Video Title"])
    male_titles = set(club_preds[club_preds["Predicted Gender"] == "male football"]["Video Title"])
   
    # Split the full comment dataset by gender
    df_female = df_all[df_all["Video Title"].isin(female_titles)].copy()
    df_male = df_all[df_all["Video Title"].isin(male_titles)].copy()
   
    # Count total comments and unique videos for female football
    n_comments_f = len(df_female)
    n_videos_f = df_female["Video Title"].nunique()
    print(f"📊 {club_name}: {n_comments_f} female comments across {n_videos_f} videos")
   
    # Prepare male video metadata for stratified sampling
    male_videos = (
        df_male.groupby("Video Title")
        .agg({"View Count": "first"})
        .reset_index()
        .sort_values("View Count", ascending=False)
    )
    
    # Stratify into thirds
    n = len(male_videos)
    top_1_3 = male_videos.iloc[:n//3]
    middle_1_3 = male_videos.iloc[n//3:2*n//3]
    bottom_1_3 = male_videos.iloc[2*n//3:]
    
    # Sample videos from each tier
    random.seed(random_seed)
    sampled_titles = []
    for tier in [top_1_3, middle_1_3, bottom_1_3]:
        tier_sample_size = min(n_videos_f // 3, len(tier))
        if tier_sample_size > 0:
            tier_sample = tier.sample(n=tier_sample_size, random_state=random_seed, replace=False)
            sampled_titles.extend(tier_sample["Video Title"].tolist())
    
    # Handle leftover videos if n_videos_f not divisible by 3
    while len(sampled_titles) < n_videos_f:
        extras = male_videos[~male_videos["Video Title"].isin(sampled_titles)]
        if not extras.empty:
            sampled_titles.append(extras.sample(n=1, random_state=random_seed)["Video Title"].values[0])
        else:
            break
    
    # First pass: Sample comments per video with initial quotas
    per_video_quota = n_comments_f // len(sampled_titles)
    remainder = n_comments_f % len(sampled_titles)
    sampled_rows = []
    total_sampled = 0
    used_titles = set()
    
    for i, title in enumerate(sampled_titles):
        vid_comments = df_male[df_male["Video Title"] == title]
        n_sample = per_video_quota + (1 if i < remainder else 0)
        actual_sample = min(n_sample, len(vid_comments))
        
        if actual_sample > 0:
            sampled = vid_comments.sample(n=actual_sample, random_state=random_seed + i)
            sampled_rows.append(sampled)
            total_sampled += len(sampled)
            used_titles.add(title)
    
    # Second pass: If we still need more comments, sample from remaining videos
    # (including videos not in our stratified sample)
    while total_sampled < n_comments_f:
        # Get all available male videos not yet fully used
        remaining_candidates = []
        
        # First try unused videos from our stratified sample
        unused_from_sample = [t for t in sampled_titles if t not in used_titles]
        if unused_from_sample:
            remaining_candidates.extend(unused_from_sample)
        
        # Then try videos not in our original stratified sample
        all_male_titles = set(male_videos["Video Title"])
        unsampled_titles = all_male_titles - set(sampled_titles)
        if unsampled_titles:
            remaining_candidates.extend(list(unsampled_titles))
        
        # Finally, try to get more comments from already used videos
        if not remaining_candidates:
            remaining_candidates = list(used_titles)
        
        if not remaining_candidates:
            break
        
        # Sample from remaining candidates
        for title in remaining_candidates:
            if total_sampled >= n_comments_f:
                break
                
            vid_comments = df_male[df_male["Video Title"] == title]
            
            # If we've already sampled from this video, exclude those comments
            if title in used_titles:
                already_sampled_indices = []
                for sampled_df in sampled_rows:
                    already_sampled_indices.extend(
                        sampled_df[sampled_df["Video Title"] == title].index.tolist()
                    )
                vid_comments = vid_comments.drop(already_sampled_indices, errors='ignore')
            
            needed = n_comments_f - total_sampled
            n_sample = min(needed, len(vid_comments))
            
            if n_sample > 0:
                sampled = vid_comments.sample(n=n_sample, random_state=random_seed + total_sampled)
                sampled_rows.append(sampled)
                total_sampled += len(sampled)
                used_titles.add(title)
        
        # Safety check to avoid infinite loop
        if total_sampled < n_comments_f and len(remaining_candidates) == 0:
            print(f"⚠️  Warning: Only {total_sampled} male comments available, less than target {n_comments_f}")
            break
    
    df_male_balanced = pd.concat(sampled_rows, ignore_index=True) if sampled_rows else pd.DataFrame()
    print(f"✅ Sampled {len(df_male_balanced)} male comments from {len(used_titles)} videos")
    
    return df_female.reset_index(drop=True), df_male_balanced.reset_index(drop=True)

In [12]:
arsenalF_df, arsenalM_df = balance_by_gender_from_predictions("arsenal", result_df)

print(len(arsenalF_df), "female comments")
print(len(arsenalM_df), "male comments")

📊 arsenal: 10815 female comments across 146 videos
✅ Sampled 10815 male comments from 161 videos
10815 female comments
10815 male comments

In [13]:
arsenalM_df.head()

,Video Title,Like Count,View Count,Comment Count,Commenter Name,Comment,Comment Like Count,YouTube Channel
0,JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...,66432,2656310,435,@Ayon-Bayern,So whom are you using rn -\nCalafiori or Timber ?,0,Arsenal
1,JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...,66432,2656310,435,@TalhaIb,Still losee,0,Arsenal
2,JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...,66432,2656310,435,@jaydinyearwood9181,The tackle when you bottled everything this se...,0,Arsenal
3,JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...,66432,2656310,435,@ayenijoshua9686,Who noticed SALIBA was ready to charge at the ...,7,Arsenal
4,JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...,66432,2656310,435,@kmetofficial5800,Lol psg should have put desire doué left side ...,0,Arsenal

In [14]:
chelseaF_df, chelseaM_df = balance_by_gender_from_predictions("chelsea", result_df)
wolfsburgF_df, wolfsburgM_df = balance_by_gender_from_predictions("wolfsburg", result_df)
parisfcF_df, parisfcM_df = balance_by_gender_from_predictions("paris_fc", result_df)
corinthiansF_df, corinthiansM_df = balance_by_gender_from_predictions("corinthians", result_df)
juventusF_df, juventusM_df = balance_by_gender_from_predictions("juventus", result_df)

📊 chelsea: 17864 female comments across 239 videos
✅ Sampled 17864 male comments from 253 videos
📊 wolfsburg: 3274 female comments across 269 videos
✅ Sampled 3274 male comments from 361 videos
📊 paris_fc: 140 female comments across 53 videos
✅ Sampled 140 male comments from 71 videos
📊 corinthians: 8167 female comments across 180 videos
✅ Sampled 8167 male comments from 250 videos
📊 juventus: 10813 female comments across 190 videos
✅ Sampled 10813 male comments from 257 videos

In [15]:
print(chelseaF_df.head())
print(wolfsburgF_df.head())
print(arsenalF_df.head())
print(parisfcF_df.head())
print(corinthiansF_df.head())
print(juventusF_df.head())

print(chelseaM_df.head())
print(wolfsburgM_df.head())
print(arsenalM_df.head())
print(parisfcM_df.head())
print(corinthiansM_df.head())
print(juventusM_df.head())

                   Video Title  Like Count  View Count  Comment Count  \
0  DEWSBURY-HALL makes it 4️⃣!        5101       98746             78
1  DEWSBURY-HALL makes it 4️⃣!        5101       98746             78
2  DEWSBURY-HALL makes it 4️⃣!        5101       98746             78
3  DEWSBURY-HALL makes it 4️⃣!        5101       98746             78
4  DEWSBURY-HALL makes it 4️⃣!        5101       98746             78

        Commenter Name                                            Comment  \
0       @ScottGG-tq5ts                    Cundy ns the background!! hahah
1       @rabahtaha3016          He is the unrated and underrated player 😮
2  @FidelIdoniboye-c9t  So happy for palmers first goal contribution t...
3        @kylereece575                                 Well played nkunku
4              @CAVCFC                           Yam bam give me some ham

   Comment Like Count        YouTube Channel
0                   0  Chelsea Football Club
1                   0  Chelsea Football Club
2                   0  Chelsea Football Club
3                   0  Chelsea Football Club
4                   0  Chelsea Football Club
                                         Video Title  Like Count  View Count  \
0  "Ich kann nicht mehr!" 😮‍💨 | Hinter den Kuliss...         194        4930
1  "Ich kann nicht mehr!" 😮‍💨 | Hinter den Kuliss...         194        4930
2  "Ich kann nicht mehr!" 😮‍💨 | Hinter den Kuliss...         194        4930
3  "Ich kann nicht mehr!" 😮‍💨 | Hinter den Kuliss...         194        4930
4  "Ich kann nicht mehr!" 😮‍💨 | Hinter den Kuliss...         194        4930

   Comment Count    Commenter Name  \
0             15  @moritzweber9315
1             15       @19Anonym45
2             15     @FlipFlop-r8d
3             15   @zeugengrafites
4             15        @Hofenheim

                                             Comment  Comment Like Count  \
0  Willkommen in der Bundesliga Aaron, merkt scho...                   1
1                                       Maschinen 🐺🐺                   2
2                                Wo neuer Stürmer? 👀                   0
3                          Mæhle ist eine Maschine 😮                  18
4                                         Gut kick 👍                   1

  YouTube Channel
0   VfL Wolfsburg
1   VfL Wolfsburg
2   VfL Wolfsburg
3   VfL Wolfsburg
4   VfL Wolfsburg
                              Video Title  Like Count  View Count  \
0  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
1  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
2  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
3  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
4  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281

   Comment Count        Commenter Name  \
0             16  @gbemigaakiniola8744
1             16        @hardroxxx5923
2             16          @alislim-c3g
3             16       @naomipeach5590
4             16        @vinnyvyas9794

                                             Comment  Comment Like Count  \
0                                       Welcome back                   0
1                                   She is beautiful                   0
2                   Excuse my Droooolll!!😍😍😍😍😍😍😍😍😍😍😍                   1
3                  Why is she so oily and shiny ? 😂😂                   0
4  Lovely. She is beautiful and a super talented ...                   2

  YouTube Channel
0         Arsenal
1         Arsenal
2         Arsenal
3         Arsenal
4         Arsenal
                                         Video Title  Like Count  View Count  \
0  🎬 Son plus beau souvenir? Son film préféré? My...          13        1157
1            La première interview de Sheika Scott !          14         337
2            La première interview de Sheika Scott !          14         337
3            La première interview de Sheika Scott !          14         337
4            La première interview de Sheika Scott !          14         337

   Comment Count Commenter Name  \
0              2  @Abderlebig22
1              4      @Toniopfc
2              4    @poutou1554
3              4       @litogor
4              4  @Tour62Eiffel

                                             Comment  Comment Like Count  \
0         Le front Zeubi elle a mangé le synthétique                   1
1                                        Bienvenue ❤                   1
2  Ouverture prioritaire des abonnements : jeudi ...                   0
3                            Bienvenue au Paris FC 👍                   1
4  Bienvenue à Paris. J'espère que vous y serez h...                   1

  YouTube Channel
0        Paris FC
1        Paris FC
2        Paris FC
3        Paris FC
4        Paris FC
                                         Video Title  Like Count  View Count  \
0  MESTRE WASHINGTON E MC SAMUKA | CORINTHIANS DO...       183.0        9623
1  GARRO: “ESTAMOS NOS PREPARANDO PARA COMEÇAR DA...      1680.0       15094
2  GARRO: “ESTAMOS NOS PREPARANDO PARA COMEÇAR DA...      1680.0       15094
3  GARRO: “ESTAMOS NOS PREPARANDO PARA COMEÇAR DA...      1680.0       15094
4  GARRO: “ESTAMOS NOS PREPARANDO PARA COMEÇAR DA...      1680.0       15094

   Comment Count        Commenter Name  \
0              1             @McSamuka
1             59      @felippedias5446
2             59  @celiocavalcante9215
3             59          @farra_festh
4             59           @Medinadu7x

                                             Comment  Comment Like Count  \
0  Satisfação Total minha Família 🦅🖤🤍 Gratidão Co...                   2
1                     Saudades da nossa seleção ⚫️⚪️                   0
2  Bom ver que o garro esta com umas cochas bem m...                   0
3  O time praticamente vai ter uma pre temporada ...                   0
4  Garro merece demais ser convocado pra seleção ...                   0

  YouTube Channel
0  Corinthians TV
1  Corinthians TV
2  Corinthians TV
3  Corinthians TV
4  Corinthians TV
                                         Video Title  Like Count  View Count  \
0  Taking the game to new heights, literally,Extr...      1581.0       47154
1  Taking the game to new heights, literally,Extr...      1581.0       47154
2  Taking the game to new heights, literally,Extr...      1581.0       47154
3  Taking the game to new heights, literally,Extr...      1581.0       47154
4  Taking the game to new heights, literally,Extr...      1581.0       47154

   Comment Count                 Commenter Name  \
0              9                  @MstoKhudoyan
1              9             @marcoarcangeli526
2              9  @ForzaJuventusLaVechiaSignora
3              9                       @not_or7
4              9                   @strazzo6840

                                             Comment  Comment Like Count  \
0                                        Hala Madrid                   0
1  Vorrei che la stessa accuratezza con la quale ...                   0
2                                     Grande Amore ❤                   0
3  Can’t wait for the juve city game will be there ❤                   4
4                         Grande professore!!!👨🏽‍🏫🤍🖤                   7

  YouTube Channel
0        Juventus
1        Juventus
2        Juventus
3        Juventus
4        Juventus
               Video Title  Like Count  View Count  Comment Count  \
0  No one can stop NETO😮‍💨       10827      221920            129
1  No one can stop NETO😮‍💨       10827      221920            129
2  No one can stop NETO😮‍💨       10827      221920            129
3  No one can stop NETO😮‍💨       10827      221920            129
4  No one can stop NETO😮‍💨       10827      221920            129

                    Commenter Name  \
0               @valerioharvey7289
1                       @sudan9393
2  @bamigboyeiyanuoluwaopeyemi2403
3                      @Wes_ley_33
4                  @thelegospy7600

                                             Comment  Comment Like Count  \
0  He absolutely cooked mykolenko throughout the ...                   0
1                      Portuguese speedster 😮‍💨😮‍💨💙💙                   0
2                                      Which Neto???                   0
3             Looks like Someone forgot to put music                   0
4           The past 2-3 games he’s been brilliant 😊                  12

         YouTube Channel
0  Chelsea Football Club
1  Chelsea Football Club
2  Chelsea Football Club
3  Chelsea Football Club
4  Chelsea Football Club
                                         Video Title  Like Count  View Count  \
0  „Werde ich niemals vergessen“ | Stimmen | UWCL...         571       35258
1  „Werde ich niemals vergessen“ | Stimmen | UWCL...         571       35258
2  „Werde ich niemals vergessen“ | Stimmen | UWCL...         571       35258
3  „Werde ich niemals vergessen“ | Stimmen | UWCL...         571       35258
4  „Werde ich niemals vergessen“ | Stimmen | UWCL...         571       35258

   Comment Count        Commenter Name  \
0             41    @dieballerburg1025
1             41        @StefanB-vv5eu
2             41  @JuliusPepperwood881
3             41      @HiViByRegina111
4             41         @HeribertLohr

                                             Comment  Comment Like Count  \
0  Ihr habt so schön gespielt heute einfach Mega ...                   7
1  Sveindis on fire 🔥💚🐺💚🔥 mein persönlicher Höhep...                  37
2                                         Sveindis ♥                   0
3  Das Spiel hat mich sehr glücklich gemacht, Sve...                  14
4  Glückwunsch. Wenn sie den Ball ruhig und struk...                   7

  YouTube Channel
0   VfL Wolfsburg
1   VfL Wolfsburg
2   VfL Wolfsburg
3   VfL Wolfsburg
4   VfL Wolfsburg
                                         Video Title  Like Count  View Count  \
0  JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...       66432     2656310
1  JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...       66432     2656310
2  JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...       66432     2656310
3  JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...       66432     2656310
4  JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...       66432     2656310

   Comment Count       Commenter Name  \
0            435         @Ayon-Bayern
1            435             @TalhaIb
2            435  @jaydinyearwood9181
3            435     @ayenijoshua9686
4            435    @kmetofficial5800

                                             Comment  Comment Like Count  \
0  So whom are you using rn -\nCalafiori or Timber ?                   0
1                                        Still losee                   0
2  The tackle when you bottled everything this se...                   0
3  Who noticed SALIBA was ready to charge at the ...                   7
4  Lol psg should have put desire doué left side ...                   0

  YouTube Channel
0         Arsenal
1         Arsenal
2         Arsenal
3         Arsenal
4         Arsenal
                                         Video Title  Like Count  View Count  \
0  Paris FC - SM Caen [4-2] : le résumé de la vic...          25        1184
1                            Récap de la semaine #20          64        4003
2                            Récap de la semaine #20          64        4003
3                            Récap de la semaine #20          64        4003
4  Conférence de presse d'Antoine Arnault et de P...         352       16542

   Comment Count      Commenter Name  \
0              1   @celticbalkan2219
1              6            @pilou75
2              6  @abelfonteneau1566
3              6   @neymarchauve3328
4             48          @tedstormy

                                             Comment  Comment Like Count  \
0  I can't wait for next season to watch the Pari...                   5
1  Allez les gars, c'est rien c'était juste un fa...                   7
2                                   On vous a bz🤫🤣💙🤍                   1
3                  Vous êtes éclater 😂😂😂🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣                   1
4  C'est ambitieux, c'est prometteur. Si le club ...                  13

  YouTube Channel
0        Paris FC
1        Paris FC
2        Paris FC
3        Paris FC
4        Paris FC
                                         Video Title  Like Count  View Count  \
0  BASTIDORES | Corinthians 2 x 0 São Bernardo | ...     18237.0      178663
1  BASTIDORES | Corinthians 2 x 0 São Bernardo | ...     18237.0      178663
2  BASTIDORES | Corinthians 2 x 0 São Bernardo | ...     18237.0      178663
3  BASTIDORES | Corinthians 2 x 0 São Bernardo | ...     18237.0      178663
4  BASTIDORES | Corinthians 2 x 0 São Bernardo | ...     18237.0      178663

   Comment Count              Commenter Name  \
0            345        @giovannasantana8686
1            345        @galerinhadatutu4037
2            345            @ariiesspark4866
3            345                   @killua7.
4            345  @brunovasconcelosalves8964

                                             Comment  Comment Like Count  \
0        O ambiente nos bastidores tá muito bom slk🔥                  72
1  parabens pela classificação, agora é ganhar o ...                   0
2                              eu te amo corinthians                   0
3            Os cara chama o garro de gordo lkkkkkkj                   1
4                     O Hugo é melhor até falando rs                   0

  YouTube Channel
0  Corinthians TV
1  Corinthians TV
2  Corinthians TV
3  Corinthians TV
4  Corinthians TV
                                         Video Title  Like Count  View Count  \
0  don’t worry bro it happens even to the best of...      9977.0      390914
1  don’t worry bro it happens even to the best of...      9977.0      390914
2  don’t worry bro it happens even to the best of...      9977.0      390914
3  don’t worry bro it happens even to the best of...      9977.0      390914
4  don’t worry bro it happens even to the best of...      9977.0      390914

   Comment Count      Commenter Name  \
0            109          @Jichuonyy
1            109   @MilanBrouwer-n3p
2            109      @Jacklovesgolf
3            109  @DeyanDimitrov-y3z
4            109       @kenanxsempre

                                             Comment  Comment Like Count  \
0                                           Nooo🗿🥶🤍🖤                   0
1           The admin of this cahnnel is is a savage                   0
2  Hi  JUVENTUS❤❤❤❤❤❤❤😊😊😊😊😊 I like man city bette...                   0
3                                           😂😂😂😂😂😂😂😂                   0
4          la situazione continua a sfuggire di mano                   0

  YouTube Channel
0        Juventus
1        Juventus
2        Juventus
3        Juventus
4        Juventus

In [16]:
def add_gender_of_sport_column(df, gender):
    df['Gender of Sport'] = gender
    return df

In [17]:
add_gender_of_sport_column(parisfcF_df, 'Female')
add_gender_of_sport_column(wolfsburgF_df, 'Female')
add_gender_of_sport_column(juventusF_df, 'Female')
add_gender_of_sport_column(arsenalF_df, 'Female')
add_gender_of_sport_column(chelseaF_df, 'Female')
add_gender_of_sport_column(corinthiansF_df, 'Female')

add_gender_of_sport_column(parisfcM_df, 'Male')
add_gender_of_sport_column(wolfsburgM_df, 'Male')
add_gender_of_sport_column(juventusM_df, 'Male')
add_gender_of_sport_column(arsenalM_df, 'Male')
add_gender_of_sport_column(chelseaM_df, 'Male')
add_gender_of_sport_column(corinthiansM_df, 'Male')

,Video Title,Like Count,View Count,Comment Count,Commenter Name,Comment,Comment Like Count,YouTube Channel,Gender of Sport
0,BASTIDORES | Corinthians 2 x 0 São Bernardo | ...,18237.0,178663,345,@giovannasantana8686,O ambiente nos bastidores tá muito bom slk🔥,72,Corinthians TV,Male
1,BASTIDORES | Corinthians 2 x 0 São Bernardo | ...,18237.0,178663,345,@galerinhadatutu4037,"parabens pela classificação, agora é ganhar o ...",0,Corinthians TV,Male
2,BASTIDORES | Corinthians 2 x 0 São Bernardo | ...,18237.0,178663,345,@ariiesspark4866,eu te amo corinthians,0,Corinthians TV,Male
3,BASTIDORES | Corinthians 2 x 0 São Bernardo | ...,18237.0,178663,345,@killua7.,Os cara chama o garro de gordo lkkkkkkj,1,Corinthians TV,Male
4,BASTIDORES | Corinthians 2 x 0 São Bernardo | ...,18237.0,178663,345,@brunovasconcelosalves8964,O Hugo é melhor até falando rs,0,Corinthians TV,Male
...,...,...,...,...,...,...,...,...,...
8162,Distribuição de ingressos na Neo Química Arena.,NaN,12637,322,@joseadrianosilva2573,"Se a torcida não comprar dos cambistas, vai co...",1,Corinthians TV,Male
8163,Distribuição de ingressos na Neo Química Arena.,NaN,12637,322,@lucately,PURA MENTIRA SOU FIEL TORCEDOR NAO CONSIGO COM...,0,Corinthians TV,Male
8164,Distribuição de ingressos na Neo Química Arena.,NaN,12637,322,@TheRucorreia,As receitas aumentaram em uma razão diretament...,0,Corinthians TV,Male
8165,Distribuição de ingressos na Neo Química Arena.,NaN,12637,322,@eduardo1987edu,Pinóquio Melo,3,Corinthians TV,Male
8166,Distribuição de ingressos na Neo Química Arena.,NaN,12637,322,@IgoorRafa,"Augusto é safado, mais do mesmo!",2,Corinthians TV,Male

In [45]:
combined_arsenal = pd.concat([arsenalF_df, arsenalM_df], ignore_index=True)
combined_corinthians = pd.concat([corinthiansF_df, corinthiansM_df], ignore_index=True)
combined_chelsea = pd.concat([chelseaF_df, chelseaM_df], ignore_index=True)
combined_juventus = pd.concat([juventusF_df, juventusM_df], ignore_index=True)
combined_wolfsburg = pd.concat([wolfsburgF_df, wolfsburgM_df], ignore_index=True)
combined_parisfc = pd.concat([parisfcF_df, parisfcM_df], ignore_index=True)

In [46]:
combined_arsenal.columns
combined_arsenal['Club'] = 'Arsenal'
combined_arsenal['Club Region'] = 'England'
print(combined_arsenal.head())
print(combined_arsenal.columns)

                              Video Title  Like Count  View Count  \
0  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
1  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
2  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
3  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281
4  REUNITED 🫂 #taylorhinds #arsenal #awfc         673       19281

   Comment Count        Commenter Name  \
0             16  @gbemigaakiniola8744
1             16        @hardroxxx5923
2             16          @alislim-c3g
3             16       @naomipeach5590
4             16        @vinnyvyas9794

                                             Comment  Comment Like Count  \
0                                       Welcome back                   0
1                                   She is beautiful                   0
2                   Excuse my Droooolll!!😍😍😍😍😍😍😍😍😍😍😍                   1
3                  Why is she so oily and shiny ? 😂😂                   0
4  Lovely. She is beautiful and a super talented ...                   2

  YouTube Channel Gender of Sport     Club Club Region
0         Arsenal          Female  Arsenal     England
1         Arsenal          Female  Arsenal     England
2         Arsenal          Female  Arsenal     England
3         Arsenal          Female  Arsenal     England
4         Arsenal          Female  Arsenal     England
Index(['Video Title', 'Like Count', 'View Count', 'Comment Count',
       'Commenter Name', 'Comment', 'Comment Like Count', 'YouTube Channel',
       'Gender of Sport', 'Club', 'Club Region'],
      dtype='object')

In [47]:
combined_juventus['Club'] = 'Juventus'
combined_juventus['Club Region'] = 'Italy'
print(combined_juventus.head())
print(combined_juventus.columns)

                                         Video Title  Like Count  View Count  \
0  Taking the game to new heights, literally,Extr...      1581.0       47154
1  Taking the game to new heights, literally,Extr...      1581.0       47154
2  Taking the game to new heights, literally,Extr...      1581.0       47154
3  Taking the game to new heights, literally,Extr...      1581.0       47154
4  Taking the game to new heights, literally,Extr...      1581.0       47154

   Comment Count                 Commenter Name  \
0              9                  @MstoKhudoyan
1              9             @marcoarcangeli526
2              9  @ForzaJuventusLaVechiaSignora
3              9                       @not_or7
4              9                   @strazzo6840

                                             Comment  Comment Like Count  \
0                                        Hala Madrid                   0
1  Vorrei che la stessa accuratezza con la quale ...                   0
2                                     Grande Amore ❤                   0
3  Can’t wait for the juve city game will be there ❤                   4
4                         Grande professore!!!👨🏽‍🏫🤍🖤                   7

  YouTube Channel Gender of Sport      Club Club Region
0        Juventus          Female  Juventus       Italy
1        Juventus          Female  Juventus       Italy
2        Juventus          Female  Juventus       Italy
3        Juventus          Female  Juventus       Italy
4        Juventus          Female  Juventus       Italy
Index(['Video Title', 'Like Count', 'View Count', 'Comment Count',
       'Commenter Name', 'Comment', 'Comment Like Count', 'YouTube Channel',
       'Gender of Sport', 'Club', 'Club Region'],
      dtype='object')

In [48]:
combined_chelsea['Club'] = 'Chelsea'
combined_chelsea['Club Region'] = 'England'

combined_corinthians['Club'] = 'Corinthians'
combined_corinthians['Club Region'] = 'Latin America'

combined_parisfc['Club'] = 'Paris FC'
combined_parisfc['Club Region'] = 'France'

combined_wolfsburg['Club'] = 'Wolfsburg'
combined_wolfsburg['Club Region'] = 'Germany'

In [49]:
def top_bottom_unique_videos_by_gender(combined_df):
    
    # Step 2: Ensure numeric types
    combined_df['View Count'] = pd.to_numeric(combined_df['View Count'], errors='coerce')
    combined_df['Comment Count'] = pd.to_numeric(combined_df['Comment Count'], errors='coerce')

    # Step 3: Drop duplicates — keep the highest View Count per Video Title
    combined_df = combined_df.sort_values('View Count', ascending=False)
    unique_videos = combined_df.drop_duplicates(subset='Video Title', keep='first')

    # Step 4: Group by Gender and extract top/bottom 3
    results = {}

    for gender, group in unique_videos.groupby('Gender of Sport'):
        top_views = group.nlargest(3, 'View Count')
        bottom_views = group.nsmallest(3, 'View Count')

        top_comments = group.nlargest(3, 'Comment Count')
        bottom_comments = group.nsmallest(3, 'Comment Count')

        results[gender] = {
            'Top 3 View Count': top_views,
            'Bottom 3 View Count': bottom_views,
            'Top 3 Comment Count': top_comments,
            'Bottom 3 Comment Count': bottom_comments
        }

    return results

In [50]:
top_bottom_unique_videos_by_gender(combined_arsenal)

{'Female': {'Top 3 View Count':                                             Video Title  Like Count  \
  894   WE'RE STILL CELEBRATING 💃 #uwcl #arsenal #awfc...       36659
  8646   ONE OF THE BEST SAVES YOU WILL SEE! DAVID RAYA 👏       58383
  9482               FABIO VIEIRA WITH A PIN POINT PASS 📍       27356

        View Count  Comment Count      Commenter Name  \
  894      6131427            724     @GranitXhakaFan
  8646     1924183            836    @mattdrayton2668
  9482     1316938            225  @katolaadewale9247

                                         Comment  Comment Like Count  \
  894   Wally needs more minutes on the pitch. 😭                   0
  8646                That's his job! Good save.                   0
  9482                                        Ok                   0

       YouTube Channel Gender of Sport     Club Club Region
  894          Arsenal          Female  Arsenal     England
  8646         Arsenal          Female  Arsenal     England
  9482         Arsenal          Female  Arsenal     England  ,
  'Bottom 3 View Count':                                             Video Title  Like Count  \
  8368  Arsenal x Sobha Realty: working together to em...         311
  4209  PRESS CONFERENCE | Renee Slegers previews Live...         279
  7234  Black Arsenal Untold | Sunny Nwachukwu  & Anit...         419

        View Count  Comment Count        Commenter Name  \
  8368        5946             10    @NeelShanker-lr2lx
  4209        6004             20         @gigaware2289
  7234        7279             25  @harrisonezeanowi276

                                                  Comment  Comment Like Count  \
  8368  Arsenal is not just a club, it's a family. I w...                  17
  4209                        I LOVE ARSENAL I HATE MAN U                   0
  7234                                               Wow❤                   1

       YouTube Channel Gender of Sport     Club Club Region
  8368         Arsenal          Female  Arsenal     England
  4209         Arsenal          Female  Arsenal     England
  7234         Arsenal          Female  Arsenal     England  ,
  'Top 3 Comment Count':                                             Video Title  Like Count  \
  8646   ONE OF THE BEST SAVES YOU WILL SEE! DAVID RAYA 👏       58383
  894   WE'RE STILL CELEBRATING 💃 #uwcl #arsenal #awfc...       36659
  6698  OUR GUNNERS TAKE ON THE LATEST QOTD 🤔 #arsenal...       32438

        View Count  Comment Count    Commenter Name  \
  8646     1924183            836  @mattdrayton2668
  894      6131427            724   @GranitXhakaFan
  6698      727835            501      @mightyskull

                                                  Comment  Comment Like Count  \
  8646                         That's his job! Good save.                   0
  894            Wally needs more minutes on the pitch. 😭                   0
  6698  If anyone in the team even came close to Marti...                   2

       YouTube Channel Gender of Sport     Club Club Region
  8646         Arsenal          Female  Arsenal     England
  894          Arsenal          Female  Arsenal     England
  6698         Arsenal          Female  Arsenal     England  ,
  'Bottom 3 Comment Count':                                             Video Title  Like Count  \
  5550                         THE BEST OF LAIA CODINA 🇪🇸         987
  6178  GAME-CHANGING MOMENTS! | Foord, Kafaji & Wienr...         366
  2438  AMAZING PASS, BEAUTIFUL FINISH! FRIDA MAANUM S...         777

        View Count  Comment Count      Commenter Name        Comment  \
  5550       10358              3    @MotivationYt-99           COYG
  6178        7557              6    @kalidkanada4299  How are you ❤
  2438       20641              7  @lourdeslapada3347         Nice ❤

        Comment Like Count YouTube Channel Gender of Sport     Club Club Region
  5550                   2         Arsenal          Female  Arsenal     England
  6178                   0         Arsenal          Female  Arsenal     England
  2438                   2         Arsenal          Female  Arsenal     England  },
 'Male': {'Top 3 View Count':                                              Video Title  Like Count  \
  19691  EXTENDED HIGHLIGHTS | Arsenal 5-1 Manchester C...       36411
  11912  BIG CHAMPIONS LEAGUE WIN 🔥 | HIGHLIGHTS | Arse...       39178
  10815  JURRIEN TIMBER WITH AN INCREDIBLE TACKLE AGAIN...       66432

         View Count  Comment Count   Commenter Name  \
  19691     3631331           1494  @sovitthapa2683
  11912     2968036           1179      @BluntRifle
  10815     2656310            435     @Ayon-Bayern

                                                   Comment  Comment Like Count  \
  19691                       Rice is an incredible player                   0
  11912  We are so lucky to have a player like Trossard...                   2
  10815  So whom are you using rn -\nCalafiori or Timber ?                   0

        YouTube Channel Gender of Sport     Club Club Region
  19691         Arsenal            Male  Arsenal     England
  11912         Arsenal            Male  Arsenal     England
  10815         Arsenal            Male  Arsenal     England  ,
  'Bottom 3 View Count':                                              Video Title  Like Count  \
  17959  Black Arsenal Untold | Robbie Kwapong and Femi...         390
  17977          Where loyalty is rewarded ☕️ | Hotels.com         682
  17442  HIGHLIGHTS | Chelsea vs Arsenal (1-0) | All th...         159

         View Count  Comment Count           Commenter Name  \
  17959        7830             43                @MO-ee3po
  17977        9181             44                   @SanTM
  17442       10454             11  @godsonthedisruptor2976

                                                   Comment  Comment Like Count  \
  17959                                                  ❤                   1
  17977  What about loyal fans and the ticket price inc...                   5
  17442                                 Wasteful Arsenal 😮                   0

        YouTube Channel Gender of Sport     Club Club Region
  17959         Arsenal            Male  Arsenal     England
  17977         Arsenal            Male  Arsenal     England
  17442         Arsenal            Male  Arsenal     England  ,
  'Top 3 Comment Count':                                              Video Title  Like Count  \
  19691  EXTENDED HIGHLIGHTS | Arsenal 5-1 Manchester C...       36411
  13805  HIGHLIGHTS | PSG vs Arsenal (2-1, 3-1 on agg) ...       11816
  11912  BIG CHAMPIONS LEAGUE WIN 🔥 | HIGHLIGHTS | Arse...       39178

         View Count  Comment Count   Commenter Name  \
  19691     3631331           1494  @sovitthapa2683
  13805     1824771           1335    @nirmoudu9319
  11912     2968036           1179      @BluntRifle

                                                   Comment  Comment Like Count  \
  19691                       Rice is an incredible player                   0
  13805  Congratulations Despite your elimination Arsen...                  16
  11912  We are so lucky to have a player like Trossard...                   2

        YouTube Channel Gender of Sport     Club Club Region
  19691         Arsenal            Male  Arsenal     England
  13805         Arsenal            Male  Arsenal     England
  11912         Arsenal            Male  Arsenal     England  ,
  'Bottom 3 Comment Count':                                              Video Title  Like Count  \
  15965  FINAL HOME GAME OF THE SEASON!| Arsenal vs New...         869
  17442  HIGHLIGHTS | Chelsea vs Arsenal (1-0) | All th...         159
  17864                          WHAT A LEAP FROM TIMBER 🫢        2330

         View Count  Comment Count           Commenter Name  \
  15965       57472              7           @Skelly.ftbl49
  17442       10454             11  @godsonthedisruptor2976
  17864       35021             13           @vinnyvyas9794

                                                   Comment  Comment Like Count  \
  15965                                            COYG✊✊✊                   1
  17442                                 Wasteful Arsenal 😮                   0
  17864  Quality leap by Timber. What a header. Brillia...                   0

        YouTube Channel Gender of Sport     Club Club Region
  15965         Arsenal            Male  Arsenal     England
  17442         Arsenal            Male  Arsenal     England
  17864         Arsenal            Male  Arsenal     England  }}

In [51]:
top_bottom_unique_videos_by_gender(combined_corinthians)

{'Female': {'Top 3 View Count':                                             Video Title  Like Count  \
  3527  OS BASTIDORES DA LOUCURA - A CONQUISTA DO 31º ...     67642.0
  2112  CORINTHIANS X INTERNACIONAL | AO VIVO | BRASIL...     16072.0
  6326  Portuguesa x Corinthians | Paulistão 2025 | PR...     10699.0

        View Count  Comment Count        Commenter Name  \
  3527      759357           1973            @slk_renan
  2112      576515             11  @ojheffrodrigues3382
  6326      515799              1   @fabionascimento505

                                                  Comment  Comment Like Count  \
  3527                                                 🦅🔥                   0
  2112                             Vaiiii Corinthians!!!!                   1
  6326  Até que 2 x 2 com gosto de derrota não foi tão...                   0

       YouTube Channel Gender of Sport         Club    Club Region
  3527  Corinthians TV          Female  Corinthians  Latin America
  2112  Corinthians TV          Female  Corinthians  Latin America
  6326  Corinthians TV          Female  Corinthians  Latin America  ,
  'Bottom 3 View Count':                                             Video Title  Like Count  \
  57    BASTIDORES DA BASE | CORINTHIANS 1 X 1 SÃO PAU...       161.0
  6393  "Fizemos um grande clássico!" Ramón Díaz anali...       251.0
  8034  Majestoso: Ramón Díaz destaca a importância de...       280.0

        View Count  Comment Count        Commenter Name  \
  57           744              4         @demellomello
  6393        1103              9     @andersondodo6832
  8034        1470             17  @BrutusJiuJitsuFiori

                                                  Comment  Comment Like Count  \
  57    Como pode arbitragem não validar o gol do Cori...                   1
  6393  Vai Corinthians! Esse ano nos guarda grandes c...                   2
  8034  Ramon mexeu mal. Tirou volante e colocou o mor...                   0

       YouTube Channel Gender of Sport         Club    Club Region
  57    Corinthians TV          Female  Corinthians  Latin America
  6393  Corinthians TV          Female  Corinthians  Latin America
  8034  Corinthians TV          Female  Corinthians  Latin America  ,
  'Top 3 Comment Count':                                             Video Title  Like Count  \
  3527  OS BASTIDORES DA LOUCURA - A CONQUISTA DO 31º ...     67642.0
  7265                                   A Garro la Ocho.     22125.0
  1764  BASTIDORES | CORINTHIANS 4 x 2 INTERNACIONAL |...     25538.0

        View Count  Comment Count   Commenter Name  \
  3527      759357           1973       @slk_renan
  7265      166116           1235  @TheGuilhermeHS
  1764      249361            483     @edsonfilms_

                                                  Comment  Comment Like Count  \
  3527                                                 🦅🔥                   0
  7265  Pataquada! A sorte é que o garro é o garro e n...                   0
  1764            Mano melhor cena Martinez dançando  kkk                   0

       YouTube Channel Gender of Sport         Club    Club Region
  3527  Corinthians TV          Female  Corinthians  Latin America
  7265  Corinthians TV          Female  Corinthians  Latin America
  1764  Corinthians TV          Female  Corinthians  Latin America  ,
  'Bottom 3 Comment Count':                                             Video Title  Like Count  \
  6326  Portuguesa x Corinthians | Paulistão 2025 | PR...     10699.0
  0     MESTRE WASHINGTON E MC SAMUKA | CORINTHIANS DO...       183.0
  407       CORINTHIANS DO PARQUE | Victão (Basquete) #03       266.0

        View Count  Comment Count       Commenter Name  \
  6326      515799              1  @fabionascimento505
  0           9623              1            @McSamuka
  407         2887              1           @Tom-l7m8b

                                                  Comment  Comment Like Count  \
  6326  Até que 2 x 2 com gosto de derrota não foi tão...                   0
  0     Satisfação Total minha Família 🦅🖤🤍 Gratidão Co...                   2
  407                                  Vai Corinthians 🤍🖤                   1

       YouTube Channel Gender of Sport         Club    Club Region
  6326  Corinthians TV          Female  Corinthians  Latin America
  0     Corinthians TV          Female  Corinthians  Latin America
  407   Corinthians TV          Female  Corinthians  Latin America  },
 'Male': {'Top 3 View Count':                                              Video Title  Like Count  \
  13589  Terça-feira de treino pro Coringão. 🏴🏳️ #VaiCo...     15179.0
  9313   CORINTHIANS X NOVORIZONTINO  | COPA DO BRASIL ...     10918.0
  15532  Corinthians 4 x 2 Internacional  | 7ª RODADA |...     13225.0

         View Count  Comment Count        Commenter Name  \
  13589      423322            344     @luizvergilio7801
  9313       385665              4  @CorinthianoFielRaiz
  15532      377136            470              @yesh.67

                                                   Comment  Comment Like Count  \
  13589                      Parabéns a doutora fico feliz                   0
  9313   Que transmissão ToP - parabéns Corinthians TV ...                   1
  15532                             Vaaaiii Corinthianssss                   2

        YouTube Channel Gender of Sport         Club    Club Region
  13589  Corinthians TV            Male  Corinthians  Latin America
  9313   Corinthians TV            Male  Corinthians  Latin America
  15532  Corinthians TV            Male  Corinthians  Latin America  ,
  'Bottom 3 View Count':                                              Video Title  Like Count  \
  11722  Ramón Díaz se diz satisfeito com o desempenho ...       202.0
  11787  "Mudou a minha vida!" Leandro Castán relembra ...       190.0
  13852  Léo Mana fala sobre a sequência de jogos e a b...       253.0

         View Count  Comment Count           Commenter Name  \
  11722         701              2  @nelsondasilvaaires1365
  11787         738              4       @nataalvesdearaujo
  13852         989              9           @Gabrielwoo10_

                                                   Comment  Comment Like Count  \
  11722  Pó meu o time ta ótimo mas vc faz cada substit...                   0
  11787                                   Vai Corinthians!                   0
  13852                                     Tá jogando bem                   2

        YouTube Channel Gender of Sport         Club    Club Region
  11722  Corinthians TV            Male  Corinthians  Latin America
  11787  Corinthians TV            Male  Corinthians  Latin America
  13852  Corinthians TV            Male  Corinthians  Latin America  ,
  'Top 3 Comment Count':                                              Video Title  Like Count  \
  9618   BASTIDORES | Corinthians 2 x 1 Santos | Paulis...     29486.0
  15532  Corinthians 4 x 2 Internacional  | 7ª RODADA |...     13225.0
  9462   O primeiro dia de Fabrizio Angileri pelo clube...     20150.0

         View Count  Comment Count      Commenter Name  \
  9618       304401            608  @klebesonleonel819
  15532      377136            470            @yesh.67
  9462       202962            458   @levinogueira7903

                                  Comment  Comment Like Count YouTube Channel  \
  9618   Garro é muito Corinthians vey 🖤🤍                   0  Corinthians TV
  15532            Vaaaiii Corinthianssss                   2  Corinthians TV
  9462        Parece que veio em forma né                   0  Corinthians TV

        Gender of Sport         Club    Club Region
  9618             Male  Corinthians  Latin America
  15532            Male  Corinthians  Latin America
  9462             Male  Corinthians  Latin America  ,
  'Bottom 3 Comment Count':                                              Video Title  Like Count  \
  12161  Yuri Alberto fala sobre a semifinal contra o S...       256.0
  13717  JOGO COMPLETO: CORINTHIANS 3 X 1 PULO FUTSAL |...      1377.0
  11767                     Elinho Corazza | PoropoPOD #08       544.0

         View Count  Comment Count            Commenter Name  \
  12161        1309              1           @hallisonsilva7
  13717       37399              2             @Rafael-iy4jc
  11767        4503              2  @EdielsonDossantos-ul2vp

                                    Comment  Comment Like Count YouTube Channel  \
  12161                               ❤❤❤❤❤                   0  Corinthians TV
  13717         Vai Corinthians 🦅🖤 VAMOOSSS                   2  Corinthians TV
  11767  Salve a todos e Vai Corinthians 🖤🦅                   0  Corinthians TV

        Gender of Sport         Club    Club Region
  12161            Male  Corinthians  Latin America
  13717            Male  Corinthians  Latin America
  11767            Male  Corinthians  Latin America  }}

In [52]:
top_bottom_unique_videos_by_gender(combined_chelsea)

{'Female': {'Top 3 View Count':                Video Title  Like Count  View Count  Comment Count  \
  1446      Niiicccoooooo 🇸🇳       74006     4908629            958
  2112  Bringing it Home 🤩 🏆       73872     3817515           1049
  4835        Shake body… 💃🏆       36717     3029236            485

              Commenter Name                                            Comment  \
  1446  @andranikintoyan1007                               Свинарник просто....
  2112   @RaquelAdrienne-v2o  petir kakek lagi ngamuk di situs  A̲M̲B̲I̲L̲4̲...
  4835        @julieross3806         Why does it all ways have to be man united

        Comment Like Count        YouTube Channel Gender of Sport     Club  \
  1446                   0  Chelsea Football Club          Female  Chelsea
  2112                   0  Chelsea Football Club          Female  Chelsea
  4835                   0  Chelsea Football Club          Female  Chelsea

       Club Region
  1446     England
  2112     England
  4835     England  ,
  'Bottom 3 View Count':                                             Video Title  Like Count  \
  8076  The future is Bright 🤩 | Millie Bright signs n...         357
  6072          Zola explores Bangkok 🇹🇭 | The Famous CFC         286
  6588  BOMPASTOR Press Conference | Chelsea Women vs ...         269

        View Count  Comment Count            Commenter Name  \
  8076        3945             23             @vidolocosmas
  6072        5219             14  @บ่าววก๊อตจุ๊กกรู้น้ะย๊ะ
  6588        5799             40              @JEUELDudley

                        Comment  Comment Like Count        YouTube Channel  \
  8076  Congratulations Captain                   2  Chelsea Football Club
  6072               ไทยแลนด์🇹🇭                   2  Chelsea Football Club
  6588                        😮                   1  Chelsea Football Club

       Gender of Sport     Club Club Region
  8076          Female  Chelsea     England
  6072          Female  Chelsea     England
  6588          Female  Chelsea     England  ,
  'Top 3 Comment Count':                Video Title  Like Count  View Count  Comment Count  \
  4383  THAT’S SO CHELSEA. 🎶       37823      936787           1232
  2112  Bringing it Home 🤩 🏆       73872     3817515           1049
  1446      Niiicccoooooo 🇸🇳       74006     4908629            958

              Commenter Name                                            Comment  \
  4383               @Bs.1st                            🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶
  2112   @RaquelAdrienne-v2o  petir kakek lagi ngamuk di situs  A̲M̲B̲I̲L̲4̲...
  1446  @andranikintoyan1007                               Свинарник просто....

        Comment Like Count        YouTube Channel Gender of Sport     Club  \
  4383                   0  Chelsea Football Club          Female  Chelsea
  2112                   0  Chelsea Football Club          Female  Chelsea
  1446                   0  Chelsea Football Club          Female  Chelsea

       Club Region
  4383     England
  2112     England
  1446     England  ,
  'Bottom 3 Comment Count':                                              Video Title  Like Count  \
  12302  Wieke Kaptein has what superstition?!? 😂 #shor...         863
  9682   BOMPASTOR Press Conference | Chelsea Women vs ...         268
  6465   BOMPASTOR Press Conference | WSL | Tottenham  ...         270

         View Count  Comment Count       Commenter Name  \
  12302       14045              1  @NicholasJasper-h4p
  9682         5883              5   @JamesMonday-zp3yi
  6465         6730              6          @CHIEF_0077

                                                   Comment  Comment Like Count  \
  12302                                                 Hi                   1
  9682   I ❤ your comment because, you speak like someo...                   1
  6465                              Walsh OUT! Nüsken IN !                   1

               YouTube Channel Gender of Sport     Club Club Region
  12302  Chelsea Football Club          Female  Chelsea     England
  9682   Chelsea Football Club          Female  Chelsea     England
  6465   Chelsea Football Club          Female  Chelsea     England  },
 'Male': {'Top 3 View Count':                                              Video Title  Like Count  \
  17990  Wolves 2-6 Chelsea | 8-GOAL THRILLER - HIGHLIG...       45723
  18529  Chelsea 3-0 Aston Villa | HIGHLIGHTS | Premier...       41637
  20005  Chelsea 0-2 Manchester City | HIGHLIGHTS | Pre...       20000

         View Count  Comment Count        Commenter Name  \
  17990     2363136           1386      @MohAmsori-kr6yk
  18529     2065324           1038  @radiansitumeang5475
  20005     2050245           1494   @sebastianadasu5775

                                              Comment  Comment Like Count  \
  17990                                        mantap                   0
  18529  Probably Cucurela is the best left back now.                   1
  20005           Nkunku and Osimhen where are you😭😭😭                   6

               YouTube Channel Gender of Sport     Club Club Region
  17990  Chelsea Football Club            Male  Chelsea     England
  18529  Chelsea Football Club            Male  Chelsea     England
  20005  Chelsea Football Club            Male  Chelsea     England  ,
  'Bottom 3 View Count':                                              Video Title  Like Count  \
  32754                      Levi's 'Games Gone' moments 😂         216
  30328  The power of football around the world 🌍 | Blu...         367
  32030  Why Football Fans Should Speak About Mental He...         464

         View Count  Comment Count Commenter Name  \
  32754        2863              7    @Ella-d6l4t
  30328        3685             11  @MeliTsabedze
  32030        6847             29     @Jarvis_66

                                                   Comment  Comment Like Count  \
  32754  Thank you so much for your hard work and the e...                   0
  30328           Give the content crew a raise. Back2Back                   9
  32030                                                  🎉                   1

               YouTube Channel Gender of Sport     Club Club Region
  32754  Chelsea Football Club            Male  Chelsea     England
  30328  Chelsea Football Club            Male  Chelsea     England
  32030  Chelsea Football Club            Male  Chelsea     England  ,
  'Top 3 Comment Count':                                              Video Title  Like Count  \
  20005  Chelsea 0-2 Manchester City | HIGHLIGHTS | Pre...       20000
  17990  Wolves 2-6 Chelsea | 8-GOAL THRILLER - HIGHLIG...       45723
  33574  SANCHO is a Blue! 💙 #shorts #chelseafc #jadons...       43986

         View Count  Comment Count       Commenter Name  \
  20005     2050245           1494  @sebastianadasu5775
  17990     2363136           1386     @MohAmsori-kr6yk
  33574      536567           1215       @tobiajani4575

                                                   Comment  Comment Like Count  \
  20005                Nkunku and Osimhen where are you😭😭😭                   6
  17990                                             mantap                   0
  33574  First to comment. Welcome star boy. Already be...                   0

               YouTube Channel Gender of Sport     Club Club Region
  20005  Chelsea Football Club            Male  Chelsea     England
  17990  Chelsea Football Club            Male  Chelsea     England
  33574  Chelsea Football Club            Male  Chelsea     England  ,
  'Bottom 3 Comment Count':                          Video Title  Like Count  View Count  Comment Count  \
  31475     50 appearances for Aggie 💙        1246       22842              7
  32754  Levi's 'Games Gone' moments 😂         216        2863              7
  29373       TAKE A BOW, ORIANE! 👏😮‍💨        1332       20267             11

        Commenter Name                                            Comment  \
  31475   @ZuluTheChef  Sam kerr might find it difficult to get back i...
  32754    @Ella-d6l4t  Thank you so much for your hard work and the e...
  29373  @MK777forlife                    Bro none is watching this match

         Comment Like Count        YouTube Channel Gender of Sport     Club  \
  31475                   5  Chelsea Football Club            Male  Chelsea
  32754                   0  Chelsea Football Club            Male  Chelsea
  29373                   0  Chelsea Football Club            Male  Chelsea

        Club Region
  31475     England
  32754     England
  29373     England  }}

In [53]:
top_bottom_unique_videos_by_gender(combined_juventus)

{'Female': {'Top 3 View Count':                                             Video Title  Like Count  \
  1684  Alisha PATAPIM 🗣️ 🤍🖤 #scudetto #celebration #j...     56374.0
  897   Which entrance is your favorite? 🔥 #womensfoot...     50539.0
  6963  They did it for real 💀 #wait #meme #trend#cele...    120859.0

        View Count  Comment Count             Commenter Name            Comment  \
  1684     6124594            830  @alessandroparrinello9962  Forza Juventus❤❤❤
  897      5137519            245               @Dou3aZniber               1010
  6963     3053712            575       @fadilspinetta-ji4ez         Forza juve

        Comment Like Count YouTube Channel Gender of Sport      Club Club Region
  1684                   0        Juventus          Female  Juventus       Italy
  897                    0        Juventus          Female  Juventus       Italy
  6963                   0        Juventus          Female  Juventus       Italy  ,
  'Bottom 3 View Count':                                             Video Title  Like Count  \
  5494  HIGHLIGHTS SERIE A | Juventus Women 1-1 Napoli...       202.0
  2895  HIGHLIGHTS Poule Scudetto | Juventus Women 0-2...       238.0
  2004  HIGHLIGHTS Serie A Poule Scudetto | Fiorentina...       256.0

        View Count  Comment Count   Commenter Name  \
  5494        3170              6  @princextreme88
  2895        3921              6    @ShortsFHDita
  2004        4170              8  @princextreme88

                                                  Comment  Comment Like Count  \
  5494                                    2 punti buttati                   1
  2895  Avete scelto un campo terribile per questo ann...                   4
  2004                                         forza juve                   1

       YouTube Channel Gender of Sport      Club Club Region
  5494        Juventus          Female  Juventus       Italy
  2895        Juventus          Female  Juventus       Italy
  2004        Juventus          Female  Juventus       Italy  ,
  'Top 3 Comment Count':                                             Video Title  Like Count  \
  3455  Let’s see who wins this McKennie jersey 🗣️⁉️ #...      3470.0
  7753  That's too easy 💀 #guess #real #sound #meme #d...     29356.0
  1684  Alisha PATAPIM 🗣️ 🤍🖤 #scudetto #celebration #j...     56374.0

        View Count  Comment Count             Commenter Name  \
  3455       39206           1669                  @lupix_13
  7753      584130           1517            @denizdeniz1444
  1684     6124594            830  @alessandroparrinello9962

                   Comment  Comment Like Count YouTube Channel Gender of Sport  \
  3455     I won, check it                   1        Juventus          Female
  7753  3 is so perfect\n😂                   0        Juventus          Female
  1684   Forza Juventus❤❤❤                   0        Juventus          Female

            Club Club Region
  3455  Juventus       Italy
  7753  Juventus       Italy
  1684  Juventus       Italy  ,
  'Bottom 3 Comment Count':                                             Video Title  Like Count  \
  2738  Freestyle is more than competition—it's self-e...      1366.0
  2741  Turns struggles into strength through Freestyl...      1380.0
  9156  Watch the @theWFFA World Cup on Juventus YT Ch...      1621.0

        View Count  Comment Count       Commenter Name  \
  2738       28142              3      @MatteoPardossi
  2741       17287              3  @alfonsocaiazzo3367
  9156       15849              4        @Khoemkunthea

                                                  Comment  Comment Like Count  \
  2738  Chi dopo la partita Juve - Genoa che é finita ...                   6
  2741                                Forzaaaa juveee❤❤❤❤                   5
  9156                                               😢😢😢😢                   0

       YouTube Channel Gender of Sport      Club Club Region
  2738        Juventus          Female  Juventus       Italy
  2741        Juventus          Female  Juventus       Italy
  9156        Juventus          Female  Juventus       Italy  },
 'Male': {'Top 3 View Count':                                              Video Title  Like Count  \
  12586                      This sequence is pure magic ✨     92901.0
  12062            A great win 🙌🎉 #win #football #juventus     48029.0
  13339  How on earth Adzic missed that shot? 🤯😭 @Pongf...     25130.0

         View Count  Comment Count         Commenter Name  \
  12586     2435686            462           @eduardo9359
  12062     1408594            595              @bluxae19
  13339      942539             18  @Community_AntiTikTok

                                                   Comment  Comment Like Count  \
  12586                           Do nada uma música Br 🇧🇷                   0
  12062  The fact that this is the OFFICIAL channel, ma...                   4
  13339                                         👏🏻👏🏻👏🏻👏🏻🤍🖤                   0

        YouTube Channel Gender of Sport      Club Club Region
  12586        Juventus            Male  Juventus       Italy
  12062        Juventus            Male  Juventus       Italy
  13339        Juventus            Male  Juventus       Italy  ,
  'Bottom 3 View Count':                                              Video Title  Like Count  \
  16521   Top 5 November Goals | Next Gen & Under 20 Teams       228.0
  16705  HIGHLIGHTS Serie C | Juventus Next Gen 0-0 Giu...       299.0
  19822  HIGHLIGHTS Primavera 1 | Torino 1-0 Juventus U...       294.0

         View Count  Comment Count        Commenter Name  \
  16521        3055              7  @5.YILDIZFENERAĞLAMA
  16705        3781              6   @akudewechannel3364
  19822        4351             16     @yudhakotrack8358

                                  Comment  Comment Like Count YouTube Channel  \
  16521                Kenan yildiz in 19                   4        Juventus
  16705              Grazie for highlight                   0        Juventus
  19822  Juventus like a toothless tiger😂                   1        Juventus

        Gender of Sport      Club Club Region
  16521            Male  Juventus       Italy
  16705            Male  Juventus       Italy
  19822            Male  Juventus       Italy  ,
  'Top 3 Comment Count':                                              Video Title  Like Count  \
  12983  Magic Yildiz 🪄✨ #juventus #football #champions...     57195.0
  12062            A great win 🙌🎉 #win #football #juventus     48029.0
  13811                  Big WIN 🔥 #juventus #seriea #meme     41639.0

         View Count  Comment Count     Commenter Name  \
  12983      873243            920        @Pølsesimon
  12062     1408594            595          @bluxae19
  13811      918007            511  @Neymar_JR123-d3h

                                                   Comment  Comment Like Count  \
  12983                                                  1                   0
  12062  The fact that this is the OFFICIAL channel, ma...                   4
  13811                          Bro roblox=====juventus☠️                   1

        YouTube Channel Gender of Sport      Club Club Region
  12983        Juventus            Male  Juventus       Italy
  12062        Juventus            Male  Juventus       Italy
  13811        Juventus            Male  Juventus       Italy  ,
  'Bottom 3 Comment Count':                                              Video Title  Like Count  \
  17030      Top 5 March GOALS | Next Gen & Under 20 Teams       231.0
  17107           Highlights Juventus 3-2 Atalanta U20 🔥🤍🖤      1154.0
  14458  That hurts… 🥹 #juventus #friends #reaction #humor      1319.0

         View Count  Comment Count    Commenter Name              Comment  \
  17030        4962              2    @massimodevivo  Forza Juventus 🤍🖤❤️
  17107       34401              4  @EsinYlmaz-wk6qf      Juventusss cool
  14458       54847              5     @Khoemkunthea              😂😂😂😂❤❤😂

         Comment Like Count YouTube Channel Gender of Sport      Club  \
  17030                   2        Juventus            Male  Juventus
  17107                   1        Juventus            Male  Juventus
  14458                   1        Juventus            Male  Juventus

        Club Region
  17030       Italy
  17107       Italy
  14458       Italy  }}

In [54]:
top_bottom_unique_videos_by_gender(combined_parisfc)

{'Female': {'Top 3 View Count':                                           Video Title  Like Count  View Count  \
  64  [UWCL] : Revivez la victoire historique des Pa...         105        6518
  84             Gaëtane Thiney, la dernière partition.          77        4761
  36                           JULIE SOYER, clap de fin          68        2682

      Comment Count       Commenter Name  \
  64             13    @didierboutet2494
  84              8  @joeldemontchat4416
  36              5          @GANG-gp4ix

                                                Comment  Comment Like Count  \
  64                                   Super les filles                   3
  84  Elle pourrait encore prolonger , elle est en t...                   0
  36                       Saint Didier Des Bois ✌️✌️✌️                   0

     YouTube Channel Gender of Sport      Club Club Region
  64        Paris FC          Female  Paris FC      France
  84        Paris FC          Female  Paris FC      France
  36        Paris FC          Female  Paris FC      France  ,
  'Bottom 3 View Count':                                            Video Title  Like Count  \
  110                           🎙 "On se doit de réagir"           7
  94          🎙 "Rester vigilant dans tous les domaines"          10
  118  🎙 "Il faut être vigilant dans la gestion du gr...           7

       View Count  Comment Count  Commenter Name  \
  110         115              4      @sbddh3832
  94          178              6    @yanndgt4482
  118         188              4  @kamelkeda7374

                                                 Comment  Comment Like Count  \
  110  Depuis leur poisson d’avril avec Usain Bolt, d...                   2
  94           Allez le Paris FC ! Vincent la légende !!                   2
  118            Aller René  tu va réussir pfc en ligue1                   1

      YouTube Channel Gender of Sport      Club Club Region
  110        Paris FC          Female  Paris FC      France
  94         Paris FC          Female  Paris FC      France
  118        Paris FC          Female  Paris FC      France  ,
  'Top 3 Comment Count':                                            Video Title  Like Count  \
  64   [UWCL] : Revivez la victoire historique des Pa...         105
  126              🎙 "Le principal obstacle, c'est nous"          27
  84              Gaëtane Thiney, la dernière partition.          77

       View Count  Comment Count       Commenter Name  \
  64         6518             13    @didierboutet2494
  126         752              9  @parisfcomostro1780
  84         4761              8  @joeldemontchat4416

                                                 Comment  Comment Like Count  \
  64                                    Super les filles                   3
  126  Je t'aime coach ! Discours parfait ! On va le ...                   5
  84   Elle pourrait encore prolonger , elle est en t...                   0

      YouTube Channel Gender of Sport      Club Club Region
  64         Paris FC          Female  Paris FC      France
  126        Paris FC          Female  Paris FC      France
  84         Paris FC          Female  Paris FC      France  ,
  'Bottom 3 Comment Count':                                            Video Title  Like Count  \
  31   [UWCL] : Paris FC - AC Sparta Prague (2-0) : l...          25
  17   🎙️ Un petit mot de la part d'Océane Picard, no...          42
  122  Direction Grenoble, au cœur du voyage des pari...          48

       View Count  Comment Count        Commenter Name  \
  31         2274              1  @christianbargain560
  17         1869              1     @JeanMichelCaniez
  122        1618              1    @tanitatikaram3656

                                                 Comment  Comment Like Count  \
  31   De très loin mon équipe favorite !!!! vive le ...                   0
  17   Bonsoir, c'est une excellente joueuse. Allez l...                   1
  122             fixed matches two idiot wrestling team                   0

      YouTube Channel Gender of Sport      Club Club Region
  31         Paris FC          Female  Paris FC      France
  17         Paris FC          Female  Paris FC      France
  122        Paris FC          Female  Paris FC      France  },
 'Male': {'Top 3 View Count':                                            Video Title  Like Count  \
  170  PARIS FC - CSC DE CAYENNE (14 - 0) - Résumé - ...        1144
  146  Conférence de presse d'Antoine Arnault et de P...         352
  259      Dans les coulisses des salons VIP du Paris FC          63

       View Count  Comment Count              Commenter Name  \
  170       67465            141  @lemarseillaisallezlom4965
  146       16542             48        @solangeouattara6970
  259        4021              5         @parisfcomostro1780

                                                 Comment  Comment Like Count  \
  170  Palmarès de Cayenne on a une marque de piment ...                   5
  146  Bravo Monsieur Président Pierre Ferracci pour ...                   0
  259  Investissez dans la sécurité plutôt MDR, ça no...                   5

      YouTube Channel Gender of Sport      Club Club Region
  170        Paris FC            Male  Paris FC      France
  146        Paris FC            Male  Paris FC      France
  259        Paris FC            Male  Paris FC      France  ,
  'Bottom 3 View Count':                                          Video Title  Like Count  View Count  \
  264  🎙 "Très satisfait de l'état mental des troupes"           7         162
  249                 🎙 "Imposer notre façon de jouer"           8         169
  231                               🎙 "Un match bonus"           8         179

       Comment Count       Commenter Name  \
  264              1            @nathan94
  249              1       @kamelkeda7374
  231              4  @parisfcomostro1780

                                                 Comment  Comment Like Count  \
  264                                                 💙🤍                   1
  249  Franchement  rien pls que René girard  ils mon...                   1
  231  On va le faire et on va aller en 16ème ! Allez...                   2

      YouTube Channel Gender of Sport      Club Club Region
  264        Paris FC            Male  Paris FC      France
  249        Paris FC            Male  Paris FC      France
  231        Paris FC            Male  Paris FC      France  ,
  'Top 3 Comment Count':                                            Video Title  Like Count  \
  170  PARIS FC - CSC DE CAYENNE (14 - 0) - Résumé - ...        1144
  146  Conférence de presse d'Antoine Arnault et de P...         352
  176                        Le récap' de la semaine #35          52

       View Count  Comment Count              Commenter Name  \
  170       67465            141  @lemarseillaisallezlom4965
  146       16542             48        @solangeouattara6970
  176        1304             10    @professeurstrausshh3391

                                                 Comment  Comment Like Count  \
  170  Palmarès de Cayenne on a une marque de piment ...                   5
  146  Bravo Monsieur Président Pierre Ferracci pour ...                   0
  176                                   Bravo pour hier!                   1

      YouTube Channel Gender of Sport      Club Club Region
  170        Paris FC            Male  Paris FC      France
  146        Paris FC            Male  Paris FC      France
  176        Paris FC            Male  Paris FC      France  ,
  'Bottom 3 Comment Count':                                            Video Title  Like Count  \
  163       Au coeur de la VINCI Mixed Cup, 2ème édition          56
  140  Paris FC - SM Caen [4-2] : le résumé de la vic...          25
  167                           Récap' de la semaine #14          31

       View Count  Comment Count     Commenter Name  \
  163        3974              1        @jorghe5819
  140        1184              1  @celticbalkan2219
  167        1172              1           @pilou75

                                                 Comment  Comment Like Count  \
  163                                  Psg city rivals??                   0
  140  I can't wait for next season to watch the Pari...                   5
  167                 Kikonda en feu devant les buts mdr                   0

      YouTube Channel Gender of Sport      Club Club Region
  163        Paris FC            Male  Paris FC      France
  140        Paris FC            Male  Paris FC      France
  167        Paris FC            Male  Paris FC      France  }}

In [55]:
top_bottom_unique_videos_by_gender(combined_wolfsburg)

{'Female': {'Top 3 View Count':                                             Video Title  Like Count  \
  2026  Amoura mit Premierentreffer ⚽️ | Highlights | ...        1364
  944   "Esst mehr Currywürste!" | Merle Frohms & Kath...         881
  1484  Mit Dank und Ehrfurcht - Alexandra Popp verabs...         878

        View Count  Comment Count         Commenter Name  \
  2026       82940            170        @aldopepeto9531
  944        78464             36  @exe-studioproduktion
  1484       67150            115    @hanslauterbach7433

                                                  Comment  Comment Like Count  \
  2026                                   The great Amoura                   0
  944   Wenn ich mich für eine von beiden entscheiden ...                   1
  1484  Liebe Alexandra, ich war immer ein großer Fan ...                   0

       YouTube Channel Gender of Sport       Club Club Region
  2026   VfL Wolfsburg          Female  Wolfsburg     Germany
  944    VfL Wolfsburg          Female  Wolfsburg     Germany
  1484   VfL Wolfsburg          Female  Wolfsburg     Germany  ,
  'Bottom 3 View Count':                                            Video Title  Like Count  \
  755  "Stimmt, sie war ein Frühstarter" 😳🚀 – Trophäe...          36
  921  Wem gehört dieser Trophäenschrank? 🏆🤔 | Fische...          54
  215  Queen Beerensteyn, incredible link-up & the BE...          63

       View Count  Comment Count Commenter Name  \
  755         331              2      @MrVI1987
  921         855              1    @19Anonym45
  215         857              2    @19Anonym45

                                                 Comment  Comment Like Count  \
  755  Hab voll das dejavu, als ob ich das schon mal ...                   0
  921                            Ganz interessant haha💚🤍                   1
  215              Mal gucken was nächste Saison wird 💚🤍                   2

      YouTube Channel Gender of Sport       Club Club Region
  755   VfL Wolfsburg          Female  Wolfsburg     Germany
  921   VfL Wolfsburg          Female  Wolfsburg     Germany
  215   VfL Wolfsburg          Female  Wolfsburg     Germany  ,
  'Top 3 Comment Count':                                             Video Title  Like Count  \
  2026  Amoura mit Premierentreffer ⚽️ | Highlights | ...        1364
  2489  Verstärkung für den Sturm! ⚡️ Mohamed Amoura s...         881
  2909  "Es war mir eine Ehre!" - Emotionale Abschieds...        1182

        View Count  Comment Count       Commenter Name  \
  2026       82940            170      @aldopepeto9531
  2489       28874            145  @mohamedjapouni1450
  2909       19317            140            @Jumo1084

                                                  Comment  Comment Like Count  \
  2026                                   The great Amoura                   0
  2489                                    ❤❤🇩🇿🇩🇿🇩🇿🇩🇿⚽⚽⚽🐐🐐                   3
  2909  Danke für die Zeit beim VfL, die ganzen Tore, ...                   5

       YouTube Channel Gender of Sport       Club Club Region
  2026   VfL Wolfsburg          Female  Wolfsburg     Germany
  2489   VfL Wolfsburg          Female  Wolfsburg     Germany
  2909   VfL Wolfsburg          Female  Wolfsburg     Germany  ,
  'Bottom 3 Comment Count':                                             Video Title  Like Count  \
  2005  Frage der Woche: Wer gewinnt im Fußball der Fr...         479
  2577                   This-or-That Urlaubs-Edition  🏖️         302
  453                 4 goal haul by Lineth Beerensteyn 🔥         203

        View Count  Comment Count Commenter Name  \
  2005       11037              1  @janmeyer8844
  2577        6167              1  @janmeyer8844
  453         3551              1  @janmeyer8844

                                       Comment  Comment Like Count  \
  2005                            Sehr gut 🐺💚🤗                   4
  2577  Ich mag  einfach Unsere wölfinnen.🐺💚♥️                   7
  453                  Einfach der Hammer💚🐺⚽️😊                   4

       YouTube Channel Gender of Sport       Club Club Region
  2005   VfL Wolfsburg          Female  Wolfsburg     Germany
  2577   VfL Wolfsburg          Female  Wolfsburg     Germany
  453    VfL Wolfsburg          Female  Wolfsburg     Germany  },
 'Male': {'Top 3 View Count':                                             Video Title  Like Count  \
  6422  🔥 Marius Müllers Kindheitstraum wird wahr! Bun...        2065
  4007  Weitschuss-Obi & Huth mit Traum-Volley! 🚀😍 Die...         198
  3297  Kantersieg in Florenz | UWCL | Highlights | AC...         459

        View Count  Comment Count       Commenter Name  \
  6422       73718             29            @SouLP196
  4007       71251             14        @jandegen9648
  3297       66874             32  @ohdearnotagain2725

                                                  Comment  Comment Like Count  \
  6422  Wir hätten ihn halten sollen. Was hast du geta...                   1
  4007                                ⚽💚🐺👸👸🏽🐺💚⚽\n🌹🌹🌹🌹🌹🌹🌹🌹                   0
  3297  My grandmother would have been a better goalke...                   2

       YouTube Channel Gender of Sport       Club Club Region
  6422   VfL Wolfsburg            Male  Wolfsburg     Germany
  4007   VfL Wolfsburg            Male  Wolfsburg     Germany
  3297   VfL Wolfsburg            Male  Wolfsburg     Germany  ,
  'Bottom 3 View Count':                                             Video Title  Like Count  \
  6391  “Zum Glück Fußballer geworden!” 🎯 – Dosenwerfe...          39
  5173  "Toast mit Honig und Smarties" 🥪🍯🍫 | Rapidfire...          42
  5127  New Record for our Rocket Man & International ...          44

        View Count  Comment Count   Commenter Name  \
  6391         560              6  @Cedric_Stoffel
  5173         601              4          @BGMP10
  5127         744              3       @freddi114

                                         Comment  Comment Like Count  \
  6391                       Frohe Weihnachten ❤                   2
  5173                                 Kofi 🇩🇪❤️                   0
  5127  Auch mal die Teams verwechseln  bei 4:00                   1

       YouTube Channel Gender of Sport       Club Club Region
  6391   VfL Wolfsburg            Male  Wolfsburg     Germany
  5173   VfL Wolfsburg            Male  Wolfsburg     Germany
  5127   VfL Wolfsburg            Male  Wolfsburg     Germany  ,
  'Top 3 Comment Count':                                             Video Title  Like Count  \
  3473  RE-LIVE  | Pressekonferenz mit Hasenhüttl und ...         295
  6194  „Müssen das zweite Tor nachlegen!“ | PK mit Ko...         180
  6276  "Called me hammer!" 🔨 | Konstantinos Koulierak...        1016

        View Count  Comment Count       Commenter Name  \
  3473       40052            137  @richtigeralman9474
  6194       13490            130   @lifesahellofaride
  6276       24551            116     @apostolisste907

                                                  Comment  Comment Like Count  \
  3473  Wie habt ihr denn den Schiri bezahlt? VW hat d...                   0
  6194  Danke Nico, war ne schön zeit und alles gute i...                   5
  6276  Wolfsburg became my favorite team watch out  f...                  83

       YouTube Channel Gender of Sport       Club Club Region
  3473   VfL Wolfsburg            Male  Wolfsburg     Germany
  6194   VfL Wolfsburg            Male  Wolfsburg     Germany
  6276   VfL Wolfsburg            Male  Wolfsburg     Germany  ,
  'Bottom 3 Comment Count':                                             Video Title  Like Count  \
  5469                  Was serviert uns der Spielplan? 😂         148
  5000  ⏳🔥 Wieviele Fragen in 60 Sekunden, Lisa Schmit...         152
  5664  Good Job, Coach! ⚽️🔥 Die schönsten Treffer von...          65

        View Count  Comment Count Commenter Name  \
  5469        3449              1    @19Anonym45
  5000        3174              1  @soybotcito25
  5664        1572              1    @19Anonym45

                                           Comment  Comment Like Count  \
  5469                                          💚🤍                   3
  5000      Wolsburg es un equipo alemán muy bueno                   3
  5664  Hauptsache Leistung an der Seitenlinie! 💚🤍                   1

       YouTube Channel Gender of Sport       Club Club Region
  5469   VfL Wolfsburg            Male  Wolfsburg     Germany
  5000   VfL Wolfsburg            Male  Wolfsburg     Germany
  5664   VfL Wolfsburg            Male  Wolfsburg     Germany  }}

In [56]:
import math

def floor_2_decimal(x):
    return math.floor(x * 100) / 100 if pd.notnull(x) else None

def video_stats_summary_by_gender(df):
    """
    Computes stats grouped by 'Gender of Sport' and prints labeled results.
    Returns a dictionary with gender keys and tuples of 6 floored averages.
    """

    df['View Count'] = pd.to_numeric(df['View Count'], errors='coerce')
    df['Comment Count'] = pd.to_numeric(df['Comment Count'], errors='coerce')

    df = df.dropna(subset=['Video Title', 'View Count', 'Comment Count', 'Gender of Sport'])

    results = {}

    for gender, group in df.groupby('Gender of Sport'):
        group = group.sort_values('View Count', ascending=False)
        unique_videos = group.drop_duplicates(subset='Video Title', keep='first')

        full_avg_view = unique_videos['View Count'].mean()
        full_avg_comment = unique_videos['Comment Count'].mean()

        top10_view_avg = unique_videos.nlargest(10, 'View Count')['View Count'].mean()
        top10_comment_avg = unique_videos.nlargest(10, 'Comment Count')['Comment Count'].mean()

        bottom10_view_avg = unique_videos.nsmallest(10, 'View Count')['View Count'].mean()
        bottom10_comment_avg = unique_videos.nsmallest(10, 'Comment Count')['Comment Count'].mean()

        # Floor rounding
        stats = tuple(map(floor_2_decimal, [
            full_avg_view,
            full_avg_comment,
            top10_view_avg,
            top10_comment_avg,
            bottom10_view_avg,
            bottom10_comment_avg
        ]))

        results[gender] = stats

        print(f"\nStats for Gender: {gender}")
        print(f"  Full average View Count      : {stats[0]}")
        print(f"  Full average Comment Count   : {stats[1]}")
        print(f"  Top 10 average View Count    : {stats[2]}")
        print(f"  Top 10 average Comment Count : {stats[3]}")
        print(f"  Bottom 10 average View Count : {stats[4]}")
        print(f"  Bottom 10 average Comment Ct : {stats[5]}")

    return results

In [57]:
video_stats_summary_by_gender(combined_arsenal)

Stats for Gender: Female
  Full average View Count      : 154124.34
  Full average Comment Count   : 93.76
  Top 10 average View Count    : 1398322.0
  Top 10 average Comment Count : 444.9
  Bottom 10 average View Count : 7749.4
  Bottom 10 average Comment Ct : 9.4

Stats for Gender: Male
  Full average View Count      : 281856.91
  Full average Comment Count   : 207.77
  Top 10 average View Count    : 1991478.1
  Top 10 average Comment Count : 1078.09
  Bottom 10 average View Count : 12588.0
  Bottom 10 average Comment Ct : 14.8

{'Female': (154124.34, 93.76, 1398322.0, 444.9, 7749.4, 9.4),
 'Male': (281856.91, 207.77, 1991478.1, 1078.09, 12588.0, 14.8)}

In [58]:
video_stats_summary_by_gender(combined_chelsea)

Stats for Gender: Female
  Full average View Count      : 114225.67
  Full average Comment Count   : 91.66
  Top 10 average View Count    : 1612391.9
  Top 10 average Comment Count : 731.1
  Bottom 10 average View Count : 6046.9
  Bottom 10 average Comment Ct : 8.6

Stats for Gender: Male
  Full average View Count      : 232284.59
  Full average Comment Count   : 244.47
  Top 10 average View Count    : 1708437.5
  Top 10 average Comment Count : 1071.9
  Bottom 10 average View Count : 8496.0
  Bottom 10 average Comment Ct : 12.3

{'Female': (114225.67, 91.66, 1612391.9, 731.1, 6046.9, 8.6),
 'Male': (232284.59, 244.47, 1708437.5, 1071.9, 8496.0, 12.3)}

In [59]:
video_stats_summary_by_gender(combined_wolfsburg)

Stats for Gender: Female
  Full average View Count      : 9446.0
  Full average Comment Count   : 14.5
  Top 10 average View Count    : 53846.1
  Top 10 average Comment Count : 91.5
  Bottom 10 average View Count : 1218.2
  Bottom 10 average Comment Ct : 1.3

Stats for Gender: Male
  Full average View Count      : 8388.11
  Full average Comment Count   : 15.83
  Top 10 average View Count    : 56468.1
  Top 10 average Comment Count : 91.9
  Bottom 10 average View Count : 845.9
  Bottom 10 average Comment Ct : 1.6

{'Female': (9446.0, 14.5, 53846.1, 91.5, 1218.2, 1.3),
 'Male': (8388.11, 15.83, 56468.1, 91.9, 845.9, 1.6)}

In [60]:
video_stats_summary_by_gender(combined_juventus)

Stats for Gender: Female
  Full average View Count      : 156914.44
  Full average Comment Count   : 64.68
  Top 10 average View Count    : 1995100.9
  Top 10 average Comment Count : 604.1
  Bottom 10 average View Count : 4421.89
  Bottom 10 average Comment Ct : 4.59

Stats for Gender: Male
  Full average View Count      : 109632.89
  Full average Comment Count   : 75.92
  Top 10 average View Count    : 935487.2
  Top 10 average Comment Count : 456.6
  Bottom 10 average View Count : 5030.39
  Bottom 10 average Comment Ct : 5.4

{'Female': (156914.44, 64.68, 1995100.9, 604.1, 4421.89, 4.59),
 'Male': (109632.89, 75.92, 935487.2, 456.6, 5030.39, 5.4)}

In [61]:
video_stats_summary_by_gender(combined_corinthians)

Stats for Gender: Female
  Full average View Count      : 48197.75
  Full average Comment Count   : 52.41
  Top 10 average View Count    : 407267.3
  Top 10 average Comment Count : 521.79
  Bottom 10 average View Count : 1697.5
  Bottom 10 average Comment Ct : 1.8

Stats for Gender: Male
  Full average View Count      : 40787.0
  Full average Comment Count   : 58.86
  Top 10 average View Count    : 317185.5
  Top 10 average Comment Count : 413.3
  Bottom 10 average View Count : 1186.5
  Bottom 10 average Comment Ct : 2.2

{'Female': (48197.75, 52.41, 407267.3, 521.79, 1697.5, 1.8),
 'Male': (40787.0, 58.86, 317185.5, 413.3, 1186.5, 2.2)}

In [62]:
video_stats_summary_by_gender(combined_parisfc)

Stats for Gender: Female
  Full average View Count      : 1046.2
  Full average Comment Count   : 3.07
  Top 10 average View Count    : 2795.0
  Top 10 average Comment Count : 7.4
  Bottom 10 average View Count : 214.1
  Bottom 10 average Comment Ct : 1.0

Stats for Gender: Male
  Full average View Count      : 2029.69
  Full average Comment Count   : 5.6
  Top 10 average View Count    : 10641.8
  Top 10 average Comment Count : 24.8
  Bottom 10 average View Count : 217.7
  Bottom 10 average Comment Ct : 1.0

{'Female': (1046.2, 3.07, 2795.0, 7.4, 214.1, 1.0),
 'Male': (2029.69, 5.6, 10641.8, 24.8, 217.7, 1.0)}

In [63]:
import numpy as np
def categorize_popularity_by_club_gender(df):
    """
    Categorize content popularity based on percentiles within each club-gender combination
    
    Args:
        df: DataFrame with columns 'View Count', 'Gender', and 'Club'
    
    Returns:
        DataFrame with added 'Popularity_Category' column
    """
    
    def assign_popularity_group(group):
        """Assign popularity categories within each club-gender group"""
        if len(group) < 3:
            # If very few samples, assign based on simple rules
            if len(group) == 1:
                return pd.Series(['Average'], index=group.index)
            elif len(group) == 2:
                sorted_group = group.sort_values('View Count')
                return pd.Series(['Low', 'High'], index=sorted_group.index)
        
        # Calculate percentiles for this specific club-gender combination
        q33 = group['View Count'].quantile(0.33)
        q67 = group['View Count'].quantile(0.67)
        
        # Assign categories based on percentiles
        conditions = [
            group['View Count'] >= q67,
            group['View Count'] >= q33,
            group['View Count'] < q33
        ]
        
        choices = ['High', 'Average', 'Low']
        
        return pd.Series(
            np.select(conditions, choices, default='Average'),
            index=group.index
        )
    
    # Group by both Club and Gender, then apply categorization
    df['Video Popularity'] = df.groupby(['Club', 'Gender of Sport']).apply(assign_popularity_group, include_groups=False).reset_index(level=[0,1], drop=True)
    
    return df

In [64]:
combined_arsenal = categorize_popularity_by_club_gender(combined_arsenal)

In [65]:
combined_parisfc = categorize_popularity_by_club_gender(combined_parisfc)
combined_chelsea = categorize_popularity_by_club_gender(combined_chelsea)
combined_corinthians = categorize_popularity_by_club_gender(combined_corinthians)
combined_juventus = categorize_popularity_by_club_gender(combined_juventus)
combined_wolfsburg = categorize_popularity_by_club_gender(combined_wolfsburg)

In [66]:
print(combined_parisfc)

                                           Video Title  Like Count  \
0    🎬 Son plus beau souvenir? Son film préféré? My...          13
1              La première interview de Sheika Scott !          14
2              La première interview de Sheika Scott !          14
3              La première interview de Sheika Scott !          14
4              La première interview de Sheika Scott !          14
..                                                 ...         ...
275  Olympique Lyonnais vs Paris FC [2-2] : Le résu...          13
276  Olympique Lyonnais vs Paris FC [2-2] : Le résu...          13
277  Un match pour l'histoire (bande annonce finale...          34
278  Paris FC - SM Caen : La conf' d'avant-match du...          20
279  Paris FC - SM Caen : La conf' d'avant-match du...          20

     View Count  Comment Count    Commenter Name  \
0          1157              2     @Abderlebig22
1           337              4         @Toniopfc
2           337              4       @poutou1554
3           337              4          @litogor
4           337              4     @Tour62Eiffel
..          ...            ...               ...
275        1107              2    @CityOfParis93
276        1107              2          @pilou75
277         561              1  @delattremartial
278         548              2    @trahlllambert
279         548              2       @poutou1554

                                               Comment  Comment Like Count  \
0           Le front Zeubi elle a mangé le synthétique                   1
1                                          Bienvenue ❤                   1
2    Ouverture prioritaire des abonnements : jeudi ...                   0
3                              Bienvenue au Paris FC 👍                   1
4    Bienvenue à Paris. J'espère que vous y serez h...                   1
..                                                 ...                 ...
275                                                NaN                   2
276  0 défaite sur les 4 matchs contre l’OL et le P...                   4
277                         allez vous pouvez le faire                   0
278  merci courage et je serai ou  stade pour soute...                   1
279  Road to ligue 1. Et après escapade Jean Bouin ...                   2

    YouTube Channel Gender of Sport      Club Club Region Video Popularity
0          Paris FC          Female  Paris FC      France          Average
1          Paris FC          Female  Paris FC      France              Low
2          Paris FC          Female  Paris FC      France              Low
3          Paris FC          Female  Paris FC      France              Low
4          Paris FC          Female  Paris FC      France              Low
..              ...             ...       ...         ...              ...
275        Paris FC            Male  Paris FC      France          Average
276        Paris FC            Male  Paris FC      France          Average
277        Paris FC            Male  Paris FC      France          Average
278        Paris FC            Male  Paris FC      France          Average
279        Paris FC            Male  Paris FC      France          Average

[280 rows x 12 columns]

In [67]:
# Clean text before detection for better accuracy
import re
from langdetect import detect
import pandas as pd

def detect_language(text):
    try:
        return detect(text)
    except:
        return 'unknown'

def clean_for_lang_detection(text):
    # Remove URLs, mentions, hashtags
    if pd.isna(text) or text is None:
        return ''
    
    # Ensure text is a string
    text = str(text)
    text = re.sub(r'http\S+|www\S+|@\w+|#\w+', '', text)
    return text.strip()

In [68]:
combined_arsenal['Language'] = combined_arsenal['Comment'].apply(
    lambda x: detect_language(clean_for_lang_detection(x))
)
combined_chelsea['Language'] = combined_chelsea['Comment'].apply(
    lambda x: detect_language(clean_for_lang_detection(x))
)
combined_juventus['Language'] = combined_juventus['Comment'].apply(
    lambda x: detect_language(clean_for_lang_detection(x))
)
combined_wolfsburg['Language'] = combined_wolfsburg['Comment'].apply(
    lambda x: detect_language(clean_for_lang_detection(x))
)
combined_parisfc['Language'] = combined_parisfc['Comment'].apply(
    lambda x: detect_language(clean_for_lang_detection(x))
)
combined_corinthians['Language'] = combined_corinthians['Comment'].apply(
    lambda x: detect_language(clean_for_lang_detection(x))
)

In [72]:
combined_all = pd.concat([combined_juventus, combined_arsenal, combined_chelsea, combined_corinthians, combined_parisfc, combined_wolfsburg], ignore_index=True)

In [74]:
combined_all['Club']

0          Juventus
1          Juventus
2          Juventus
3          Juventus
4          Juventus
            ...
102141    Wolfsburg
102142    Wolfsburg
102143    Wolfsburg
102144    Wolfsburg
102145    Wolfsburg
Name: Club, Length: 102146, dtype: object

In [75]:
combined_all['Channel Structure'] = 'Unified'

In [76]:
combined_all.to_csv("unified.csv", index=False, encoding='utf-8-sig')